/* Javascript.vala.c generated by valac 0.24.0, the Vala compiler
 * generated from Javascript.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <JavaScriptCore/JavaScript.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <gobject/gvaluecollector.h>


#define PALETE_TYPE_JAVASCRIPT (palete_javascript_get_type ())
#define PALETE_JAVASCRIPT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PALETE_TYPE_JAVASCRIPT, PaleteJavascript))
#define PALETE_JAVASCRIPT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PALETE_TYPE_JAVASCRIPT, PaleteJavascriptClass))
#define PALETE_IS_JAVASCRIPT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PALETE_TYPE_JAVASCRIPT))
#define PALETE_IS_JAVASCRIPT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PALETE_TYPE_JAVASCRIPT))
#define PALETE_JAVASCRIPT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PALETE_TYPE_JAVASCRIPT, PaleteJavascriptClass))

typedef struct _PaleteJavascript PaleteJavascript;
typedef struct _PaleteJavascriptClass PaleteJavascriptClass;
typedef struct _PaleteJavascriptPrivate PaleteJavascriptPrivate;
#define _JSGlobalContextRelease0(var) ((var == NULL) ? NULL : (var = (JSGlobalContextRelease (var), NULL)))
#define _JSClassRelease0(var) ((var == NULL) ? NULL : (var = (JSClassRelease (var), NULL)))
#define _0(var) ((var == NULL) ? NULL : (var = ( (var), NULL)))
#define _palete_javascript_unref0(var) ((var == NULL) ? NULL : (var = (palete_javascript_unref (var), NULL)))
#define _JSStringRelease0(var) ((var == NULL) ? NULL : (var = (JSStringRelease (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _PaleteParamSpecJavascript PaleteParamSpecJavascript;

struct _PaleteJavascript {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PaleteJavascriptPrivate * priv;
	void* js_global_context;
};

struct _PaleteJavascriptClass {
	GTypeClass parent_class;
	void (*finalize) (PaleteJavascript *self);
};

struct _PaleteParamSpecJavascript {
	GParamSpec parent_instance;
};


extern PaleteJavascript* palete_instance;
PaleteJavascript* palete_instance = NULL;
static gpointer palete_javascript_parent_class = NULL;

gpointer palete_javascript_ref (gpointer instance);
void palete_javascript_unref (gpointer instance);
GParamSpec* palete_param_spec_javascript (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void palete_value_set_javascript (GValue* value, gpointer v_object);
void palete_value_take_javascript (GValue* value, gpointer v_object);
gpointer palete_value_get_javascript (const GValue* value);
GType palete_javascript_get_type (void) G_GNUC_CONST;
enum  {
	PALETE_JAVASCRIPT_DUMMY_PROPERTY
};
void* palete_javascript_class_constructor (void* ctx, void* constructor, void** arguments, int arguments_length1, void** exception);
static void* _palete_javascript_class_constructor_js_core_object_call_as_constructor_callback (void* ctx, void* constructor, size_t arguments_length1, void** arguments, void** exception);
PaleteJavascript* palete_javascript_singleton (void);
PaleteJavascript* palete_javascript_new (void);
PaleteJavascript* palete_javascript_construct (GType object_type);
gboolean palete_javascript_validate (PaleteJavascript* self, const gchar* code, gchar** res);
static void palete_javascript_finalize (PaleteJavascript* obj);

static const JSStaticFunction PALETE_JAVASCRIPT_class_functions[1] = {{NULL, NULL, 0}};
static const JSClassDefinition PALETE_JAVASCRIPT_class_definition = {0, kJSClassAttributeNone, "App", NULL, NULL, PALETE_JAVASCRIPT_class_functions, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, _palete_javascript_class_constructor_js_core_object_call_as_constructor_callback, NULL, NULL};

static void* _palete_javascript_class_constructor_js_core_object_call_as_constructor_callback (void* ctx, void* constructor, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = palete_javascript_class_constructor (ctx, constructor, arguments, arguments_length1, exception);
#line 25 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	return result;
#line 81 "Javascript.vala.c"
}


void* palete_javascript_class_constructor (void* ctx, void* constructor, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	void* c = NULL;
	void* _tmp0_ = NULL;
	void* o = NULL;
	void* _tmp1_ = NULL;
	void* _tmp2_ = NULL;
#line 11 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	g_return_val_if_fail (ctx != NULL, NULL);
#line 11 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	g_return_val_if_fail (constructor != NULL, NULL);
#line 17 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp0_ = JSClassCreate (&PALETE_JAVASCRIPT_class_definition);
#line 17 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	c = _tmp0_;
#line 18 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp1_ = ctx;
#line 18 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp2_ = JSObjectMake (_tmp1_, c, NULL);
#line 18 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	o = _tmp2_;
#line 20 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	result = o;
#line 20 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_JSClassRelease0 (c);
#line 20 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	if (exception) {
#line 20 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		*exception = _vala_exception;
#line 115 "Javascript.vala.c"
	} else {
#line 20 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		_0 (_vala_exception);
#line 119 "Javascript.vala.c"
	}
#line 20 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	return result;
#line 123 "Javascript.vala.c"
}


static gpointer _palete_javascript_ref0 (gpointer self) {
#line 57 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	return self ? palete_javascript_ref (self) : NULL;
#line 130 "Javascript.vala.c"
}


PaleteJavascript* palete_javascript_singleton (void) {
	PaleteJavascript* result = NULL;
	PaleteJavascript* _tmp0_ = NULL;
	PaleteJavascript* _tmp2_ = NULL;
	PaleteJavascript* _tmp3_ = NULL;
#line 54 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp0_ = palete_instance;
#line 54 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	if (_tmp0_ == NULL) {
#line 143 "Javascript.vala.c"
		PaleteJavascript* _tmp1_ = NULL;
#line 55 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		_tmp1_ = palete_javascript_new ();
#line 55 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		_palete_javascript_unref0 (palete_instance);
#line 55 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		palete_instance = _tmp1_;
#line 151 "Javascript.vala.c"
	}
#line 57 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp2_ = palete_instance;
#line 57 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp3_ = _palete_javascript_ref0 (_tmp2_);
#line 57 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	result = _tmp3_;
#line 57 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	return result;
#line 161 "Javascript.vala.c"
}


PaleteJavascript* palete_javascript_construct (GType object_type) {
	PaleteJavascript* self = NULL;
	void* goc = NULL;
	void* _tmp0_ = NULL;
	void* _tmp1_ = NULL;
#line 59 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	self = (PaleteJavascript*) g_type_create_instance (object_type);
#line 61 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp0_ = JSClassCreate (&PALETE_JAVASCRIPT_class_definition);
#line 61 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	goc = _tmp0_;
#line 62 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp1_ = JSGlobalContextCreate (goc);
#line 62 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_JSGlobalContextRelease0 (self->js_global_context);
#line 62 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	self->js_global_context = _tmp1_;
#line 59 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_JSClassRelease0 (goc);
#line 59 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	return self;
#line 186 "Javascript.vala.c"
}


PaleteJavascript* palete_javascript_new (void) {
#line 59 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	return palete_javascript_construct (PALETE_TYPE_JAVASCRIPT);
#line 193 "Javascript.vala.c"
}


gboolean palete_javascript_validate (PaleteJavascript* self, const gchar* code, gchar** res) {
	gchar* _vala_res = NULL;
	gboolean result = FALSE;
	void* ex = NULL;
	void* ctx = NULL;
	void* _tmp0_ = NULL;
	gboolean ret = FALSE;
	void* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	void* _tmp3_ = NULL;
	void* _tmp4_ = NULL;
	void* _tmp5_ = NULL;
	gboolean _tmp6_ = FALSE;
	gboolean _tmp7_ = FALSE;
	gchar* _tmp8_ = NULL;
	void* _tmp9_ = NULL;
	void* _tmp10_ = NULL;
	gboolean _tmp11_ = FALSE;
	void* exo = NULL;
	void* _tmp12_ = NULL;
	void* _tmp13_ = NULL;
	void* _tmp14_ = NULL;
	void ** property_names = NULL;
	void* _tmp15_ = NULL;
	void* _tmp16_ = NULL;
	void ** _tmp17_ = NULL;
	void ** _tmp18_ = NULL;
	gsize _tmp19_ = 0UL;
	void* js_string = NULL;
	void* _tmp20_ = NULL;
	void* _tmp21_ = NULL;
	void* _tmp22_ = NULL;
	gchar* c_string = NULL;
	gchar* _tmp23_ = NULL;
	gchar* cv_string = NULL;
	gchar* _tmp24_ = NULL;
	gchar* _tmp49_ = NULL;
#line 66 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 66 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	g_return_val_if_fail (code != NULL, FALSE);
#line 69 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp0_ = self->js_global_context;
#line 69 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	ctx = _tmp0_;
#line 70 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp1_ = self->js_global_context;
#line 70 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp2_ = code;
#line 70 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp3_ = JSStringCreateWithUTF8CString (_tmp2_);
#line 70 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp4_ = _tmp3_;
#line 70 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp6_ = JSCheckScriptSyntax (_tmp1_, _tmp4_, NULL, 0, &_tmp5_);
#line 70 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_0 (ex);
#line 70 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	ex = _tmp5_;
#line 70 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp7_ = _tmp6_;
#line 70 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_JSStringRelease0 (_tmp4_);
#line 70 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	ret = _tmp7_;
#line 76 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp8_ = g_strdup ("");
#line 76 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_g_free0 (_vala_res);
#line 76 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_vala_res = _tmp8_;
#line 77 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp9_ = ex;
#line 77 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp10_ = ctx;
#line 77 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp11_ = JSValueIsNull (_tmp10_, _tmp9_);
#line 77 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	if (_tmp11_) {
#line 78 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		result = ret;
#line 78 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		_0 (ex);
#line 78 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		if (res) {
#line 78 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
			*res = _vala_res;
#line 284 "Javascript.vala.c"
		} else {
#line 78 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
			_g_free0 (_vala_res);
#line 288 "Javascript.vala.c"
		}
#line 78 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		return result;
#line 292 "Javascript.vala.c"
	}
#line 83 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp12_ = ex;
#line 83 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp13_ = ctx;
#line 83 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp14_ = JSValueToObject (_tmp13_, _tmp12_, NULL);
#line 83 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	exo = _tmp14_;
#line 84 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp15_ = exo;
#line 84 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp16_ = ctx;
#line 84 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp17_ = JSObjectCopyPropertyNames (_tmp16_, _tmp15_);
#line 84 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	property_names = _tmp17_;
#line 86 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp18_ = property_names;
#line 86 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp19_ = JSPropertyNameArrayGetCount (_tmp18_);
#line 86 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	g_print ("got %d props\n", (gint) _tmp19_);
#line 88 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp20_ = exo;
#line 88 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp21_ = ctx;
#line 88 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp22_ = JSValueToStringCopy (_tmp21_, _tmp20_, NULL);
#line 88 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	js_string = _tmp22_;
#line 89 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp23_ = g_new0 (gchar, 1024);
#line 89 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	c_string = _tmp23_;
#line 90 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp24_ = g_new0 (gchar, 1024);
#line 90 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	cv_string = _tmp24_;
#line 332 "Javascript.vala.c"
	{
		gint i = 0;
#line 91 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		i = 0;
#line 337 "Javascript.vala.c"
		{
			gboolean _tmp25_ = FALSE;
#line 91 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
			_tmp25_ = TRUE;
#line 91 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
			while (TRUE) {
#line 344 "Javascript.vala.c"
				gint _tmp27_ = 0;
				void ** _tmp28_ = NULL;
				gsize _tmp29_ = 0UL;
				void ** _tmp30_ = NULL;
				gint _tmp31_ = 0;
				void* _tmp32_ = NULL;
				gchar* _tmp33_ = NULL;
				gchar* _tmp34_ = NULL;
				void* _tmp35_ = NULL;
				gchar* _tmp36_ = NULL;
				gdouble val = 0.0;
				void* _tmp37_ = NULL;
				void* _tmp38_ = NULL;
				void* _tmp39_ = NULL;
				void* _tmp40_ = NULL;
				void* _tmp41_ = NULL;
				void* _tmp42_ = NULL;
				gdouble _tmp43_ = 0.0;
				gdouble _tmp44_ = 0.0;
				gint _tmp45_ = 0;
				gchar* _tmp46_ = NULL;
				gdouble _tmp47_ = 0.0;
				gchar* _tmp48_ = NULL;
#line 91 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				if (!_tmp25_) {
#line 370 "Javascript.vala.c"
					gint _tmp26_ = 0;
#line 91 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
					_tmp26_ = i;
#line 91 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
					i = _tmp26_ + 1;
#line 376 "Javascript.vala.c"
				}
#line 91 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp25_ = FALSE;
#line 91 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp27_ = i;
#line 91 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp28_ = property_names;
#line 91 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp29_ = JSPropertyNameArrayGetCount (_tmp28_);
#line 91 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				if (!(((gsize) _tmp27_) < _tmp29_)) {
#line 91 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
					break;
#line 390 "Javascript.vala.c"
				}
#line 92 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp30_ = property_names;
#line 92 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp31_ = i;
#line 92 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp32_ = JSPropertyNameArrayGetNameAtIndex (_tmp30_, (gsize) _tmp31_);
#line 92 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_JSStringRelease0 (js_string);
#line 92 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				js_string = _tmp32_;
#line 93 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp33_ = g_new0 (gchar, 1024);
#line 93 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				c_string = _tmp33_;
#line 94 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp34_ = g_new0 (gchar, 1024);
#line 94 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				cv_string = _tmp34_;
#line 95 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp35_ = js_string;
#line 95 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp36_ = c_string;
#line 95 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				JSStringGetUTF8CString (_tmp35_, _tmp36_, (gsize) 1023);
#line 96 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp37_ = exo;
#line 96 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp38_ = ctx;
#line 96 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp39_ = js_string;
#line 96 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp40_ = JSObjectGetProperty (_tmp38_, _tmp37_, _tmp39_, NULL);
#line 96 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp41_ = _tmp40_;
#line 96 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp42_ = ctx;
#line 96 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp43_ = JSValueToNumber (_tmp42_, _tmp41_, NULL);
#line 96 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp44_ = _tmp43_;
#line 96 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_0 (_tmp41_);
#line 96 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				val = _tmp44_;
#line 99 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp45_ = i;
#line 99 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp46_ = c_string;
#line 99 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp47_ = val;
#line 99 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				g_print ("\t%i: %s = %f\n", _tmp45_, (const gchar*) _tmp46_, _tmp47_);
#line 100 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				_tmp48_ = c_string;
#line 100 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
				g_free (_tmp48_);
#line 448 "Javascript.vala.c"
			}
		}
	}
#line 102 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_tmp49_ = g_strdup ("??");
#line 102 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_g_free0 (_vala_res);
#line 102 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_vala_res = _tmp49_;
#line 104 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	result = ret;
#line 104 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_JSStringRelease0 (js_string);
#line 104 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_0 (exo);
#line 104 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_0 (ex);
#line 104 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	if (res) {
#line 104 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		*res = _vala_res;
#line 470 "Javascript.vala.c"
	} else {
#line 104 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		_g_free0 (_vala_res);
#line 474 "Javascript.vala.c"
	}
#line 104 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	return result;
#line 478 "Javascript.vala.c"
}


static void palete_value_javascript_init (GValue* value) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	value->data[0].v_pointer = NULL;
#line 485 "Javascript.vala.c"
}


static void palete_value_javascript_free_value (GValue* value) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	if (value->data[0].v_pointer) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		palete_javascript_unref (value->data[0].v_pointer);
#line 494 "Javascript.vala.c"
	}
}


static void palete_value_javascript_copy_value (const GValue* src_value, GValue* dest_value) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	if (src_value->data[0].v_pointer) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		dest_value->data[0].v_pointer = palete_javascript_ref (src_value->data[0].v_pointer);
#line 504 "Javascript.vala.c"
	} else {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		dest_value->data[0].v_pointer = NULL;
#line 508 "Javascript.vala.c"
	}
}


static gpointer palete_value_javascript_peek_pointer (const GValue* value) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	return value->data[0].v_pointer;
#line 516 "Javascript.vala.c"
}


static gchar* palete_value_javascript_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	if (collect_values[0].v_pointer) {
#line 523 "Javascript.vala.c"
		PaleteJavascript* object;
		object = collect_values[0].v_pointer;
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		if (object->parent_instance.g_class == NULL) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 530 "Javascript.vala.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 534 "Javascript.vala.c"
		}
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		value->data[0].v_pointer = palete_javascript_ref (object);
#line 538 "Javascript.vala.c"
	} else {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		value->data[0].v_pointer = NULL;
#line 542 "Javascript.vala.c"
	}
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	return NULL;
#line 546 "Javascript.vala.c"
}


static gchar* palete_value_javascript_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	PaleteJavascript** object_p;
	object_p = collect_values[0].v_pointer;
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	if (!object_p) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 557 "Javascript.vala.c"
	}
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	if (!value->data[0].v_pointer) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		*object_p = NULL;
#line 563 "Javascript.vala.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		*object_p = value->data[0].v_pointer;
#line 567 "Javascript.vala.c"
	} else {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		*object_p = palete_javascript_ref (value->data[0].v_pointer);
#line 571 "Javascript.vala.c"
	}
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	return NULL;
#line 575 "Javascript.vala.c"
}


GParamSpec* palete_param_spec_javascript (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	PaleteParamSpecJavascript* spec;
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	g_return_val_if_fail (g_type_is_a (object_type, PALETE_TYPE_JAVASCRIPT), NULL);
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	return G_PARAM_SPEC (spec);
#line 589 "Javascript.vala.c"
}


gpointer palete_value_get_javascript (const GValue* value) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PALETE_TYPE_JAVASCRIPT), NULL);
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	return value->data[0].v_pointer;
#line 598 "Javascript.vala.c"
}


void palete_value_set_javascript (GValue* value, gpointer v_object) {
	PaleteJavascript* old;
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PALETE_TYPE_JAVASCRIPT));
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	old = value->data[0].v_pointer;
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	if (v_object) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, PALETE_TYPE_JAVASCRIPT));
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		value->data[0].v_pointer = v_object;
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		palete_javascript_ref (value->data[0].v_pointer);
#line 618 "Javascript.vala.c"
	} else {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		value->data[0].v_pointer = NULL;
#line 622 "Javascript.vala.c"
	}
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	if (old) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		palete_javascript_unref (old);
#line 628 "Javascript.vala.c"
	}
}


void palete_value_take_javascript (GValue* value, gpointer v_object) {
	PaleteJavascript* old;
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PALETE_TYPE_JAVASCRIPT));
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	old = value->data[0].v_pointer;
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	if (v_object) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, PALETE_TYPE_JAVASCRIPT));
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		value->data[0].v_pointer = v_object;
#line 647 "Javascript.vala.c"
	} else {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		value->data[0].v_pointer = NULL;
#line 651 "Javascript.vala.c"
	}
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	if (old) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		palete_javascript_unref (old);
#line 657 "Javascript.vala.c"
	}
}


static void palete_javascript_class_init (PaleteJavascriptClass * klass) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	palete_javascript_parent_class = g_type_class_peek_parent (klass);
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	PALETE_JAVASCRIPT_CLASS (klass)->finalize = palete_javascript_finalize;
#line 667 "Javascript.vala.c"
}


static void palete_javascript_instance_init (PaleteJavascript * self) {
#line 50 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	self->js_global_context = NULL;
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	self->ref_count = 1;
#line 676 "Javascript.vala.c"
}


static void palete_javascript_finalize (PaleteJavascript* obj) {
	PaleteJavascript * self;
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PALETE_TYPE_JAVASCRIPT, PaleteJavascript);
#line 50 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	_JSGlobalContextRelease0 (self->js_global_context);
#line 686 "Javascript.vala.c"
}


GType palete_javascript_get_type (void) {
	static volatile gsize palete_javascript_type_id__volatile = 0;
	if (g_once_init_enter (&palete_javascript_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { palete_value_javascript_init, palete_value_javascript_free_value, palete_value_javascript_copy_value, palete_value_javascript_peek_pointer, "p", palete_value_javascript_collect_value, "p", palete_value_javascript_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (PaleteJavascriptClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) palete_javascript_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PaleteJavascript), 0, (GInstanceInitFunc) palete_javascript_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType palete_javascript_type_id;
		palete_javascript_type_id = g_type_register_fundamental (g_type_fundamental_next (), "PaleteJavascript", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&palete_javascript_type_id__volatile, palete_javascript_type_id);
	}
	return palete_javascript_type_id__volatile;
}


gpointer palete_javascript_ref (gpointer instance) {
	PaleteJavascript* self;
	self = instance;
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	g_atomic_int_inc (&self->ref_count);
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	return instance;
#line 711 "Javascript.vala.c"
}


void palete_javascript_unref (gpointer instance) {
	PaleteJavascript* self;
	self = instance;
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		PALETE_JAVASCRIPT_GET_CLASS (self)->finalize (self);
#line 8 "/home/alan/gitlive/app.Builder.js/Palete/Javascript.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 724 "Javascript.vala.c"
	}
}



