/* Application.vala.c generated by valac 0.24.0, the Vala compiler
 * generated from Application.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define BUILDER4_TYPE_APPLICATION (builder4_application_get_type ())
#define BUILDER4_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BUILDER4_TYPE_APPLICATION, Builder4Application))
#define BUILDER4_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BUILDER4_TYPE_APPLICATION, Builder4ApplicationClass))
#define BUILDER4_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BUILDER4_TYPE_APPLICATION))
#define BUILDER4_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BUILDER4_TYPE_APPLICATION))
#define BUILDER4_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BUILDER4_TYPE_APPLICATION, Builder4ApplicationClass))

typedef struct _Builder4Application Builder4Application;
typedef struct _Builder4ApplicationClass Builder4ApplicationClass;
typedef struct _Builder4ApplicationPrivate Builder4ApplicationPrivate;

#define BUILDER4_APPLICATION_TYPE_TARGET (builder4_application_target_get_type ())

struct _Builder4Application {
	GtkApplication parent_instance;
	Builder4ApplicationPrivate * priv;
};

struct _Builder4ApplicationClass {
	GtkApplicationClass parent_class;
};

typedef enum  {
	BUILDER4_APPLICATION_TARGET_INT32,
	BUILDER4_APPLICATION_TARGET_STRING,
	BUILDER4_APPLICATION_TARGET_ROOTWIN
} Builder4ApplicationTarget;


static gpointer builder4_application_parent_class = NULL;

GType builder4_application_get_type (void) G_GNUC_CONST;
enum  {
	BUILDER4_APPLICATION_DUMMY_PROPERTY
};
static GType builder4_application_target_get_type (void) G_GNUC_UNUSED;
Builder4Application* builder4_application_new (void);
Builder4Application* builder4_application_construct (GType object_type);

const GtkTargetEntry BUILDER4_APPLICATION_targetList[4] = {{"INTEGER", (guint) 0, (guint) BUILDER4_APPLICATION_TARGET_INT32}, {"STRING", (guint) 0, (guint) BUILDER4_APPLICATION_TARGET_STRING}, {"text/plain", (guint) 0, (guint) BUILDER4_APPLICATION_TARGET_STRING}, {"application/x-rootwindow-drop", (guint) 0, (guint) BUILDER4_APPLICATION_TARGET_ROOTWIN}};

static GType builder4_application_target_get_type (void) {
	static volatile gsize builder4_application_target_type_id__volatile = 0;
	if (g_once_init_enter (&builder4_application_target_type_id__volatile)) {
		static const GEnumValue values[] = {{BUILDER4_APPLICATION_TARGET_INT32, "BUILDER4_APPLICATION_TARGET_INT32", "int32"}, {BUILDER4_APPLICATION_TARGET_STRING, "BUILDER4_APPLICATION_TARGET_STRING", "string"}, {BUILDER4_APPLICATION_TARGET_ROOTWIN, "BUILDER4_APPLICATION_TARGET_ROOTWIN", "rootwin"}, {0, NULL, NULL}};
		GType builder4_application_target_type_id;
		builder4_application_target_type_id = g_enum_register_static ("Builder4ApplicationTarget", values);
		g_once_init_leave (&builder4_application_target_type_id__volatile, builder4_application_target_type_id);
	}
	return builder4_application_target_type_id__volatile;
}


Builder4Application* builder4_application_construct (GType object_type) {
	Builder4Application * self = NULL;
#line 7 "/home/alan/gitlive/app.Builder.js/Builder4/Application.vala"
	self = (Builder4Application*) g_object_new (object_type, NULL);
#line 7 "/home/alan/gitlive/app.Builder.js/Builder4/Application.vala"
	return self;
#line 70 "Application.vala.c"
}


Builder4Application* builder4_application_new (void) {
#line 7 "/home/alan/gitlive/app.Builder.js/Builder4/Application.vala"
	return builder4_application_construct (BUILDER4_TYPE_APPLICATION);
#line 77 "Application.vala.c"
}


static void builder4_application_class_init (Builder4ApplicationClass * klass) {
#line 7 "/home/alan/gitlive/app.Builder.js/Builder4/Application.vala"
	builder4_application_parent_class = g_type_class_peek_parent (klass);
#line 84 "Application.vala.c"
}


static void builder4_application_instance_init (Builder4Application * self) {
}


GType builder4_application_get_type (void) {
	static volatile gsize builder4_application_type_id__volatile = 0;
	if (g_once_init_enter (&builder4_application_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Builder4ApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) builder4_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Builder4Application), 0, (GInstanceInitFunc) builder4_application_instance_init, NULL };
		GType builder4_application_type_id;
		builder4_application_type_id = g_type_register_static (GTK_TYPE_APPLICATION, "Builder4Application", &g_define_type_info, 0);
		g_once_init_leave (&builder4_application_type_id__volatile, builder4_application_type_id);
	}
	return builder4_application_type_id__volatile;
}



