/* ClutterFiles.vala.c generated by valac 0.24.0, the Vala compiler
 * generated from ClutterFiles.vala, do not modify */

/* -- to compile
valac  --pkg gio-2.0  --pkg posix  --pkg gtk+-3.0 --pkg libnotify --pkg gtksourceview-3.0  --pkg  libwnck-3.0 \
    /tmp/ClutterFiles.vala  -o /tmp/ClutterFiles
*/
/* -- to test class
static int main (string[] args) {
    Gtk.init (ref args);
    new Xcls_ClutterFiles();
    ClutterFiles.show_all();
     Gtk.main ();
    return 0;
}
*/

#include <glib.h>
#include <glib-object.h>
#include <clutter/clutter.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define TYPE_XCLS_CLUTTERFILES (xcls_clutterfiles_get_type ())
#define XCLS_CLUTTERFILES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_XCLS_CLUTTERFILES, Xcls_ClutterFiles))
#define XCLS_CLUTTERFILES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_XCLS_CLUTTERFILES, Xcls_ClutterFilesClass))
#define IS_XCLS_CLUTTERFILES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_XCLS_CLUTTERFILES))
#define IS_XCLS_CLUTTERFILES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_XCLS_CLUTTERFILES))
#define XCLS_CLUTTERFILES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_XCLS_CLUTTERFILES, Xcls_ClutterFilesClass))

typedef struct _Xcls_ClutterFiles Xcls_ClutterFiles;
typedef struct _Xcls_ClutterFilesClass Xcls_ClutterFilesClass;
typedef struct _Xcls_ClutterFilesPrivate Xcls_ClutterFilesPrivate;

#define XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT (xcls_clutterfiles_xcls_filelayout_get_type ())
#define XCLS_CLUTTERFILES_XCLS_FILELAYOUT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT, Xcls_ClutterFilesXcls_filelayout))
#define XCLS_CLUTTERFILES_XCLS_FILELAYOUT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT, Xcls_ClutterFilesXcls_filelayoutClass))
#define XCLS_CLUTTERFILES_IS_XCLS_FILELAYOUT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT))
#define XCLS_CLUTTERFILES_IS_XCLS_FILELAYOUT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT))
#define XCLS_CLUTTERFILES_XCLS_FILELAYOUT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT, Xcls_ClutterFilesXcls_filelayoutClass))

typedef struct _Xcls_ClutterFilesXcls_filelayout Xcls_ClutterFilesXcls_filelayout;
typedef struct _Xcls_ClutterFilesXcls_filelayoutClass Xcls_ClutterFilesXcls_filelayoutClass;

#define XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT_MANAGER (xcls_clutterfiles_xcls_filelayout_manager_get_type ())
#define XCLS_CLUTTERFILES_XCLS_FILELAYOUT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT_MANAGER, Xcls_ClutterFilesXcls_filelayout_manager))
#define XCLS_CLUTTERFILES_XCLS_FILELAYOUT_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT_MANAGER, Xcls_ClutterFilesXcls_filelayout_managerClass))
#define XCLS_CLUTTERFILES_IS_XCLS_FILELAYOUT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT_MANAGER))
#define XCLS_CLUTTERFILES_IS_XCLS_FILELAYOUT_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT_MANAGER))
#define XCLS_CLUTTERFILES_XCLS_FILELAYOUT_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT_MANAGER, Xcls_ClutterFilesXcls_filelayout_managerClass))

typedef struct _Xcls_ClutterFilesXcls_filelayout_manager Xcls_ClutterFilesXcls_filelayout_manager;
typedef struct _Xcls_ClutterFilesXcls_filelayout_managerClass Xcls_ClutterFilesXcls_filelayout_managerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Xcls_ClutterFilesXcls_filelayoutPrivate Xcls_ClutterFilesXcls_filelayoutPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Xcls_ClutterFilesXcls_filelayout_managerPrivate Xcls_ClutterFilesXcls_filelayout_managerPrivate;

#define PROJECT_TYPE_PROJECT (project_project_get_type ())
#define PROJECT_PROJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROJECT_TYPE_PROJECT, ProjectProject))
#define PROJECT_PROJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROJECT_TYPE_PROJECT, ProjectProjectClass))
#define PROJECT_IS_PROJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROJECT_TYPE_PROJECT))
#define PROJECT_IS_PROJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROJECT_TYPE_PROJECT))
#define PROJECT_PROJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROJECT_TYPE_PROJECT, ProjectProjectClass))

typedef struct _ProjectProject ProjectProject;
typedef struct _ProjectProjectClass ProjectProjectClass;

#define JS_RENDER_TYPE_JS_RENDER (js_render_js_render_get_type ())
#define JS_RENDER_JS_RENDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JS_RENDER_TYPE_JS_RENDER, JsRenderJsRender))
#define JS_RENDER_JS_RENDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JS_RENDER_TYPE_JS_RENDER, JsRenderJsRenderClass))
#define JS_RENDER_IS_JS_RENDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JS_RENDER_TYPE_JS_RENDER))
#define JS_RENDER_IS_JS_RENDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JS_RENDER_TYPE_JS_RENDER))
#define JS_RENDER_JS_RENDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JS_RENDER_TYPE_JS_RENDER, JsRenderJsRenderClass))

typedef struct _JsRenderJsRender JsRenderJsRender;
typedef struct _JsRenderJsRenderClass JsRenderJsRenderClass;
typedef struct _ProjectProjectPrivate ProjectProjectPrivate;

#define XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM (xcls_clutterfiles_xcls_fileitem_get_type ())
#define XCLS_CLUTTERFILES_XCLS_FILEITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM, Xcls_ClutterFilesXcls_fileitem))
#define XCLS_CLUTTERFILES_XCLS_FILEITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM, Xcls_ClutterFilesXcls_fileitemClass))
#define XCLS_CLUTTERFILES_IS_XCLS_FILEITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM))
#define XCLS_CLUTTERFILES_IS_XCLS_FILEITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM))
#define XCLS_CLUTTERFILES_XCLS_FILEITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM, Xcls_ClutterFilesXcls_fileitemClass))

typedef struct _Xcls_ClutterFilesXcls_fileitem Xcls_ClutterFilesXcls_fileitem;
typedef struct _Xcls_ClutterFilesXcls_fileitemClass Xcls_ClutterFilesXcls_fileitemClass;
typedef struct _JsRenderJsRenderPrivate JsRenderJsRenderPrivate;

#define JS_RENDER_TYPE_NODE (js_render_node_get_type ())
#define JS_RENDER_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JS_RENDER_TYPE_NODE, JsRenderNode))
#define JS_RENDER_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JS_RENDER_TYPE_NODE, JsRenderNodeClass))
#define JS_RENDER_IS_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JS_RENDER_TYPE_NODE))
#define JS_RENDER_IS_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JS_RENDER_TYPE_NODE))
#define JS_RENDER_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JS_RENDER_TYPE_NODE, JsRenderNodeClass))

typedef struct _JsRenderNode JsRenderNode;
typedef struct _JsRenderNodeClass JsRenderNodeClass;
typedef struct _Xcls_ClutterFilesXcls_fileitemPrivate Xcls_ClutterFilesXcls_fileitemPrivate;

#define XCLS_CLUTTERFILES_TYPE_XCLS_IMAGE (xcls_clutterfiles_xcls_image_get_type ())
#define XCLS_CLUTTERFILES_XCLS_IMAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_IMAGE, Xcls_ClutterFilesXcls_image))
#define XCLS_CLUTTERFILES_XCLS_IMAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_IMAGE, Xcls_ClutterFilesXcls_imageClass))
#define XCLS_CLUTTERFILES_IS_XCLS_IMAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_IMAGE))
#define XCLS_CLUTTERFILES_IS_XCLS_IMAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_IMAGE))
#define XCLS_CLUTTERFILES_XCLS_IMAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_IMAGE, Xcls_ClutterFilesXcls_imageClass))

typedef struct _Xcls_ClutterFilesXcls_image Xcls_ClutterFilesXcls_image;
typedef struct _Xcls_ClutterFilesXcls_imageClass Xcls_ClutterFilesXcls_imageClass;

#define XCLS_CLUTTERFILES_TYPE_XCLS_TITLE (xcls_clutterfiles_xcls_title_get_type ())
#define XCLS_CLUTTERFILES_XCLS_TITLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_TITLE, Xcls_ClutterFilesXcls_title))
#define XCLS_CLUTTERFILES_XCLS_TITLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_TITLE, Xcls_ClutterFilesXcls_titleClass))
#define XCLS_CLUTTERFILES_IS_XCLS_TITLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_TITLE))
#define XCLS_CLUTTERFILES_IS_XCLS_TITLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_TITLE))
#define XCLS_CLUTTERFILES_XCLS_TITLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_TITLE, Xcls_ClutterFilesXcls_titleClass))

typedef struct _Xcls_ClutterFilesXcls_title Xcls_ClutterFilesXcls_title;
typedef struct _Xcls_ClutterFilesXcls_titleClass Xcls_ClutterFilesXcls_titleClass;

#define XCLS_CLUTTERFILES_TYPE_XCLS_BOXLAYOUT5 (xcls_clutterfiles_xcls_boxlayout5_get_type ())
#define XCLS_CLUTTERFILES_XCLS_BOXLAYOUT5(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_BOXLAYOUT5, Xcls_ClutterFilesXcls_BoxLayout5))
#define XCLS_CLUTTERFILES_XCLS_BOXLAYOUT5_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_BOXLAYOUT5, Xcls_ClutterFilesXcls_BoxLayout5Class))
#define XCLS_CLUTTERFILES_IS_XCLS_BOXLAYOUT5(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_BOXLAYOUT5))
#define XCLS_CLUTTERFILES_IS_XCLS_BOXLAYOUT5_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_BOXLAYOUT5))
#define XCLS_CLUTTERFILES_XCLS_BOXLAYOUT5_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_BOXLAYOUT5, Xcls_ClutterFilesXcls_BoxLayout5Class))

typedef struct _Xcls_ClutterFilesXcls_BoxLayout5 Xcls_ClutterFilesXcls_BoxLayout5;
typedef struct _Xcls_ClutterFilesXcls_BoxLayout5Class Xcls_ClutterFilesXcls_BoxLayout5Class;
typedef struct _Xcls_ClutterFilesXcls_BoxLayout5Private Xcls_ClutterFilesXcls_BoxLayout5Private;
typedef struct _Xcls_ClutterFilesXcls_imagePrivate Xcls_ClutterFilesXcls_imagePrivate;
typedef struct _Xcls_ClutterFilesXcls_titlePrivate Xcls_ClutterFilesXcls_titlePrivate;

struct _Xcls_ClutterFiles {
	GObject parent_instance;
	Xcls_ClutterFilesPrivate * priv;
	ClutterScrollActor* el;
	Xcls_ClutterFilesXcls_filelayout* filelayout;
	Xcls_ClutterFilesXcls_filelayout_manager* filelayout_manager;
};

struct _Xcls_ClutterFilesClass {
	GObjectClass parent_class;
};

struct _Xcls_ClutterFilesPrivate {
	Xcls_ClutterFiles* _this;
};

struct _Xcls_ClutterFilesXcls_filelayout {
	GObject parent_instance;
	Xcls_ClutterFilesXcls_filelayoutPrivate * priv;
	ClutterActor* el;
};

struct _Xcls_ClutterFilesXcls_filelayoutClass {
	GObjectClass parent_class;
};

struct _Xcls_ClutterFilesXcls_filelayout_manager {
	GObject parent_instance;
	Xcls_ClutterFilesXcls_filelayout_managerPrivate * priv;
	ClutterFlowLayout* el;
};

struct _Xcls_ClutterFilesXcls_filelayout_managerClass {
	GObjectClass parent_class;
};

struct _ProjectProject {
	GObject parent_instance;
	ProjectProjectPrivate * priv;
	gchar* id;
	gchar* fn;
	gchar* name;
	gchar* runhtml;
	GeeHashMap* paths;
	GeeHashMap* files;
	gchar* xtype;
};

struct _ProjectProjectClass {
	GObjectClass parent_class;
};

typedef enum  {
	JS_RENDER_ERROR_INVALID_FORMAT
} JsRenderError;
#define JS_RENDER_ERROR js_render_error_quark ()
struct _JsRenderJsRender {
	GObject parent_instance;
	JsRenderJsRenderPrivate * priv;
	GeeArrayList* doubleStringProps;
	gchar* id;
	gchar* name;
	gchar* fullname;
	gchar* path;
	gchar* parent;
	gchar* region;
	gchar* title;
	gchar* permname;
	gchar* modOrder;
	gchar* xtype;
	ProjectProject* project;
	JsRenderNode* tree;
	GList* cn;
	gboolean hasParent;
};

struct _JsRenderJsRenderClass {
	GObjectClass parent_class;
	void (*save) (JsRenderJsRender* self);
	void (*loadItems) (JsRenderJsRender* self, GError** error);
	gchar* (*toSource) (JsRenderJsRender* self);
	gchar* (*toSourcePreview) (JsRenderJsRender* self);
	gchar* (*toValaSource) (JsRenderJsRender* self, gboolean testcompile);
};

struct _Xcls_ClutterFilesXcls_fileitem {
	GObject parent_instance;
	Xcls_ClutterFilesXcls_fileitemPrivate * priv;
	ClutterActor* el;
	Xcls_ClutterFilesXcls_image* image;
	Xcls_ClutterFilesXcls_title* title;
};

struct _Xcls_ClutterFilesXcls_fileitemClass {
	GObjectClass parent_class;
};

struct _Xcls_ClutterFilesXcls_filelayoutPrivate {
	Xcls_ClutterFiles* _this;
};

struct _Xcls_ClutterFilesXcls_filelayout_managerPrivate {
	Xcls_ClutterFiles* _this;
};

struct _Xcls_ClutterFilesXcls_fileitemPrivate {
	Xcls_ClutterFiles* _this;
};

struct _Xcls_ClutterFilesXcls_BoxLayout5 {
	GObject parent_instance;
	Xcls_ClutterFilesXcls_BoxLayout5Private * priv;
	ClutterBoxLayout* el;
};

struct _Xcls_ClutterFilesXcls_BoxLayout5Class {
	GObjectClass parent_class;
};

struct _Xcls_ClutterFilesXcls_image {
	GObject parent_instance;
	Xcls_ClutterFilesXcls_imagePrivate * priv;
	ClutterTexture* el;
};

struct _Xcls_ClutterFilesXcls_imageClass {
	GObjectClass parent_class;
};

struct _Xcls_ClutterFilesXcls_title {
	GObject parent_instance;
	Xcls_ClutterFilesXcls_titlePrivate * priv;
	ClutterText* el;
};

struct _Xcls_ClutterFilesXcls_titleClass {
	GObjectClass parent_class;
};

struct _Xcls_ClutterFilesXcls_BoxLayout5Private {
	Xcls_ClutterFiles* _this;
};

struct _Xcls_ClutterFilesXcls_imagePrivate {
	Xcls_ClutterFiles* _this;
};

struct _Xcls_ClutterFilesXcls_titlePrivate {
	Xcls_ClutterFiles* _this;
};


extern Xcls_ClutterFiles* ClutterFiles;
Xcls_ClutterFiles* ClutterFiles = NULL;
static gpointer xcls_clutterfiles_parent_class = NULL;
static gpointer xcls_clutterfiles_xcls_filelayout_parent_class = NULL;
static gpointer xcls_clutterfiles_xcls_filelayout_manager_parent_class = NULL;
static gpointer xcls_clutterfiles_xcls_fileitem_parent_class = NULL;
static gpointer xcls_clutterfiles_xcls_boxlayout5_parent_class = NULL;
static gpointer xcls_clutterfiles_xcls_image_parent_class = NULL;
static gpointer xcls_clutterfiles_xcls_title_parent_class = NULL;

GType xcls_clutterfiles_get_type (void) G_GNUC_CONST;
GType xcls_clutterfiles_xcls_filelayout_get_type (void) G_GNUC_CONST;
GType xcls_clutterfiles_xcls_filelayout_manager_get_type (void) G_GNUC_CONST;
#define XCLS_CLUTTERFILES_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_XCLS_CLUTTERFILES, Xcls_ClutterFilesPrivate))
enum  {
	XCLS_CLUTTERFILES_DUMMY_PROPERTY
};
Xcls_ClutterFiles* xcls_clutterfiles_new (void);
Xcls_ClutterFiles* xcls_clutterfiles_construct (GType object_type);
Xcls_ClutterFilesXcls_filelayout* xcls_clutterfiles_xcls_filelayout_new (Xcls_ClutterFiles* _owner);
Xcls_ClutterFilesXcls_filelayout* xcls_clutterfiles_xcls_filelayout_construct (GType object_type, Xcls_ClutterFiles* _owner);
static gboolean __lambda8_ (Xcls_ClutterFiles* self, ClutterScrollEvent* event);
static gboolean ___lambda8__clutter_actor_scroll_event (ClutterActor* _sender, ClutterScrollEvent* event, gpointer self);
void xcls_clutterfiles_set_size (Xcls_ClutterFiles* self, gfloat w, gfloat h);
GType project_project_get_type (void) G_GNUC_CONST;
void xcls_clutterfiles_show (Xcls_ClutterFiles* self, ProjectProject* pr);
GType js_render_js_render_get_type (void) G_GNUC_CONST;
GType xcls_clutterfiles_xcls_fileitem_get_type (void) G_GNUC_CONST;
Xcls_ClutterFilesXcls_fileitem* xcls_clutterfiles_xcls_fileitem_new (Xcls_ClutterFiles* _owner, JsRenderJsRender* file);
Xcls_ClutterFilesXcls_fileitem* xcls_clutterfiles_xcls_fileitem_construct (GType object_type, Xcls_ClutterFiles* _owner, JsRenderJsRender* file);
GQuark js_render_error_quark (void);
GType js_render_node_get_type (void) G_GNUC_CONST;
GType xcls_clutterfiles_xcls_image_get_type (void) G_GNUC_CONST;
GType xcls_clutterfiles_xcls_title_get_type (void) G_GNUC_CONST;
#define XCLS_CLUTTERFILES_XCLS_FILELAYOUT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT, Xcls_ClutterFilesXcls_filelayoutPrivate))
enum  {
	XCLS_CLUTTERFILES_XCLS_FILELAYOUT_DUMMY_PROPERTY
};
Xcls_ClutterFilesXcls_filelayout_manager* xcls_clutterfiles_xcls_filelayout_manager_new (Xcls_ClutterFiles* _owner);
Xcls_ClutterFilesXcls_filelayout_manager* xcls_clutterfiles_xcls_filelayout_manager_construct (GType object_type, Xcls_ClutterFiles* _owner);
static void xcls_clutterfiles_xcls_filelayout_finalize (GObject* obj);
#define XCLS_CLUTTERFILES_XCLS_FILELAYOUT_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT_MANAGER, Xcls_ClutterFilesXcls_filelayout_managerPrivate))
enum  {
	XCLS_CLUTTERFILES_XCLS_FILELAYOUT_MANAGER_DUMMY_PROPERTY
};
static void xcls_clutterfiles_xcls_filelayout_manager_finalize (GObject* obj);
#define XCLS_CLUTTERFILES_XCLS_FILEITEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM, Xcls_ClutterFilesXcls_fileitemPrivate))
enum  {
	XCLS_CLUTTERFILES_XCLS_FILEITEM_DUMMY_PROPERTY
};
GType xcls_clutterfiles_xcls_boxlayout5_get_type (void) G_GNUC_CONST;
Xcls_ClutterFilesXcls_BoxLayout5* xcls_clutterfiles_xcls_boxlayout5_new (Xcls_ClutterFiles* _owner);
Xcls_ClutterFilesXcls_BoxLayout5* xcls_clutterfiles_xcls_boxlayout5_construct (GType object_type, Xcls_ClutterFiles* _owner);
Xcls_ClutterFilesXcls_image* xcls_clutterfiles_xcls_image_new (Xcls_ClutterFiles* _owner, JsRenderJsRender* file);
Xcls_ClutterFilesXcls_image* xcls_clutterfiles_xcls_image_construct (GType object_type, Xcls_ClutterFiles* _owner, JsRenderJsRender* file);
Xcls_ClutterFilesXcls_title* xcls_clutterfiles_xcls_title_new (Xcls_ClutterFiles* _owner, JsRenderJsRender* file);
Xcls_ClutterFilesXcls_title* xcls_clutterfiles_xcls_title_construct (GType object_type, Xcls_ClutterFiles* _owner, JsRenderJsRender* file);
static void xcls_clutterfiles_xcls_fileitem_finalize (GObject* obj);
#define XCLS_CLUTTERFILES_XCLS_BOXLAYOUT5_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_CLUTTERFILES_TYPE_XCLS_BOXLAYOUT5, Xcls_ClutterFilesXcls_BoxLayout5Private))
enum  {
	XCLS_CLUTTERFILES_XCLS_BOXLAYOUT5_DUMMY_PROPERTY
};
static void xcls_clutterfiles_xcls_boxlayout5_finalize (GObject* obj);
#define XCLS_CLUTTERFILES_XCLS_IMAGE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_CLUTTERFILES_TYPE_XCLS_IMAGE, Xcls_ClutterFilesXcls_imagePrivate))
enum  {
	XCLS_CLUTTERFILES_XCLS_IMAGE_DUMMY_PROPERTY
};
gchar* js_render_js_render_getIconFile (JsRenderJsRender* self);
static void xcls_clutterfiles_xcls_image_finalize (GObject* obj);
#define XCLS_CLUTTERFILES_XCLS_TITLE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_CLUTTERFILES_TYPE_XCLS_TITLE, Xcls_ClutterFilesXcls_titlePrivate))
enum  {
	XCLS_CLUTTERFILES_XCLS_TITLE_DUMMY_PROPERTY
};
gchar* js_render_js_render_nickName (JsRenderJsRender* self);
static void xcls_clutterfiles_xcls_title_finalize (GObject* obj);
static void xcls_clutterfiles_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
#line 33 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return self ? g_object_ref (self) : NULL;
#line 373 "ClutterFiles.vala.c"
}


static gboolean __lambda8_ (Xcls_ClutterFiles* self, ClutterScrollEvent* event) {
	gboolean result = FALSE;
	gfloat y = 0.0F;
	ClutterScrollActor* _tmp0_ = NULL;
	gfloat _tmp1_ = 0.0F;
	gfloat _tmp2_ = 0.0F;
	ClutterScrollDirection dir = 0;
	ClutterScrollEvent _tmp3_ = {0};
	ClutterScrollDirection _tmp4_ = 0;
	ClutterScrollDirection _tmp5_ = 0;
	ClutterScrollEvent _tmp12_ = {0};
	gfloat _tmp13_ = 0.0F;
	gfloat _tmp14_ = 0.0F;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	ClutterScrollActor* _tmp17_ = NULL;
	gfloat _tmp18_ = 0.0F;
#line 45 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 48 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = self->el;
#line 48 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = clutter_actor_get_y ((ClutterActor*) _tmp0_);
#line 48 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = _tmp1_;
#line 48 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	y = _tmp2_;
#line 49 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = *event;
#line 49 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = _tmp3_.direction;
#line 49 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	dir = _tmp4_;
#line 50 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp5_ = dir;
#line 50 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	switch (_tmp5_) {
#line 50 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		case CLUTTER_SCROLL_UP:
#line 416 "ClutterFiles.vala.c"
		{
			gfloat _tmp6_ = 0.0F;
			ClutterScrollEvent _tmp7_ = {0};
			gfloat _tmp8_ = 0.0F;
#line 52 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
			_tmp6_ = y;
#line 52 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
			_tmp7_ = *event;
#line 52 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
			_tmp8_ = _tmp7_.y;
#line 52 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
			y = _tmp6_ + _tmp8_;
#line 53 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
			break;
#line 431 "ClutterFiles.vala.c"
		}
#line 50 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		case CLUTTER_SCROLL_DOWN:
#line 435 "ClutterFiles.vala.c"
		{
			gfloat _tmp9_ = 0.0F;
			ClutterScrollEvent _tmp10_ = {0};
			gfloat _tmp11_ = 0.0F;
#line 55 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
			_tmp9_ = y;
#line 55 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
			_tmp10_ = *event;
#line 55 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
			_tmp11_ = _tmp10_.y;
#line 55 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
			y = _tmp9_ - _tmp11_;
#line 56 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
			break;
#line 450 "ClutterFiles.vala.c"
		}
		default:
		{
#line 58 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
			result = FALSE;
#line 58 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
			return result;
#line 458 "ClutterFiles.vala.c"
		}
	}
#line 60 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp12_ = *event;
#line 60 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp13_ = _tmp12_.y;
#line 60 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp14_ = y;
#line 60 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp15_ = g_strdup_printf ("scroll event of %f  - new y = %f ", (gdouble) _tmp13_, (gdouble) _tmp14_);
#line 60 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp16_ = _tmp15_;
#line 60 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_print ("%s", _tmp16_);
#line 60 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_free0 (_tmp16_);
#line 61 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp17_ = self->el;
#line 61 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp18_ = y;
#line 61 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_y ((ClutterActor*) _tmp17_, _tmp18_);
#line 62 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	result = TRUE;
#line 62 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return result;
#line 485 "ClutterFiles.vala.c"
}


static gboolean ___lambda8__clutter_actor_scroll_event (ClutterActor* _sender, ClutterScrollEvent* event, gpointer self) {
	gboolean result;
	result = __lambda8_ ((Xcls_ClutterFiles*) self, event);
#line 45 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return result;
#line 494 "ClutterFiles.vala.c"
}


Xcls_ClutterFiles* xcls_clutterfiles_construct (GType object_type) {
	Xcls_ClutterFiles * self = NULL;
	Xcls_ClutterFiles* _tmp0_ = NULL;
	Xcls_ClutterFiles* _tmp1_ = NULL;
	ClutterScrollActor* _tmp2_ = NULL;
	Xcls_ClutterFilesXcls_filelayout* child_0 = NULL;
	Xcls_ClutterFiles* _tmp3_ = NULL;
	Xcls_ClutterFilesXcls_filelayout* _tmp4_ = NULL;
	ClutterScrollActor* _tmp5_ = NULL;
	ClutterActor* _tmp6_ = NULL;
	ClutterScrollActor* _tmp7_ = NULL;
#line 31 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = (Xcls_ClutterFiles*) g_object_new (object_type, NULL);
#line 33 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 33 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 33 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv->_this = _tmp0_;
#line 34 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _g_object_ref0 (self);
#line 34 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (ClutterFiles);
#line 34 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	ClutterFiles = _tmp1_;
#line 35 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = (ClutterScrollActor*) clutter_scroll_actor_new ();
#line 35 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp2_);
#line 35 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 35 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->el = _tmp2_;
#line 40 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = self->priv->_this;
#line 40 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = xcls_clutterfiles_xcls_filelayout_new (_tmp3_);
#line 40 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	child_0 = _tmp4_;
#line 41 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref ((GObject*) child_0);
#line 42 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp5_ = self->el;
#line 42 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp6_ = child_0->el;
#line 42 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_add_child ((ClutterActor*) _tmp5_, _tmp6_);
#line 45 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp7_ = self->el;
#line 45 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_signal_connect_object ((ClutterActor*) _tmp7_, "scroll-event", (GCallback) ___lambda8__clutter_actor_scroll_event, self, 0);
#line 31 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (child_0);
#line 31 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return self;
#line 553 "ClutterFiles.vala.c"
}


Xcls_ClutterFiles* xcls_clutterfiles_new (void) {
#line 31 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return xcls_clutterfiles_construct (TYPE_XCLS_CLUTTERFILES);
#line 560 "ClutterFiles.vala.c"
}


void xcls_clutterfiles_set_size (Xcls_ClutterFiles* self, gfloat w, gfloat h) {
	Xcls_ClutterFiles* _tmp0_ = NULL;
	Xcls_ClutterFilesXcls_filelayout_manager* _tmp1_ = NULL;
	ClutterFlowLayout* _tmp2_ = NULL;
	gfloat _tmp3_ = 0.0F;
	ClutterScrollActor* _tmp4_ = NULL;
	ClutterScrollActor* _tmp5_ = NULL;
	ClutterStage* _tmp6_ = NULL;
	gfloat _tmp7_ = 0.0F;
	gfloat _tmp8_ = 0.0F;
	ClutterScrollActor* _tmp9_ = NULL;
	ClutterStage* _tmp10_ = NULL;
	gfloat _tmp11_ = 0.0F;
	gfloat _tmp12_ = 0.0F;
	ClutterScrollActor* _tmp13_ = NULL;
#line 68 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_if_fail (self != NULL);
#line 69 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = self->priv->_this;
#line 69 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _tmp0_->filelayout_manager;
#line 69 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = _tmp1_->el;
#line 69 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = w;
#line 69 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_set (_tmp2_, "max-column-width", _tmp3_ - 150, NULL);
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = self->el;
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp5_ = self->el;
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp6_ = clutter_actor_get_stage ((ClutterActor*) _tmp5_);
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp7_ = clutter_actor_get_width ((ClutterActor*) _tmp6_);
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp8_ = _tmp7_;
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp9_ = self->el;
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp10_ = clutter_actor_get_stage ((ClutterActor*) _tmp9_);
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp11_ = clutter_actor_get_height ((ClutterActor*) _tmp10_);
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp12_ = _tmp11_;
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_size ((ClutterActor*) _tmp4_, _tmp8_ - 150, _tmp12_);
#line 72 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp13_ = self->el;
#line 72 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_position ((ClutterActor*) _tmp13_, (gfloat) 100, (gfloat) 50);
#line 615 "ClutterFiles.vala.c"
}


void xcls_clutterfiles_show (Xcls_ClutterFiles* self, ProjectProject* pr) {
	GeeMapIterator* fiter = NULL;
	ProjectProject* _tmp0_ = NULL;
	GeeHashMap* _tmp1_ = NULL;
	GeeMapIterator* _tmp2_ = NULL;
	ClutterScrollActor* _tmp23_ = NULL;
#line 74 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_if_fail (self != NULL);
#line 74 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_if_fail (pr != NULL);
#line 77 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = pr;
#line 77 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _tmp0_->files;
#line 77 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = gee_abstract_map_map_iterator ((GeeAbstractMap*) _tmp1_);
#line 77 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	fiter = _tmp2_;
#line 78 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	while (TRUE) {
#line 639 "ClutterFiles.vala.c"
		GeeMapIterator* _tmp3_ = NULL;
		gboolean _tmp4_ = FALSE;
		Xcls_ClutterFilesXcls_fileitem* a = NULL;
		GeeMapIterator* _tmp5_ = NULL;
		gpointer _tmp6_ = NULL;
		JsRenderJsRender* _tmp7_ = NULL;
		Xcls_ClutterFilesXcls_fileitem* _tmp8_ = NULL;
		Xcls_ClutterFilesXcls_fileitem* _tmp9_ = NULL;
		Xcls_ClutterFilesXcls_fileitem* _tmp10_ = NULL;
		GeeMapIterator* _tmp11_ = NULL;
		gpointer _tmp12_ = NULL;
		JsRenderJsRender* _tmp13_ = NULL;
		const gchar* _tmp14_ = NULL;
		gchar* _tmp15_ = NULL;
		gchar* _tmp16_ = NULL;
		gchar* _tmp17_ = NULL;
		gchar* _tmp18_ = NULL;
		Xcls_ClutterFilesXcls_filelayout* _tmp19_ = NULL;
		ClutterActor* _tmp20_ = NULL;
		Xcls_ClutterFilesXcls_fileitem* _tmp21_ = NULL;
		ClutterActor* _tmp22_ = NULL;
#line 78 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp3_ = fiter;
#line 78 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp4_ = gee_map_iterator_next (_tmp3_);
#line 78 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		if (!_tmp4_) {
#line 78 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
			break;
#line 669 "ClutterFiles.vala.c"
		}
#line 79 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp5_ = fiter;
#line 79 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp6_ = gee_map_iterator_get_value (_tmp5_);
#line 79 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp7_ = (JsRenderJsRender*) _tmp6_;
#line 79 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp8_ = xcls_clutterfiles_xcls_fileitem_new (self, _tmp7_);
#line 79 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp9_ = _tmp8_;
#line 79 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_g_object_unref0 (_tmp7_);
#line 79 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		a = _tmp9_;
#line 80 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp10_ = a;
#line 80 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		g_object_ref ((GObject*) _tmp10_);
#line 81 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp11_ = fiter;
#line 81 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp12_ = gee_map_iterator_get_value (_tmp11_);
#line 81 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp13_ = (JsRenderJsRender*) _tmp12_;
#line 81 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp14_ = _tmp13_->name;
#line 81 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp15_ = g_strconcat ("add ", _tmp14_, NULL);
#line 81 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp16_ = _tmp15_;
#line 81 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp17_ = g_strconcat (_tmp16_, "\n", NULL);
#line 81 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp18_ = _tmp17_;
#line 81 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		g_print ("%s", _tmp18_);
#line 81 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_g_free0 (_tmp18_);
#line 81 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_g_free0 (_tmp16_);
#line 81 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_g_object_unref0 (_tmp13_);
#line 82 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp19_ = self->filelayout;
#line 82 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp20_ = _tmp19_->el;
#line 82 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp21_ = a;
#line 82 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp22_ = _tmp21_->el;
#line 82 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		clutter_actor_add_child (_tmp20_, _tmp22_);
#line 78 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_g_object_unref0 (a);
#line 725 "ClutterFiles.vala.c"
	}
#line 84 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp23_ = self->el;
#line 84 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_show_all ((ClutterActor*) _tmp23_);
#line 74 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (fiter);
#line 733 "ClutterFiles.vala.c"
}


Xcls_ClutterFilesXcls_filelayout* xcls_clutterfiles_xcls_filelayout_construct (GType object_type, Xcls_ClutterFiles* _owner) {
	Xcls_ClutterFilesXcls_filelayout * self = NULL;
	Xcls_ClutterFiles* _tmp0_ = NULL;
	Xcls_ClutterFiles* _tmp1_ = NULL;
	Xcls_ClutterFiles* _tmp2_ = NULL;
	Xcls_ClutterFilesXcls_filelayout* _tmp3_ = NULL;
	ClutterActor* _tmp4_ = NULL;
	Xcls_ClutterFilesXcls_filelayout_manager* child_0 = NULL;
	Xcls_ClutterFiles* _tmp5_ = NULL;
	Xcls_ClutterFilesXcls_filelayout_manager* _tmp6_ = NULL;
	ClutterActor* _tmp7_ = NULL;
	ClutterFlowLayout* _tmp8_ = NULL;
	ClutterActor* _tmp9_ = NULL;
	Xcls_ClutterFiles* _tmp10_ = NULL;
	ClutterScrollActor* _tmp11_ = NULL;
	ClutterBindConstraint* _tmp12_ = NULL;
	ClutterBindConstraint* _tmp13_ = NULL;
#line 97 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 97 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = (Xcls_ClutterFilesXcls_filelayout*) g_object_new (object_type, NULL);
#line 99 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = _owner;
#line 99 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 99 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 99 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv->_this = _tmp1_;
#line 100 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = self->priv->_this;
#line 100 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = _g_object_ref0 (self);
#line 100 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (_tmp2_->filelayout);
#line 100 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_->filelayout = _tmp3_;
#line 101 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = clutter_actor_new ();
#line 101 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp4_);
#line 101 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 101 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->el = _tmp4_;
#line 106 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp5_ = self->priv->_this;
#line 106 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp6_ = xcls_clutterfiles_xcls_filelayout_manager_new (_tmp5_);
#line 106 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	child_0 = _tmp6_;
#line 107 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref ((GObject*) child_0);
#line 108 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp7_ = self->el;
#line 108 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp8_ = child_0->el;
#line 108 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_layout_manager (_tmp7_, (ClutterLayoutManager*) _tmp8_);
#line 111 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp9_ = self->el;
#line 111 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp10_ = self->priv->_this;
#line 111 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp11_ = _tmp10_->el;
#line 111 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp12_ = (ClutterBindConstraint*) clutter_bind_constraint_new ((ClutterActor*) _tmp11_, CLUTTER_BIND_SIZE, 0.0f);
#line 111 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp12_);
#line 111 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp13_ = _tmp12_;
#line 111 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_add_constraint (_tmp9_, (ClutterConstraint*) _tmp13_);
#line 111 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (_tmp13_);
#line 97 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (child_0);
#line 97 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return self;
#line 816 "ClutterFiles.vala.c"
}


Xcls_ClutterFilesXcls_filelayout* xcls_clutterfiles_xcls_filelayout_new (Xcls_ClutterFiles* _owner) {
#line 97 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return xcls_clutterfiles_xcls_filelayout_construct (XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT, _owner);
#line 823 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_filelayout_class_init (Xcls_ClutterFilesXcls_filelayoutClass * klass) {
#line 88 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	xcls_clutterfiles_xcls_filelayout_parent_class = g_type_class_peek_parent (klass);
#line 88 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_type_class_add_private (klass, sizeof (Xcls_ClutterFilesXcls_filelayoutPrivate));
#line 88 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_clutterfiles_xcls_filelayout_finalize;
#line 834 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_filelayout_instance_init (Xcls_ClutterFilesXcls_filelayout * self) {
#line 88 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv = XCLS_CLUTTERFILES_XCLS_FILELAYOUT_GET_PRIVATE (self);
#line 841 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_filelayout_finalize (GObject* obj) {
	Xcls_ClutterFilesXcls_filelayout * self;
#line 88 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT, Xcls_ClutterFilesXcls_filelayout);
#line 90 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 91 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 88 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (xcls_clutterfiles_xcls_filelayout_parent_class)->finalize (obj);
#line 855 "ClutterFiles.vala.c"
}


GType xcls_clutterfiles_xcls_filelayout_get_type (void) {
	static volatile gsize xcls_clutterfiles_xcls_filelayout_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_clutterfiles_xcls_filelayout_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_ClutterFilesXcls_filelayoutClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_clutterfiles_xcls_filelayout_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_ClutterFilesXcls_filelayout), 0, (GInstanceInitFunc) xcls_clutterfiles_xcls_filelayout_instance_init, NULL };
		GType xcls_clutterfiles_xcls_filelayout_type_id;
		xcls_clutterfiles_xcls_filelayout_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_ClutterFilesXcls_filelayout", &g_define_type_info, 0);
		g_once_init_leave (&xcls_clutterfiles_xcls_filelayout_type_id__volatile, xcls_clutterfiles_xcls_filelayout_type_id);
	}
	return xcls_clutterfiles_xcls_filelayout_type_id__volatile;
}


Xcls_ClutterFilesXcls_filelayout_manager* xcls_clutterfiles_xcls_filelayout_manager_construct (GType object_type, Xcls_ClutterFiles* _owner) {
	Xcls_ClutterFilesXcls_filelayout_manager * self = NULL;
	Xcls_ClutterFiles* _tmp0_ = NULL;
	Xcls_ClutterFiles* _tmp1_ = NULL;
	Xcls_ClutterFiles* _tmp2_ = NULL;
	Xcls_ClutterFilesXcls_filelayout_manager* _tmp3_ = NULL;
	ClutterFlowLayout* _tmp4_ = NULL;
	ClutterFlowLayout* _tmp5_ = NULL;
	ClutterFlowLayout* _tmp6_ = NULL;
	ClutterFlowLayout* _tmp7_ = NULL;
#line 129 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 129 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = (Xcls_ClutterFilesXcls_filelayout_manager*) g_object_new (object_type, NULL);
#line 131 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = _owner;
#line 131 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 131 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 131 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv->_this = _tmp1_;
#line 132 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = self->priv->_this;
#line 132 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = _g_object_ref0 (self);
#line 132 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (_tmp2_->filelayout_manager);
#line 132 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_->filelayout_manager = _tmp3_;
#line 133 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = (ClutterFlowLayout*) clutter_flow_layout_new (CLUTTER_FLOW_HORIZONTAL);
#line 133 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp4_);
#line 133 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 133 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->el = _tmp4_;
#line 138 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp5_ = self->el;
#line 138 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_flow_layout_set_column_spacing (_tmp5_, (gfloat) 20);
#line 139 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp6_ = self->el;
#line 139 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_flow_layout_set_homogeneous (_tmp6_, TRUE);
#line 140 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp7_ = self->el;
#line 140 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_flow_layout_set_row_spacing (_tmp7_, (gfloat) 20);
#line 129 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return self;
#line 923 "ClutterFiles.vala.c"
}


Xcls_ClutterFilesXcls_filelayout_manager* xcls_clutterfiles_xcls_filelayout_manager_new (Xcls_ClutterFiles* _owner) {
#line 129 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return xcls_clutterfiles_xcls_filelayout_manager_construct (XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT_MANAGER, _owner);
#line 930 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_filelayout_manager_class_init (Xcls_ClutterFilesXcls_filelayout_managerClass * klass) {
#line 120 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	xcls_clutterfiles_xcls_filelayout_manager_parent_class = g_type_class_peek_parent (klass);
#line 120 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_type_class_add_private (klass, sizeof (Xcls_ClutterFilesXcls_filelayout_managerPrivate));
#line 120 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_clutterfiles_xcls_filelayout_manager_finalize;
#line 941 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_filelayout_manager_instance_init (Xcls_ClutterFilesXcls_filelayout_manager * self) {
#line 120 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv = XCLS_CLUTTERFILES_XCLS_FILELAYOUT_MANAGER_GET_PRIVATE (self);
#line 948 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_filelayout_manager_finalize (GObject* obj) {
	Xcls_ClutterFilesXcls_filelayout_manager * self;
#line 120 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT_MANAGER, Xcls_ClutterFilesXcls_filelayout_manager);
#line 122 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 123 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 120 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (xcls_clutterfiles_xcls_filelayout_manager_parent_class)->finalize (obj);
#line 962 "ClutterFiles.vala.c"
}


GType xcls_clutterfiles_xcls_filelayout_manager_get_type (void) {
	static volatile gsize xcls_clutterfiles_xcls_filelayout_manager_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_clutterfiles_xcls_filelayout_manager_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_ClutterFilesXcls_filelayout_managerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_clutterfiles_xcls_filelayout_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_ClutterFilesXcls_filelayout_manager), 0, (GInstanceInitFunc) xcls_clutterfiles_xcls_filelayout_manager_instance_init, NULL };
		GType xcls_clutterfiles_xcls_filelayout_manager_type_id;
		xcls_clutterfiles_xcls_filelayout_manager_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_ClutterFilesXcls_filelayout_manager", &g_define_type_info, 0);
		g_once_init_leave (&xcls_clutterfiles_xcls_filelayout_manager_type_id__volatile, xcls_clutterfiles_xcls_filelayout_manager_type_id);
	}
	return xcls_clutterfiles_xcls_filelayout_manager_type_id__volatile;
}


Xcls_ClutterFilesXcls_fileitem* xcls_clutterfiles_xcls_fileitem_construct (GType object_type, Xcls_ClutterFiles* _owner, JsRenderJsRender* file) {
	Xcls_ClutterFilesXcls_fileitem * self = NULL;
	Xcls_ClutterFiles* _tmp0_ = NULL;
	Xcls_ClutterFiles* _tmp1_ = NULL;
	ClutterActor* _tmp2_ = NULL;
	Xcls_ClutterFilesXcls_BoxLayout5* child_0 = NULL;
	Xcls_ClutterFiles* _tmp3_ = NULL;
	Xcls_ClutterFilesXcls_BoxLayout5* _tmp4_ = NULL;
	ClutterActor* _tmp5_ = NULL;
	ClutterBoxLayout* _tmp6_ = NULL;
	Xcls_ClutterFilesXcls_image* child_1 = NULL;
	Xcls_ClutterFiles* _tmp7_ = NULL;
	JsRenderJsRender* _tmp8_ = NULL;
	Xcls_ClutterFilesXcls_image* _tmp9_ = NULL;
	ClutterActor* _tmp10_ = NULL;
	ClutterTexture* _tmp11_ = NULL;
	Xcls_ClutterFilesXcls_image* _tmp12_ = NULL;
	Xcls_ClutterFilesXcls_title* child_2 = NULL;
	Xcls_ClutterFiles* _tmp13_ = NULL;
	JsRenderJsRender* _tmp14_ = NULL;
	Xcls_ClutterFilesXcls_title* _tmp15_ = NULL;
	ClutterActor* _tmp16_ = NULL;
	ClutterText* _tmp17_ = NULL;
	Xcls_ClutterFilesXcls_title* _tmp18_ = NULL;
	ClutterActor* _tmp19_ = NULL;
#line 158 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 158 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (file != NULL, NULL);
#line 158 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = (Xcls_ClutterFilesXcls_fileitem*) g_object_new (object_type, NULL);
#line 160 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = _owner;
#line 160 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 160 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 160 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv->_this = _tmp1_;
#line 161 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = clutter_actor_new ();
#line 161 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp2_);
#line 161 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 161 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->el = _tmp2_;
#line 166 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = self->priv->_this;
#line 166 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = xcls_clutterfiles_xcls_boxlayout5_new (_tmp3_);
#line 166 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	child_0 = _tmp4_;
#line 167 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref ((GObject*) child_0);
#line 168 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp5_ = self->el;
#line 168 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp6_ = child_0->el;
#line 168 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_layout_manager (_tmp5_, (ClutterLayoutManager*) _tmp6_);
#line 169 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp7_ = self->priv->_this;
#line 169 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp8_ = file;
#line 169 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp9_ = xcls_clutterfiles_xcls_image_new (_tmp7_, _tmp8_);
#line 169 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	child_1 = _tmp9_;
#line 170 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref ((GObject*) child_1);
#line 171 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp10_ = self->el;
#line 171 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp11_ = child_1->el;
#line 171 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_add_child (_tmp10_, (ClutterActor*) _tmp11_);
#line 172 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp12_ = _g_object_ref0 (child_1);
#line 172 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->image);
#line 172 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->image = _tmp12_;
#line 173 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp13_ = self->priv->_this;
#line 173 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp14_ = file;
#line 173 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp15_ = xcls_clutterfiles_xcls_title_new (_tmp13_, _tmp14_);
#line 173 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	child_2 = _tmp15_;
#line 174 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref ((GObject*) child_2);
#line 175 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp16_ = self->el;
#line 175 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp17_ = child_2->el;
#line 175 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_add_child (_tmp16_, (ClutterActor*) _tmp17_);
#line 176 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp18_ = _g_object_ref0 (child_2);
#line 176 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->title);
#line 176 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->title = _tmp18_;
#line 179 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp19_ = self->el;
#line 179 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_size (_tmp19_, (gfloat) 100, (gfloat) 100);
#line 158 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (child_2);
#line 158 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (child_1);
#line 158 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (child_0);
#line 158 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return self;
#line 1095 "ClutterFiles.vala.c"
}


Xcls_ClutterFilesXcls_fileitem* xcls_clutterfiles_xcls_fileitem_new (Xcls_ClutterFiles* _owner, JsRenderJsRender* file) {
#line 158 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return xcls_clutterfiles_xcls_fileitem_construct (XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM, _owner, file);
#line 1102 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_fileitem_class_init (Xcls_ClutterFilesXcls_fileitemClass * klass) {
#line 147 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	xcls_clutterfiles_xcls_fileitem_parent_class = g_type_class_peek_parent (klass);
#line 147 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_type_class_add_private (klass, sizeof (Xcls_ClutterFilesXcls_fileitemPrivate));
#line 147 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_clutterfiles_xcls_fileitem_finalize;
#line 1113 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_fileitem_instance_init (Xcls_ClutterFilesXcls_fileitem * self) {
#line 147 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv = XCLS_CLUTTERFILES_XCLS_FILEITEM_GET_PRIVATE (self);
#line 1120 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_fileitem_finalize (GObject* obj) {
	Xcls_ClutterFilesXcls_fileitem * self;
#line 147 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM, Xcls_ClutterFilesXcls_fileitem);
#line 149 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 150 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 154 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->image);
#line 155 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->title);
#line 147 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (xcls_clutterfiles_xcls_fileitem_parent_class)->finalize (obj);
#line 1138 "ClutterFiles.vala.c"
}


GType xcls_clutterfiles_xcls_fileitem_get_type (void) {
	static volatile gsize xcls_clutterfiles_xcls_fileitem_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_clutterfiles_xcls_fileitem_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_ClutterFilesXcls_fileitemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_clutterfiles_xcls_fileitem_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_ClutterFilesXcls_fileitem), 0, (GInstanceInitFunc) xcls_clutterfiles_xcls_fileitem_instance_init, NULL };
		GType xcls_clutterfiles_xcls_fileitem_type_id;
		xcls_clutterfiles_xcls_fileitem_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_ClutterFilesXcls_fileitem", &g_define_type_info, 0);
		g_once_init_leave (&xcls_clutterfiles_xcls_fileitem_type_id__volatile, xcls_clutterfiles_xcls_fileitem_type_id);
	}
	return xcls_clutterfiles_xcls_fileitem_type_id__volatile;
}


Xcls_ClutterFilesXcls_BoxLayout5* xcls_clutterfiles_xcls_boxlayout5_construct (GType object_type, Xcls_ClutterFiles* _owner) {
	Xcls_ClutterFilesXcls_BoxLayout5 * self = NULL;
	Xcls_ClutterFiles* _tmp0_ = NULL;
	Xcls_ClutterFiles* _tmp1_ = NULL;
	ClutterBoxLayout* _tmp2_ = NULL;
	ClutterBoxLayout* _tmp3_ = NULL;
	ClutterBoxLayout* _tmp4_ = NULL;
#line 195 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 195 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = (Xcls_ClutterFilesXcls_BoxLayout5*) g_object_new (object_type, NULL);
#line 197 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = _owner;
#line 197 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 197 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 197 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv->_this = _tmp1_;
#line 198 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = (ClutterBoxLayout*) clutter_box_layout_new ();
#line 198 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp2_);
#line 198 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 198 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->el = _tmp2_;
#line 203 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = self->el;
#line 203 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_box_layout_set_orientation (_tmp3_, CLUTTER_ORIENTATION_VERTICAL);
#line 204 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = self->el;
#line 204 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_box_layout_set_spacing (_tmp4_, (guint) 4);
#line 195 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return self;
#line 1191 "ClutterFiles.vala.c"
}


Xcls_ClutterFilesXcls_BoxLayout5* xcls_clutterfiles_xcls_boxlayout5_new (Xcls_ClutterFiles* _owner) {
#line 195 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return xcls_clutterfiles_xcls_boxlayout5_construct (XCLS_CLUTTERFILES_TYPE_XCLS_BOXLAYOUT5, _owner);
#line 1198 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_boxlayout5_class_init (Xcls_ClutterFilesXcls_BoxLayout5Class * klass) {
#line 186 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	xcls_clutterfiles_xcls_boxlayout5_parent_class = g_type_class_peek_parent (klass);
#line 186 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_type_class_add_private (klass, sizeof (Xcls_ClutterFilesXcls_BoxLayout5Private));
#line 186 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_clutterfiles_xcls_boxlayout5_finalize;
#line 1209 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_boxlayout5_instance_init (Xcls_ClutterFilesXcls_BoxLayout5 * self) {
#line 186 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv = XCLS_CLUTTERFILES_XCLS_BOXLAYOUT5_GET_PRIVATE (self);
#line 1216 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_boxlayout5_finalize (GObject* obj) {
	Xcls_ClutterFilesXcls_BoxLayout5 * self;
#line 186 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_CLUTTERFILES_TYPE_XCLS_BOXLAYOUT5, Xcls_ClutterFilesXcls_BoxLayout5);
#line 188 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 189 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 186 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (xcls_clutterfiles_xcls_boxlayout5_parent_class)->finalize (obj);
#line 1230 "ClutterFiles.vala.c"
}


GType xcls_clutterfiles_xcls_boxlayout5_get_type (void) {
	static volatile gsize xcls_clutterfiles_xcls_boxlayout5_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_clutterfiles_xcls_boxlayout5_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_ClutterFilesXcls_BoxLayout5Class), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_clutterfiles_xcls_boxlayout5_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_ClutterFilesXcls_BoxLayout5), 0, (GInstanceInitFunc) xcls_clutterfiles_xcls_boxlayout5_instance_init, NULL };
		GType xcls_clutterfiles_xcls_boxlayout5_type_id;
		xcls_clutterfiles_xcls_boxlayout5_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_ClutterFilesXcls_BoxLayout5", &g_define_type_info, 0);
		g_once_init_leave (&xcls_clutterfiles_xcls_boxlayout5_type_id__volatile, xcls_clutterfiles_xcls_boxlayout5_type_id);
	}
	return xcls_clutterfiles_xcls_boxlayout5_type_id__volatile;
}


Xcls_ClutterFilesXcls_image* xcls_clutterfiles_xcls_image_construct (GType object_type, Xcls_ClutterFiles* _owner, JsRenderJsRender* file) {
	Xcls_ClutterFilesXcls_image * self = NULL;
	Xcls_ClutterFiles* _tmp0_ = NULL;
	Xcls_ClutterFiles* _tmp1_ = NULL;
	ClutterTexture* _tmp2_ = NULL;
	JsRenderJsRender* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	ClutterTexture* _tmp6_ = NULL;
	ClutterTexture* _tmp7_ = NULL;
	ClutterTexture* _tmp8_ = NULL;
	ClutterTexture* _tmp9_ = NULL;
	ClutterTexture* _tmp10_ = NULL;
	ClutterTexture* _tmp11_ = NULL;
	ClutterTexture* _tmp12_ = NULL;
	GError * _inner_error_ = NULL;
#line 220 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 220 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (file != NULL, NULL);
#line 220 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = (Xcls_ClutterFilesXcls_image*) g_object_new (object_type, NULL);
#line 222 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = _owner;
#line 222 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 222 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 222 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv->_this = _tmp1_;
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = file;
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = js_render_js_render_getIconFile (_tmp3_);
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp5_ = _tmp4_;
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp6_ = (ClutterTexture*) clutter_texture_new_from_file (_tmp5_, &_inner_error_);
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp6_);
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp7_ = _tmp6_;
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_free0 (_tmp5_);
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = _tmp7_;
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	if (_inner_error_ != NULL) {
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		g_clear_error (&_inner_error_);
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		return NULL;
#line 1300 "ClutterFiles.vala.c"
	}
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp8_ = _tmp2_;
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = NULL;
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp8_);
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->el = _tmp8_;
#line 228 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp9_ = self->el;
#line 228 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_x_align ((ClutterActor*) _tmp9_, CLUTTER_ACTOR_ALIGN_START);
#line 229 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp10_ = self->el;
#line 229 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_x_expand ((ClutterActor*) _tmp10_, TRUE);
#line 230 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp11_ = self->el;
#line 230 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_y_align ((ClutterActor*) _tmp11_, CLUTTER_ACTOR_ALIGN_START);
#line 231 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp12_ = self->el;
#line 231 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_y_expand ((ClutterActor*) _tmp12_, FALSE);
#line 220 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (_tmp2_);
#line 220 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return self;
#line 1332 "ClutterFiles.vala.c"
}


Xcls_ClutterFilesXcls_image* xcls_clutterfiles_xcls_image_new (Xcls_ClutterFiles* _owner, JsRenderJsRender* file) {
#line 220 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return xcls_clutterfiles_xcls_image_construct (XCLS_CLUTTERFILES_TYPE_XCLS_IMAGE, _owner, file);
#line 1339 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_image_class_init (Xcls_ClutterFilesXcls_imageClass * klass) {
#line 211 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	xcls_clutterfiles_xcls_image_parent_class = g_type_class_peek_parent (klass);
#line 211 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_type_class_add_private (klass, sizeof (Xcls_ClutterFilesXcls_imagePrivate));
#line 211 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_clutterfiles_xcls_image_finalize;
#line 1350 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_image_instance_init (Xcls_ClutterFilesXcls_image * self) {
#line 211 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv = XCLS_CLUTTERFILES_XCLS_IMAGE_GET_PRIVATE (self);
#line 1357 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_image_finalize (GObject* obj) {
	Xcls_ClutterFilesXcls_image * self;
#line 211 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_CLUTTERFILES_TYPE_XCLS_IMAGE, Xcls_ClutterFilesXcls_image);
#line 213 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 214 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 211 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (xcls_clutterfiles_xcls_image_parent_class)->finalize (obj);
#line 1371 "ClutterFiles.vala.c"
}


GType xcls_clutterfiles_xcls_image_get_type (void) {
	static volatile gsize xcls_clutterfiles_xcls_image_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_clutterfiles_xcls_image_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_ClutterFilesXcls_imageClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_clutterfiles_xcls_image_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_ClutterFilesXcls_image), 0, (GInstanceInitFunc) xcls_clutterfiles_xcls_image_instance_init, NULL };
		GType xcls_clutterfiles_xcls_image_type_id;
		xcls_clutterfiles_xcls_image_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_ClutterFilesXcls_image", &g_define_type_info, 0);
		g_once_init_leave (&xcls_clutterfiles_xcls_image_type_id__volatile, xcls_clutterfiles_xcls_image_type_id);
	}
	return xcls_clutterfiles_xcls_image_type_id__volatile;
}


Xcls_ClutterFilesXcls_title* xcls_clutterfiles_xcls_title_construct (GType object_type, Xcls_ClutterFiles* _owner, JsRenderJsRender* file) {
	Xcls_ClutterFilesXcls_title * self = NULL;
	Xcls_ClutterFiles* _tmp0_ = NULL;
	Xcls_ClutterFiles* _tmp1_ = NULL;
	JsRenderJsRender* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	ClutterColor _tmp5_ = {0};
	ClutterText* _tmp6_ = NULL;
	ClutterText* _tmp7_ = NULL;
	ClutterText* _tmp8_ = NULL;
	ClutterText* _tmp9_ = NULL;
	ClutterText* _tmp10_ = NULL;
#line 247 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 247 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (file != NULL, NULL);
#line 247 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = (Xcls_ClutterFilesXcls_title*) g_object_new (object_type, NULL);
#line 249 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = _owner;
#line 249 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 249 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 249 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv->_this = _tmp1_;
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = file;
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = js_render_js_render_nickName (_tmp2_);
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = _tmp3_;
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_color_from_string (&_tmp5_, "#fff");
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp6_ = (ClutterText*) clutter_text_new_full ("Sans 10px", _tmp4_, &_tmp5_);
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp6_);
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->el = _tmp6_;
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_free0 (_tmp4_);
#line 255 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp7_ = self->el;
#line 255 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_x_align ((ClutterActor*) _tmp7_, CLUTTER_ACTOR_ALIGN_START);
#line 256 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp8_ = self->el;
#line 256 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_x_expand ((ClutterActor*) _tmp8_, TRUE);
#line 257 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp9_ = self->el;
#line 257 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_y_align ((ClutterActor*) _tmp9_, CLUTTER_ACTOR_ALIGN_START);
#line 258 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp10_ = self->el;
#line 258 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_y_expand ((ClutterActor*) _tmp10_, FALSE);
#line 247 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return self;
#line 1450 "ClutterFiles.vala.c"
}


Xcls_ClutterFilesXcls_title* xcls_clutterfiles_xcls_title_new (Xcls_ClutterFiles* _owner, JsRenderJsRender* file) {
#line 247 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return xcls_clutterfiles_xcls_title_construct (XCLS_CLUTTERFILES_TYPE_XCLS_TITLE, _owner, file);
#line 1457 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_title_class_init (Xcls_ClutterFilesXcls_titleClass * klass) {
#line 238 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	xcls_clutterfiles_xcls_title_parent_class = g_type_class_peek_parent (klass);
#line 238 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_type_class_add_private (klass, sizeof (Xcls_ClutterFilesXcls_titlePrivate));
#line 238 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_clutterfiles_xcls_title_finalize;
#line 1468 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_title_instance_init (Xcls_ClutterFilesXcls_title * self) {
#line 238 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv = XCLS_CLUTTERFILES_XCLS_TITLE_GET_PRIVATE (self);
#line 1475 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_title_finalize (GObject* obj) {
	Xcls_ClutterFilesXcls_title * self;
#line 238 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_CLUTTERFILES_TYPE_XCLS_TITLE, Xcls_ClutterFilesXcls_title);
#line 240 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 241 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 238 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (xcls_clutterfiles_xcls_title_parent_class)->finalize (obj);
#line 1489 "ClutterFiles.vala.c"
}


GType xcls_clutterfiles_xcls_title_get_type (void) {
	static volatile gsize xcls_clutterfiles_xcls_title_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_clutterfiles_xcls_title_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_ClutterFilesXcls_titleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_clutterfiles_xcls_title_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_ClutterFilesXcls_title), 0, (GInstanceInitFunc) xcls_clutterfiles_xcls_title_instance_init, NULL };
		GType xcls_clutterfiles_xcls_title_type_id;
		xcls_clutterfiles_xcls_title_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_ClutterFilesXcls_title", &g_define_type_info, 0);
		g_once_init_leave (&xcls_clutterfiles_xcls_title_type_id__volatile, xcls_clutterfiles_xcls_title_type_id);
	}
	return xcls_clutterfiles_xcls_title_type_id__volatile;
}


static void xcls_clutterfiles_class_init (Xcls_ClutterFilesClass * klass) {
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	xcls_clutterfiles_parent_class = g_type_class_peek_parent (klass);
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_type_class_add_private (klass, sizeof (Xcls_ClutterFilesPrivate));
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_clutterfiles_finalize;
#line 1512 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_instance_init (Xcls_ClutterFiles * self) {
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv = XCLS_CLUTTERFILES_GET_PRIVATE (self);
#line 1519 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_finalize (GObject* obj) {
	Xcls_ClutterFiles * self;
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_XCLS_CLUTTERFILES, Xcls_ClutterFiles);
#line 22 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 23 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 25 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->filelayout);
#line 26 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->filelayout_manager);
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (xcls_clutterfiles_parent_class)->finalize (obj);
#line 1537 "ClutterFiles.vala.c"
}


GType xcls_clutterfiles_get_type (void) {
	static volatile gsize xcls_clutterfiles_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_clutterfiles_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_ClutterFilesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_clutterfiles_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_ClutterFiles), 0, (GInstanceInitFunc) xcls_clutterfiles_instance_init, NULL };
		GType xcls_clutterfiles_type_id;
		xcls_clutterfiles_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_ClutterFiles", &g_define_type_info, 0);
		g_once_init_leave (&xcls_clutterfiles_type_id__volatile, xcls_clutterfiles_type_id);
	}
	return xcls_clutterfiles_type_id__volatile;
}



