/* ClutterFiles.vala.c generated by valac 0.24.0, the Vala compiler
 * generated from ClutterFiles.vala, do not modify */

/* -- to compile
valac  --pkg gio-2.0  --pkg posix  --pkg gtk+-3.0 --pkg libnotify --pkg gtksourceview-3.0  --pkg  libwnck-3.0 \
    /tmp/ClutterFiles.vala  -o /tmp/ClutterFiles
*/
/* -- to test class
static int main (string[] args) {
    Gtk.init (ref args);
    new Xcls_ClutterFiles();
    ClutterFiles.show_all();
     Gtk.main ();
    return 0;
}
*/

#include <glib.h>
#include <glib-object.h>
#include <clutter/clutter.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define TYPE_XCLS_CLUTTERFILES (xcls_clutterfiles_get_type ())
#define XCLS_CLUTTERFILES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_XCLS_CLUTTERFILES, Xcls_ClutterFiles))
#define XCLS_CLUTTERFILES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_XCLS_CLUTTERFILES, Xcls_ClutterFilesClass))
#define IS_XCLS_CLUTTERFILES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_XCLS_CLUTTERFILES))
#define IS_XCLS_CLUTTERFILES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_XCLS_CLUTTERFILES))
#define XCLS_CLUTTERFILES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_XCLS_CLUTTERFILES, Xcls_ClutterFilesClass))

typedef struct _Xcls_ClutterFiles Xcls_ClutterFiles;
typedef struct _Xcls_ClutterFilesClass Xcls_ClutterFilesClass;
typedef struct _Xcls_ClutterFilesPrivate Xcls_ClutterFilesPrivate;

#define XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT (xcls_clutterfiles_xcls_filelayout_get_type ())
#define XCLS_CLUTTERFILES_XCLS_FILELAYOUT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT, Xcls_ClutterFilesXcls_filelayout))
#define XCLS_CLUTTERFILES_XCLS_FILELAYOUT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT, Xcls_ClutterFilesXcls_filelayoutClass))
#define XCLS_CLUTTERFILES_IS_XCLS_FILELAYOUT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT))
#define XCLS_CLUTTERFILES_IS_XCLS_FILELAYOUT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT))
#define XCLS_CLUTTERFILES_XCLS_FILELAYOUT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT, Xcls_ClutterFilesXcls_filelayoutClass))

typedef struct _Xcls_ClutterFilesXcls_filelayout Xcls_ClutterFilesXcls_filelayout;
typedef struct _Xcls_ClutterFilesXcls_filelayoutClass Xcls_ClutterFilesXcls_filelayoutClass;

#define XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT_MANAGER (xcls_clutterfiles_xcls_filelayout_manager_get_type ())
#define XCLS_CLUTTERFILES_XCLS_FILELAYOUT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT_MANAGER, Xcls_ClutterFilesXcls_filelayout_manager))
#define XCLS_CLUTTERFILES_XCLS_FILELAYOUT_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT_MANAGER, Xcls_ClutterFilesXcls_filelayout_managerClass))
#define XCLS_CLUTTERFILES_IS_XCLS_FILELAYOUT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT_MANAGER))
#define XCLS_CLUTTERFILES_IS_XCLS_FILELAYOUT_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT_MANAGER))
#define XCLS_CLUTTERFILES_XCLS_FILELAYOUT_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT_MANAGER, Xcls_ClutterFilesXcls_filelayout_managerClass))

typedef struct _Xcls_ClutterFilesXcls_filelayout_manager Xcls_ClutterFilesXcls_filelayout_manager;
typedef struct _Xcls_ClutterFilesXcls_filelayout_managerClass Xcls_ClutterFilesXcls_filelayout_managerClass;

#define XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM (xcls_clutterfiles_xcls_fileitem_get_type ())
#define XCLS_CLUTTERFILES_XCLS_FILEITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM, Xcls_ClutterFilesXcls_fileitem))
#define XCLS_CLUTTERFILES_XCLS_FILEITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM, Xcls_ClutterFilesXcls_fileitemClass))
#define XCLS_CLUTTERFILES_IS_XCLS_FILEITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM))
#define XCLS_CLUTTERFILES_IS_XCLS_FILEITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM))
#define XCLS_CLUTTERFILES_XCLS_FILEITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM, Xcls_ClutterFilesXcls_fileitemClass))

typedef struct _Xcls_ClutterFilesXcls_fileitem Xcls_ClutterFilesXcls_fileitem;
typedef struct _Xcls_ClutterFilesXcls_fileitemClass Xcls_ClutterFilesXcls_fileitemClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Xcls_ClutterFilesXcls_filelayoutPrivate Xcls_ClutterFilesXcls_filelayoutPrivate;

#define PROJECT_TYPE_PROJECT (project_project_get_type ())
#define PROJECT_PROJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROJECT_TYPE_PROJECT, ProjectProject))
#define PROJECT_PROJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROJECT_TYPE_PROJECT, ProjectProjectClass))
#define PROJECT_IS_PROJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROJECT_TYPE_PROJECT))
#define PROJECT_IS_PROJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROJECT_TYPE_PROJECT))
#define PROJECT_PROJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROJECT_TYPE_PROJECT, ProjectProjectClass))

typedef struct _ProjectProject ProjectProject;
typedef struct _ProjectProjectClass ProjectProjectClass;
typedef struct _ProjectProjectPrivate ProjectProjectPrivate;

#define JS_RENDER_TYPE_JS_RENDER (js_render_js_render_get_type ())
#define JS_RENDER_JS_RENDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JS_RENDER_TYPE_JS_RENDER, JsRenderJsRender))
#define JS_RENDER_JS_RENDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JS_RENDER_TYPE_JS_RENDER, JsRenderJsRenderClass))
#define JS_RENDER_IS_JS_RENDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JS_RENDER_TYPE_JS_RENDER))
#define JS_RENDER_IS_JS_RENDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JS_RENDER_TYPE_JS_RENDER))
#define JS_RENDER_JS_RENDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JS_RENDER_TYPE_JS_RENDER, JsRenderJsRenderClass))

typedef struct _JsRenderJsRender JsRenderJsRender;
typedef struct _JsRenderJsRenderClass JsRenderJsRenderClass;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _JsRenderJsRenderPrivate JsRenderJsRenderPrivate;

#define JS_RENDER_TYPE_NODE (js_render_node_get_type ())
#define JS_RENDER_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JS_RENDER_TYPE_NODE, JsRenderNode))
#define JS_RENDER_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JS_RENDER_TYPE_NODE, JsRenderNodeClass))
#define JS_RENDER_IS_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JS_RENDER_TYPE_NODE))
#define JS_RENDER_IS_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JS_RENDER_TYPE_NODE))
#define JS_RENDER_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JS_RENDER_TYPE_NODE, JsRenderNodeClass))

typedef struct _JsRenderNode JsRenderNode;
typedef struct _JsRenderNodeClass JsRenderNodeClass;
typedef struct _Xcls_ClutterFilesXcls_fileitemPrivate Xcls_ClutterFilesXcls_fileitemPrivate;

#define XCLS_CLUTTERFILES_TYPE_XCLS_IMAGE (xcls_clutterfiles_xcls_image_get_type ())
#define XCLS_CLUTTERFILES_XCLS_IMAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_IMAGE, Xcls_ClutterFilesXcls_image))
#define XCLS_CLUTTERFILES_XCLS_IMAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_IMAGE, Xcls_ClutterFilesXcls_imageClass))
#define XCLS_CLUTTERFILES_IS_XCLS_IMAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_IMAGE))
#define XCLS_CLUTTERFILES_IS_XCLS_IMAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_IMAGE))
#define XCLS_CLUTTERFILES_XCLS_IMAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_IMAGE, Xcls_ClutterFilesXcls_imageClass))

typedef struct _Xcls_ClutterFilesXcls_image Xcls_ClutterFilesXcls_image;
typedef struct _Xcls_ClutterFilesXcls_imageClass Xcls_ClutterFilesXcls_imageClass;

#define XCLS_CLUTTERFILES_TYPE_XCLS_TYPETITLE (xcls_clutterfiles_xcls_typetitle_get_type ())
#define XCLS_CLUTTERFILES_XCLS_TYPETITLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_TYPETITLE, Xcls_ClutterFilesXcls_typetitle))
#define XCLS_CLUTTERFILES_XCLS_TYPETITLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_TYPETITLE, Xcls_ClutterFilesXcls_typetitleClass))
#define XCLS_CLUTTERFILES_IS_XCLS_TYPETITLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_TYPETITLE))
#define XCLS_CLUTTERFILES_IS_XCLS_TYPETITLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_TYPETITLE))
#define XCLS_CLUTTERFILES_XCLS_TYPETITLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_TYPETITLE, Xcls_ClutterFilesXcls_typetitleClass))

typedef struct _Xcls_ClutterFilesXcls_typetitle Xcls_ClutterFilesXcls_typetitle;
typedef struct _Xcls_ClutterFilesXcls_typetitleClass Xcls_ClutterFilesXcls_typetitleClass;

#define XCLS_CLUTTERFILES_TYPE_XCLS_TITLE (xcls_clutterfiles_xcls_title_get_type ())
#define XCLS_CLUTTERFILES_XCLS_TITLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_TITLE, Xcls_ClutterFilesXcls_title))
#define XCLS_CLUTTERFILES_XCLS_TITLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_TITLE, Xcls_ClutterFilesXcls_titleClass))
#define XCLS_CLUTTERFILES_IS_XCLS_TITLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_TITLE))
#define XCLS_CLUTTERFILES_IS_XCLS_TITLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_TITLE))
#define XCLS_CLUTTERFILES_XCLS_TITLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_TITLE, Xcls_ClutterFilesXcls_titleClass))

typedef struct _Xcls_ClutterFilesXcls_title Xcls_ClutterFilesXcls_title;
typedef struct _Xcls_ClutterFilesXcls_titleClass Xcls_ClutterFilesXcls_titleClass;
typedef struct _Xcls_ClutterFilesXcls_filelayout_managerPrivate Xcls_ClutterFilesXcls_filelayout_managerPrivate;

#define XCLS_CLUTTERFILES_TYPE_XCLS_BOXLAYOUT5 (xcls_clutterfiles_xcls_boxlayout5_get_type ())
#define XCLS_CLUTTERFILES_XCLS_BOXLAYOUT5(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_BOXLAYOUT5, Xcls_ClutterFilesXcls_BoxLayout5))
#define XCLS_CLUTTERFILES_XCLS_BOXLAYOUT5_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_BOXLAYOUT5, Xcls_ClutterFilesXcls_BoxLayout5Class))
#define XCLS_CLUTTERFILES_IS_XCLS_BOXLAYOUT5(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_BOXLAYOUT5))
#define XCLS_CLUTTERFILES_IS_XCLS_BOXLAYOUT5_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_CLUTTERFILES_TYPE_XCLS_BOXLAYOUT5))
#define XCLS_CLUTTERFILES_XCLS_BOXLAYOUT5_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_CLUTTERFILES_TYPE_XCLS_BOXLAYOUT5, Xcls_ClutterFilesXcls_BoxLayout5Class))

typedef struct _Xcls_ClutterFilesXcls_BoxLayout5 Xcls_ClutterFilesXcls_BoxLayout5;
typedef struct _Xcls_ClutterFilesXcls_BoxLayout5Class Xcls_ClutterFilesXcls_BoxLayout5Class;
typedef struct _Xcls_ClutterFilesXcls_BoxLayout5Private Xcls_ClutterFilesXcls_BoxLayout5Private;
typedef struct _Xcls_ClutterFilesXcls_imagePrivate Xcls_ClutterFilesXcls_imagePrivate;
typedef struct _Xcls_ClutterFilesXcls_typetitlePrivate Xcls_ClutterFilesXcls_typetitlePrivate;
typedef struct _Xcls_ClutterFilesXcls_titlePrivate Xcls_ClutterFilesXcls_titlePrivate;

struct _Xcls_ClutterFiles {
	GObject parent_instance;
	Xcls_ClutterFilesPrivate * priv;
	ClutterScrollActor* el;
	Xcls_ClutterFilesXcls_filelayout* filelayout;
	Xcls_ClutterFilesXcls_filelayout_manager* filelayout_manager;
	GeeArrayList* fileitems;
};

struct _Xcls_ClutterFilesClass {
	GObjectClass parent_class;
};

struct _Xcls_ClutterFilesPrivate {
	Xcls_ClutterFiles* _this;
};

struct _Xcls_ClutterFilesXcls_filelayout {
	GObject parent_instance;
	Xcls_ClutterFilesXcls_filelayoutPrivate * priv;
	ClutterActor* el;
};

struct _Xcls_ClutterFilesXcls_filelayoutClass {
	GObjectClass parent_class;
};

struct _ProjectProject {
	GObject parent_instance;
	ProjectProjectPrivate * priv;
	gchar* id;
	gchar* fn;
	gchar* name;
	gchar* runhtml;
	GeeHashMap* paths;
	GeeHashMap* files;
	gchar* xtype;
};

struct _ProjectProjectClass {
	GObjectClass parent_class;
};

struct _JsRenderJsRender {
	GObject parent_instance;
	JsRenderJsRenderPrivate * priv;
	GeeArrayList* doubleStringProps;
	gchar* id;
	gchar* name;
	gchar* fullname;
	gchar* path;
	gchar* parent;
	gchar* region;
	gchar* title;
	gchar* permname;
	gchar* modOrder;
	gchar* xtype;
	ProjectProject* project;
	JsRenderNode* tree;
	GList* cn;
	gboolean hasParent;
};

struct _JsRenderJsRenderClass {
	GObjectClass parent_class;
	void (*save) (JsRenderJsRender* self);
	void (*loadItems) (JsRenderJsRender* self, GError** error);
	gchar* (*toSource) (JsRenderJsRender* self);
	gchar* (*toSourcePreview) (JsRenderJsRender* self);
	gchar* (*toValaSource) (JsRenderJsRender* self, gboolean testcompile);
};

struct _Xcls_ClutterFilesXcls_fileitem {
	GObject parent_instance;
	Xcls_ClutterFilesXcls_fileitemPrivate * priv;
	ClutterActor* el;
	JsRenderJsRender* file;
	Xcls_ClutterFilesXcls_image* image;
	Xcls_ClutterFilesXcls_typetitle* typetitle;
	Xcls_ClutterFilesXcls_title* title;
};

struct _Xcls_ClutterFilesXcls_fileitemClass {
	GObjectClass parent_class;
};

struct _Xcls_ClutterFilesXcls_filelayout_manager {
	GObject parent_instance;
	Xcls_ClutterFilesXcls_filelayout_managerPrivate * priv;
	ClutterFlowLayout* el;
};

struct _Xcls_ClutterFilesXcls_filelayout_managerClass {
	GObjectClass parent_class;
};

struct _Xcls_ClutterFilesXcls_filelayoutPrivate {
	Xcls_ClutterFiles* _this;
};

struct _Xcls_ClutterFilesXcls_filelayout_managerPrivate {
	Xcls_ClutterFiles* _this;
};

struct _Xcls_ClutterFilesXcls_fileitemPrivate {
	Xcls_ClutterFiles* _this;
};

struct _Xcls_ClutterFilesXcls_BoxLayout5 {
	GObject parent_instance;
	Xcls_ClutterFilesXcls_BoxLayout5Private * priv;
	ClutterBoxLayout* el;
};

struct _Xcls_ClutterFilesXcls_BoxLayout5Class {
	GObjectClass parent_class;
};

struct _Xcls_ClutterFilesXcls_image {
	GObject parent_instance;
	Xcls_ClutterFilesXcls_imagePrivate * priv;
	ClutterTexture* el;
};

struct _Xcls_ClutterFilesXcls_imageClass {
	GObjectClass parent_class;
};

struct _Xcls_ClutterFilesXcls_typetitle {
	GObject parent_instance;
	Xcls_ClutterFilesXcls_typetitlePrivate * priv;
	ClutterText* el;
};

struct _Xcls_ClutterFilesXcls_typetitleClass {
	GObjectClass parent_class;
};

struct _Xcls_ClutterFilesXcls_title {
	GObject parent_instance;
	Xcls_ClutterFilesXcls_titlePrivate * priv;
	ClutterText* el;
};

struct _Xcls_ClutterFilesXcls_titleClass {
	GObjectClass parent_class;
};

struct _Xcls_ClutterFilesXcls_BoxLayout5Private {
	Xcls_ClutterFiles* _this;
};

struct _Xcls_ClutterFilesXcls_imagePrivate {
	Xcls_ClutterFiles* _this;
};

struct _Xcls_ClutterFilesXcls_typetitlePrivate {
	Xcls_ClutterFiles* _this;
};

struct _Xcls_ClutterFilesXcls_titlePrivate {
	Xcls_ClutterFiles* _this;
};


extern Xcls_ClutterFiles* ClutterFiles;
Xcls_ClutterFiles* ClutterFiles = NULL;
static gpointer xcls_clutterfiles_parent_class = NULL;
static gpointer xcls_clutterfiles_xcls_filelayout_parent_class = NULL;
static gpointer xcls_clutterfiles_xcls_filelayout_manager_parent_class = NULL;
static gpointer xcls_clutterfiles_xcls_fileitem_parent_class = NULL;
static gpointer xcls_clutterfiles_xcls_boxlayout5_parent_class = NULL;
static gpointer xcls_clutterfiles_xcls_image_parent_class = NULL;
static gpointer xcls_clutterfiles_xcls_typetitle_parent_class = NULL;
static gpointer xcls_clutterfiles_xcls_title_parent_class = NULL;

GType xcls_clutterfiles_get_type (void) G_GNUC_CONST;
GType xcls_clutterfiles_xcls_filelayout_get_type (void) G_GNUC_CONST;
GType xcls_clutterfiles_xcls_filelayout_manager_get_type (void) G_GNUC_CONST;
GType xcls_clutterfiles_xcls_fileitem_get_type (void) G_GNUC_CONST;
#define XCLS_CLUTTERFILES_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_XCLS_CLUTTERFILES, Xcls_ClutterFilesPrivate))
enum  {
	XCLS_CLUTTERFILES_DUMMY_PROPERTY
};
Xcls_ClutterFiles* xcls_clutterfiles_new (void);
Xcls_ClutterFiles* xcls_clutterfiles_construct (GType object_type);
Xcls_ClutterFilesXcls_filelayout* xcls_clutterfiles_xcls_filelayout_new (Xcls_ClutterFiles* _owner);
Xcls_ClutterFilesXcls_filelayout* xcls_clutterfiles_xcls_filelayout_construct (GType object_type, Xcls_ClutterFiles* _owner);
void xcls_clutterfiles_clearFiles (Xcls_ClutterFiles* self);
GType project_project_get_type (void) G_GNUC_CONST;
void xcls_clutterfiles_loadProject (Xcls_ClutterFiles* self, ProjectProject* pr);
GType js_render_js_render_get_type (void) G_GNUC_CONST;
Xcls_ClutterFilesXcls_fileitem* xcls_clutterfiles_xcls_fileitem_new (Xcls_ClutterFiles* _owner, JsRenderJsRender* file);
Xcls_ClutterFilesXcls_fileitem* xcls_clutterfiles_xcls_fileitem_construct (GType object_type, Xcls_ClutterFiles* _owner, JsRenderJsRender* file);
GType js_render_node_get_type (void) G_GNUC_CONST;
GType xcls_clutterfiles_xcls_image_get_type (void) G_GNUC_CONST;
GType xcls_clutterfiles_xcls_typetitle_get_type (void) G_GNUC_CONST;
GType xcls_clutterfiles_xcls_title_get_type (void) G_GNUC_CONST;
void xcls_clutterfiles_set_size (Xcls_ClutterFiles* self, gfloat w, gfloat h);
#define XCLS_CLUTTERFILES_XCLS_FILELAYOUT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT, Xcls_ClutterFilesXcls_filelayoutPrivate))
enum  {
	XCLS_CLUTTERFILES_XCLS_FILELAYOUT_DUMMY_PROPERTY
};
Xcls_ClutterFilesXcls_filelayout_manager* xcls_clutterfiles_xcls_filelayout_manager_new (Xcls_ClutterFiles* _owner);
Xcls_ClutterFilesXcls_filelayout_manager* xcls_clutterfiles_xcls_filelayout_manager_construct (GType object_type, Xcls_ClutterFiles* _owner);
static void xcls_clutterfiles_xcls_filelayout_finalize (GObject* obj);
#define XCLS_CLUTTERFILES_XCLS_FILELAYOUT_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT_MANAGER, Xcls_ClutterFilesXcls_filelayout_managerPrivate))
enum  {
	XCLS_CLUTTERFILES_XCLS_FILELAYOUT_MANAGER_DUMMY_PROPERTY
};
static void xcls_clutterfiles_xcls_filelayout_manager_finalize (GObject* obj);
#define XCLS_CLUTTERFILES_XCLS_FILEITEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM, Xcls_ClutterFilesXcls_fileitemPrivate))
enum  {
	XCLS_CLUTTERFILES_XCLS_FILEITEM_DUMMY_PROPERTY
};
GType xcls_clutterfiles_xcls_boxlayout5_get_type (void) G_GNUC_CONST;
Xcls_ClutterFilesXcls_BoxLayout5* xcls_clutterfiles_xcls_boxlayout5_new (Xcls_ClutterFiles* _owner);
Xcls_ClutterFilesXcls_BoxLayout5* xcls_clutterfiles_xcls_boxlayout5_construct (GType object_type, Xcls_ClutterFiles* _owner);
Xcls_ClutterFilesXcls_image* xcls_clutterfiles_xcls_image_new (Xcls_ClutterFiles* _owner, JsRenderJsRender* file);
Xcls_ClutterFilesXcls_image* xcls_clutterfiles_xcls_image_construct (GType object_type, Xcls_ClutterFiles* _owner, JsRenderJsRender* file);
Xcls_ClutterFilesXcls_typetitle* xcls_clutterfiles_xcls_typetitle_new (Xcls_ClutterFiles* _owner, JsRenderJsRender* file);
Xcls_ClutterFilesXcls_typetitle* xcls_clutterfiles_xcls_typetitle_construct (GType object_type, Xcls_ClutterFiles* _owner, JsRenderJsRender* file);
Xcls_ClutterFilesXcls_title* xcls_clutterfiles_xcls_title_new (Xcls_ClutterFiles* _owner, JsRenderJsRender* file);
Xcls_ClutterFilesXcls_title* xcls_clutterfiles_xcls_title_construct (GType object_type, Xcls_ClutterFiles* _owner, JsRenderJsRender* file);
static gboolean __lambda49_ (Xcls_ClutterFilesXcls_fileitem* self, ClutterCrossingEvent* event);
static gboolean ___lambda49__clutter_actor_enter_event (ClutterActor* _sender, ClutterCrossingEvent* event, gpointer self);
static gboolean __lambda50_ (Xcls_ClutterFilesXcls_fileitem* self, ClutterCrossingEvent* event);
static gboolean ___lambda50__clutter_actor_leave_event (ClutterActor* _sender, ClutterCrossingEvent* event, gpointer self);
static gboolean __lambda51_ (Xcls_ClutterFilesXcls_fileitem* self, ClutterButtonEvent* event);
static gboolean ___lambda51__clutter_actor_button_press_event (ClutterActor* _sender, ClutterButtonEvent* event, gpointer self);
static void xcls_clutterfiles_xcls_fileitem_finalize (GObject* obj);
#define XCLS_CLUTTERFILES_XCLS_BOXLAYOUT5_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_CLUTTERFILES_TYPE_XCLS_BOXLAYOUT5, Xcls_ClutterFilesXcls_BoxLayout5Private))
enum  {
	XCLS_CLUTTERFILES_XCLS_BOXLAYOUT5_DUMMY_PROPERTY
};
static void xcls_clutterfiles_xcls_boxlayout5_finalize (GObject* obj);
#define XCLS_CLUTTERFILES_XCLS_IMAGE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_CLUTTERFILES_TYPE_XCLS_IMAGE, Xcls_ClutterFilesXcls_imagePrivate))
enum  {
	XCLS_CLUTTERFILES_XCLS_IMAGE_DUMMY_PROPERTY
};
gchar* js_render_js_render_getIconFileName (JsRenderJsRender* self, gboolean return_default);
static void xcls_clutterfiles_xcls_image_finalize (GObject* obj);
#define XCLS_CLUTTERFILES_XCLS_TYPETITLE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_CLUTTERFILES_TYPE_XCLS_TYPETITLE, Xcls_ClutterFilesXcls_typetitlePrivate))
enum  {
	XCLS_CLUTTERFILES_XCLS_TYPETITLE_DUMMY_PROPERTY
};
gchar* js_render_js_render_nickType (JsRenderJsRender* self);
static void xcls_clutterfiles_xcls_typetitle_finalize (GObject* obj);
#define XCLS_CLUTTERFILES_XCLS_TITLE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_CLUTTERFILES_TYPE_XCLS_TITLE, Xcls_ClutterFilesXcls_titlePrivate))
enum  {
	XCLS_CLUTTERFILES_XCLS_TITLE_DUMMY_PROPERTY
};
gchar* js_render_js_render_nickName (JsRenderJsRender* self);
static void xcls_clutterfiles_xcls_title_finalize (GObject* obj);
static void xcls_clutterfiles_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
#line 35 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return self ? g_object_ref (self) : NULL;
#line 411 "ClutterFiles.vala.c"
}


Xcls_ClutterFiles* xcls_clutterfiles_construct (GType object_type) {
	Xcls_ClutterFiles * self = NULL;
	Xcls_ClutterFiles* _tmp0_ = NULL;
	Xcls_ClutterFiles* _tmp1_ = NULL;
	ClutterScrollActor* _tmp2_ = NULL;
	ClutterScrollActor* _tmp3_ = NULL;
	Xcls_ClutterFilesXcls_filelayout* child_0 = NULL;
	Xcls_ClutterFiles* _tmp4_ = NULL;
	Xcls_ClutterFilesXcls_filelayout* _tmp5_ = NULL;
	ClutterScrollActor* _tmp6_ = NULL;
	ClutterActor* _tmp7_ = NULL;
	GeeArrayList* _tmp8_ = NULL;
#line 33 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = (Xcls_ClutterFiles*) g_object_new (object_type, NULL);
#line 35 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 35 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 35 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv->_this = _tmp0_;
#line 36 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _g_object_ref0 (self);
#line 36 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (ClutterFiles);
#line 36 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	ClutterFiles = _tmp1_;
#line 37 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = (ClutterScrollActor*) clutter_scroll_actor_new ();
#line 37 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp2_);
#line 37 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 37 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->el = _tmp2_;
#line 42 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = self->el;
#line 42 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_reactive ((ClutterActor*) _tmp3_, TRUE);
#line 43 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = self->priv->_this;
#line 43 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp5_ = xcls_clutterfiles_xcls_filelayout_new (_tmp4_);
#line 43 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	child_0 = _tmp5_;
#line 44 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref ((GObject*) child_0);
#line 45 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp6_ = self->el;
#line 45 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp7_ = child_0->el;
#line 45 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_add_child ((ClutterActor*) _tmp6_, _tmp7_);
#line 48 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp8_ = gee_array_list_new (XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
#line 48 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->fileitems);
#line 48 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->fileitems = _tmp8_;
#line 33 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (child_0);
#line 33 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return self;
#line 477 "ClutterFiles.vala.c"
}


Xcls_ClutterFiles* xcls_clutterfiles_new (void) {
#line 33 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return xcls_clutterfiles_construct (TYPE_XCLS_CLUTTERFILES);
#line 484 "ClutterFiles.vala.c"
}


void xcls_clutterfiles_clearFiles (Xcls_ClutterFiles* self) {
	Xcls_ClutterFilesXcls_filelayout* _tmp0_ = NULL;
	ClutterActor* _tmp1_ = NULL;
#line 52 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_if_fail (self != NULL);
#line 54 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = self->filelayout;
#line 54 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _tmp0_->el;
#line 54 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_remove_all_children (_tmp1_);
#line 499 "ClutterFiles.vala.c"
}


void xcls_clutterfiles_loadProject (Xcls_ClutterFiles* self, ProjectProject* pr) {
	ProjectProject* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	GeeArrayList* _tmp6_ = NULL;
	GeeMapIterator* fiter = NULL;
	ProjectProject* _tmp7_ = NULL;
	GeeHashMap* _tmp8_ = NULL;
	GeeMapIterator* _tmp9_ = NULL;
	ClutterScrollActor* _tmp31_ = NULL;
#line 58 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_if_fail (self != NULL);
#line 58 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_if_fail (pr != NULL);
#line 62 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	xcls_clutterfiles_clearFiles (self);
#line 64 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = pr;
#line 64 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _tmp0_->name;
#line 64 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = g_strconcat ("clutter files - load project: ", _tmp1_, NULL);
#line 64 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = _tmp2_;
#line 64 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = g_strconcat (_tmp3_, "\n", NULL);
#line 64 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp5_ = _tmp4_;
#line 64 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_print ("%s", _tmp5_);
#line 64 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_free0 (_tmp5_);
#line 64 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_free0 (_tmp3_);
#line 66 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp6_ = gee_array_list_new (XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
#line 66 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->fileitems);
#line 66 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->fileitems = _tmp6_;
#line 68 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp7_ = pr;
#line 68 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp8_ = _tmp7_->files;
#line 68 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp9_ = gee_abstract_map_map_iterator ((GeeAbstractMap*) _tmp8_);
#line 68 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	fiter = _tmp9_;
#line 69 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	while (TRUE) {
#line 556 "ClutterFiles.vala.c"
		GeeMapIterator* _tmp10_ = NULL;
		gboolean _tmp11_ = FALSE;
		Xcls_ClutterFilesXcls_fileitem* a = NULL;
		GeeMapIterator* _tmp12_ = NULL;
		gpointer _tmp13_ = NULL;
		JsRenderJsRender* _tmp14_ = NULL;
		Xcls_ClutterFilesXcls_fileitem* _tmp15_ = NULL;
		Xcls_ClutterFilesXcls_fileitem* _tmp16_ = NULL;
		GeeArrayList* _tmp17_ = NULL;
		Xcls_ClutterFilesXcls_fileitem* _tmp18_ = NULL;
		GeeMapIterator* _tmp19_ = NULL;
		gpointer _tmp20_ = NULL;
		JsRenderJsRender* _tmp21_ = NULL;
		const gchar* _tmp22_ = NULL;
		gchar* _tmp23_ = NULL;
		gchar* _tmp24_ = NULL;
		gchar* _tmp25_ = NULL;
		gchar* _tmp26_ = NULL;
		Xcls_ClutterFilesXcls_filelayout* _tmp27_ = NULL;
		ClutterActor* _tmp28_ = NULL;
		Xcls_ClutterFilesXcls_fileitem* _tmp29_ = NULL;
		ClutterActor* _tmp30_ = NULL;
#line 69 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp10_ = fiter;
#line 69 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp11_ = gee_map_iterator_next (_tmp10_);
#line 69 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		if (!_tmp11_) {
#line 69 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
			break;
#line 587 "ClutterFiles.vala.c"
		}
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp12_ = fiter;
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp13_ = gee_map_iterator_get_value (_tmp12_);
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp14_ = (JsRenderJsRender*) _tmp13_;
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp15_ = xcls_clutterfiles_xcls_fileitem_new (self, _tmp14_);
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp16_ = _tmp15_;
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_g_object_unref0 (_tmp14_);
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		a = _tmp16_;
#line 71 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp17_ = self->fileitems;
#line 71 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp18_ = a;
#line 71 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp17_, _tmp18_);
#line 74 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp19_ = fiter;
#line 74 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp20_ = gee_map_iterator_get_value (_tmp19_);
#line 74 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp21_ = (JsRenderJsRender*) _tmp20_;
#line 74 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp22_ = _tmp21_->name;
#line 74 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp23_ = g_strconcat ("add to clutter file view: ", _tmp22_, NULL);
#line 74 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp24_ = _tmp23_;
#line 74 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp25_ = g_strconcat (_tmp24_, "\n", NULL);
#line 74 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp26_ = _tmp25_;
#line 74 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		g_print ("%s", _tmp26_);
#line 74 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_g_free0 (_tmp26_);
#line 74 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_g_free0 (_tmp24_);
#line 74 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_g_object_unref0 (_tmp21_);
#line 75 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp27_ = self->filelayout;
#line 75 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp28_ = _tmp27_->el;
#line 75 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp29_ = a;
#line 75 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_tmp30_ = _tmp29_->el;
#line 75 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		clutter_actor_add_child (_tmp28_, _tmp30_);
#line 69 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		_g_object_unref0 (a);
#line 645 "ClutterFiles.vala.c"
	}
#line 77 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp31_ = self->el;
#line 77 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_show_all ((ClutterActor*) _tmp31_);
#line 58 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (fiter);
#line 653 "ClutterFiles.vala.c"
}


void xcls_clutterfiles_set_size (Xcls_ClutterFiles* self, gfloat w, gfloat h) {
	ClutterScrollActor* _tmp0_ = NULL;
	Xcls_ClutterFiles* _tmp1_ = NULL;
	Xcls_ClutterFilesXcls_filelayout_manager* _tmp2_ = NULL;
	ClutterFlowLayout* _tmp3_ = NULL;
	gfloat _tmp4_ = 0.0F;
	ClutterScrollActor* _tmp5_ = NULL;
	ClutterScrollActor* _tmp6_ = NULL;
	ClutterStage* _tmp7_ = NULL;
	gfloat _tmp8_ = 0.0F;
	gfloat _tmp9_ = 0.0F;
	ClutterScrollActor* _tmp10_ = NULL;
	ClutterStage* _tmp11_ = NULL;
	gfloat _tmp12_ = 0.0F;
	gfloat _tmp13_ = 0.0F;
	ClutterScrollActor* _tmp14_ = NULL;
#line 79 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_if_fail (self != NULL);
#line 81 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = self->el;
#line 81 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	if (_tmp0_ == NULL) {
#line 82 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		g_print ("object not ready yet?");
#line 83 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		return;
#line 683 "ClutterFiles.vala.c"
	}
#line 85 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = self->priv->_this;
#line 85 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = _tmp1_->filelayout_manager;
#line 85 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = _tmp2_->el;
#line 85 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = w;
#line 85 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_set (_tmp3_, "max-column-width", _tmp4_ - 150, NULL);
#line 86 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp5_ = self->el;
#line 86 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp6_ = self->el;
#line 86 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp7_ = clutter_actor_get_stage ((ClutterActor*) _tmp6_);
#line 86 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp8_ = clutter_actor_get_width ((ClutterActor*) _tmp7_);
#line 86 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp9_ = _tmp8_;
#line 86 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp10_ = self->el;
#line 86 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp11_ = clutter_actor_get_stage ((ClutterActor*) _tmp10_);
#line 86 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp12_ = clutter_actor_get_height ((ClutterActor*) _tmp11_);
#line 86 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp13_ = _tmp12_;
#line 86 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_size ((ClutterActor*) _tmp5_, _tmp9_ - 150, _tmp13_);
#line 88 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp14_ = self->el;
#line 88 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_position ((ClutterActor*) _tmp14_, (gfloat) 100, (gfloat) 50);
#line 719 "ClutterFiles.vala.c"
}


Xcls_ClutterFilesXcls_filelayout* xcls_clutterfiles_xcls_filelayout_construct (GType object_type, Xcls_ClutterFiles* _owner) {
	Xcls_ClutterFilesXcls_filelayout * self = NULL;
	Xcls_ClutterFiles* _tmp0_ = NULL;
	Xcls_ClutterFiles* _tmp1_ = NULL;
	Xcls_ClutterFiles* _tmp2_ = NULL;
	Xcls_ClutterFilesXcls_filelayout* _tmp3_ = NULL;
	ClutterActor* _tmp4_ = NULL;
	ClutterActor* _tmp5_ = NULL;
	Xcls_ClutterFilesXcls_filelayout_manager* child_0 = NULL;
	Xcls_ClutterFiles* _tmp6_ = NULL;
	Xcls_ClutterFilesXcls_filelayout_manager* _tmp7_ = NULL;
	ClutterActor* _tmp8_ = NULL;
	ClutterFlowLayout* _tmp9_ = NULL;
	ClutterActor* _tmp10_ = NULL;
	Xcls_ClutterFiles* _tmp11_ = NULL;
	ClutterScrollActor* _tmp12_ = NULL;
	ClutterBindConstraint* _tmp13_ = NULL;
	ClutterBindConstraint* _tmp14_ = NULL;
#line 101 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 101 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = (Xcls_ClutterFilesXcls_filelayout*) g_object_new (object_type, NULL);
#line 103 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = _owner;
#line 103 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 103 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 103 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv->_this = _tmp1_;
#line 104 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = self->priv->_this;
#line 104 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = _g_object_ref0 (self);
#line 104 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (_tmp2_->filelayout);
#line 104 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_->filelayout = _tmp3_;
#line 105 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = clutter_actor_new ();
#line 105 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp4_);
#line 105 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 105 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->el = _tmp4_;
#line 110 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp5_ = self->el;
#line 110 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_reactive (_tmp5_, TRUE);
#line 111 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp6_ = self->priv->_this;
#line 111 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp7_ = xcls_clutterfiles_xcls_filelayout_manager_new (_tmp6_);
#line 111 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	child_0 = _tmp7_;
#line 112 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref ((GObject*) child_0);
#line 113 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp8_ = self->el;
#line 113 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp9_ = child_0->el;
#line 113 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_layout_manager (_tmp8_, (ClutterLayoutManager*) _tmp9_);
#line 116 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp10_ = self->el;
#line 116 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp11_ = self->priv->_this;
#line 116 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp12_ = _tmp11_->el;
#line 116 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp13_ = (ClutterBindConstraint*) clutter_bind_constraint_new ((ClutterActor*) _tmp12_, CLUTTER_BIND_SIZE, 0.0f);
#line 116 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp13_);
#line 116 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp14_ = _tmp13_;
#line 116 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_add_constraint (_tmp10_, (ClutterConstraint*) _tmp14_);
#line 116 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (_tmp14_);
#line 101 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (child_0);
#line 101 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return self;
#line 807 "ClutterFiles.vala.c"
}


Xcls_ClutterFilesXcls_filelayout* xcls_clutterfiles_xcls_filelayout_new (Xcls_ClutterFiles* _owner) {
#line 101 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return xcls_clutterfiles_xcls_filelayout_construct (XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT, _owner);
#line 814 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_filelayout_class_init (Xcls_ClutterFilesXcls_filelayoutClass * klass) {
#line 92 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	xcls_clutterfiles_xcls_filelayout_parent_class = g_type_class_peek_parent (klass);
#line 92 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_type_class_add_private (klass, sizeof (Xcls_ClutterFilesXcls_filelayoutPrivate));
#line 92 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_clutterfiles_xcls_filelayout_finalize;
#line 825 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_filelayout_instance_init (Xcls_ClutterFilesXcls_filelayout * self) {
#line 92 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv = XCLS_CLUTTERFILES_XCLS_FILELAYOUT_GET_PRIVATE (self);
#line 832 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_filelayout_finalize (GObject* obj) {
	Xcls_ClutterFilesXcls_filelayout * self;
#line 92 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT, Xcls_ClutterFilesXcls_filelayout);
#line 94 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 95 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 92 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (xcls_clutterfiles_xcls_filelayout_parent_class)->finalize (obj);
#line 846 "ClutterFiles.vala.c"
}


GType xcls_clutterfiles_xcls_filelayout_get_type (void) {
	static volatile gsize xcls_clutterfiles_xcls_filelayout_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_clutterfiles_xcls_filelayout_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_ClutterFilesXcls_filelayoutClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_clutterfiles_xcls_filelayout_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_ClutterFilesXcls_filelayout), 0, (GInstanceInitFunc) xcls_clutterfiles_xcls_filelayout_instance_init, NULL };
		GType xcls_clutterfiles_xcls_filelayout_type_id;
		xcls_clutterfiles_xcls_filelayout_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_ClutterFilesXcls_filelayout", &g_define_type_info, 0);
		g_once_init_leave (&xcls_clutterfiles_xcls_filelayout_type_id__volatile, xcls_clutterfiles_xcls_filelayout_type_id);
	}
	return xcls_clutterfiles_xcls_filelayout_type_id__volatile;
}


Xcls_ClutterFilesXcls_filelayout_manager* xcls_clutterfiles_xcls_filelayout_manager_construct (GType object_type, Xcls_ClutterFiles* _owner) {
	Xcls_ClutterFilesXcls_filelayout_manager * self = NULL;
	Xcls_ClutterFiles* _tmp0_ = NULL;
	Xcls_ClutterFiles* _tmp1_ = NULL;
	Xcls_ClutterFiles* _tmp2_ = NULL;
	Xcls_ClutterFilesXcls_filelayout_manager* _tmp3_ = NULL;
	ClutterFlowLayout* _tmp4_ = NULL;
	ClutterFlowLayout* _tmp5_ = NULL;
	ClutterFlowLayout* _tmp6_ = NULL;
	ClutterFlowLayout* _tmp7_ = NULL;
#line 134 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 134 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = (Xcls_ClutterFilesXcls_filelayout_manager*) g_object_new (object_type, NULL);
#line 136 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = _owner;
#line 136 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 136 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 136 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv->_this = _tmp1_;
#line 137 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = self->priv->_this;
#line 137 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = _g_object_ref0 (self);
#line 137 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (_tmp2_->filelayout_manager);
#line 137 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_->filelayout_manager = _tmp3_;
#line 138 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = (ClutterFlowLayout*) clutter_flow_layout_new (CLUTTER_FLOW_HORIZONTAL);
#line 138 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp4_);
#line 138 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 138 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->el = _tmp4_;
#line 143 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp5_ = self->el;
#line 143 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_flow_layout_set_column_spacing (_tmp5_, (gfloat) 20);
#line 144 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp6_ = self->el;
#line 144 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_flow_layout_set_homogeneous (_tmp6_, TRUE);
#line 145 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp7_ = self->el;
#line 145 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_flow_layout_set_row_spacing (_tmp7_, (gfloat) 20);
#line 134 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return self;
#line 914 "ClutterFiles.vala.c"
}


Xcls_ClutterFilesXcls_filelayout_manager* xcls_clutterfiles_xcls_filelayout_manager_new (Xcls_ClutterFiles* _owner) {
#line 134 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return xcls_clutterfiles_xcls_filelayout_manager_construct (XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT_MANAGER, _owner);
#line 921 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_filelayout_manager_class_init (Xcls_ClutterFilesXcls_filelayout_managerClass * klass) {
#line 125 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	xcls_clutterfiles_xcls_filelayout_manager_parent_class = g_type_class_peek_parent (klass);
#line 125 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_type_class_add_private (klass, sizeof (Xcls_ClutterFilesXcls_filelayout_managerPrivate));
#line 125 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_clutterfiles_xcls_filelayout_manager_finalize;
#line 932 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_filelayout_manager_instance_init (Xcls_ClutterFilesXcls_filelayout_manager * self) {
#line 125 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv = XCLS_CLUTTERFILES_XCLS_FILELAYOUT_MANAGER_GET_PRIVATE (self);
#line 939 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_filelayout_manager_finalize (GObject* obj) {
	Xcls_ClutterFilesXcls_filelayout_manager * self;
#line 125 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_CLUTTERFILES_TYPE_XCLS_FILELAYOUT_MANAGER, Xcls_ClutterFilesXcls_filelayout_manager);
#line 127 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 128 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 125 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (xcls_clutterfiles_xcls_filelayout_manager_parent_class)->finalize (obj);
#line 953 "ClutterFiles.vala.c"
}


GType xcls_clutterfiles_xcls_filelayout_manager_get_type (void) {
	static volatile gsize xcls_clutterfiles_xcls_filelayout_manager_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_clutterfiles_xcls_filelayout_manager_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_ClutterFilesXcls_filelayout_managerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_clutterfiles_xcls_filelayout_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_ClutterFilesXcls_filelayout_manager), 0, (GInstanceInitFunc) xcls_clutterfiles_xcls_filelayout_manager_instance_init, NULL };
		GType xcls_clutterfiles_xcls_filelayout_manager_type_id;
		xcls_clutterfiles_xcls_filelayout_manager_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_ClutterFilesXcls_filelayout_manager", &g_define_type_info, 0);
		g_once_init_leave (&xcls_clutterfiles_xcls_filelayout_manager_type_id__volatile, xcls_clutterfiles_xcls_filelayout_manager_type_id);
	}
	return xcls_clutterfiles_xcls_filelayout_manager_type_id__volatile;
}


static gboolean __lambda49_ (Xcls_ClutterFilesXcls_fileitem* self, ClutterCrossingEvent* event) {
	gboolean result = FALSE;
	ClutterActor* _tmp0_ = NULL;
	ClutterColor _tmp1_ = {0};
#line 195 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 196 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = self->el;
#line 196 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_color_from_string (&_tmp1_, "#333");
#line 196 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_background_color (_tmp0_, &_tmp1_);
#line 197 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	result = FALSE;
#line 197 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return result;
#line 985 "ClutterFiles.vala.c"
}


static gboolean ___lambda49__clutter_actor_enter_event (ClutterActor* _sender, ClutterCrossingEvent* event, gpointer self) {
	gboolean result;
	result = __lambda49_ ((Xcls_ClutterFilesXcls_fileitem*) self, event);
#line 195 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return result;
#line 994 "ClutterFiles.vala.c"
}


static gboolean __lambda50_ (Xcls_ClutterFilesXcls_fileitem* self, ClutterCrossingEvent* event) {
	gboolean result = FALSE;
	ClutterActor* _tmp0_ = NULL;
	ClutterColor _tmp1_ = {0};
#line 199 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 200 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = self->el;
#line 200 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_color_from_string (&_tmp1_, "#000");
#line 200 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_background_color (_tmp0_, &_tmp1_);
#line 201 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	result = FALSE;
#line 201 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return result;
#line 1014 "ClutterFiles.vala.c"
}


static gboolean ___lambda50__clutter_actor_leave_event (ClutterActor* _sender, ClutterCrossingEvent* event, gpointer self) {
	gboolean result;
	result = __lambda50_ ((Xcls_ClutterFilesXcls_fileitem*) self, event);
#line 199 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return result;
#line 1023 "ClutterFiles.vala.c"
}


static gboolean __lambda51_ (Xcls_ClutterFilesXcls_fileitem* self, ClutterButtonEvent* event) {
	gboolean result = FALSE;
	Xcls_ClutterFiles* _tmp0_ = NULL;
	JsRenderJsRender* _tmp1_ = NULL;
#line 203 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 204 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = self->priv->_this;
#line 204 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = self->file;
#line 204 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_signal_emit_by_name (_tmp0_, "open", _tmp1_);
#line 205 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	result = FALSE;
#line 205 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return result;
#line 1043 "ClutterFiles.vala.c"
}


static gboolean ___lambda51__clutter_actor_button_press_event (ClutterActor* _sender, ClutterButtonEvent* event, gpointer self) {
	gboolean result;
	result = __lambda51_ ((Xcls_ClutterFilesXcls_fileitem*) self, event);
#line 203 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return result;
#line 1052 "ClutterFiles.vala.c"
}


Xcls_ClutterFilesXcls_fileitem* xcls_clutterfiles_xcls_fileitem_construct (GType object_type, Xcls_ClutterFiles* _owner, JsRenderJsRender* file) {
	Xcls_ClutterFilesXcls_fileitem * self = NULL;
	Xcls_ClutterFiles* _tmp0_ = NULL;
	Xcls_ClutterFiles* _tmp1_ = NULL;
	ClutterActor* _tmp2_ = NULL;
	ClutterActor* _tmp3_ = NULL;
	Xcls_ClutterFilesXcls_BoxLayout5* child_0 = NULL;
	Xcls_ClutterFiles* _tmp4_ = NULL;
	Xcls_ClutterFilesXcls_BoxLayout5* _tmp5_ = NULL;
	ClutterActor* _tmp6_ = NULL;
	ClutterBoxLayout* _tmp7_ = NULL;
	Xcls_ClutterFilesXcls_image* child_1 = NULL;
	Xcls_ClutterFiles* _tmp8_ = NULL;
	JsRenderJsRender* _tmp9_ = NULL;
	Xcls_ClutterFilesXcls_image* _tmp10_ = NULL;
	ClutterActor* _tmp11_ = NULL;
	ClutterTexture* _tmp12_ = NULL;
	Xcls_ClutterFilesXcls_image* _tmp13_ = NULL;
	Xcls_ClutterFilesXcls_typetitle* child_2 = NULL;
	Xcls_ClutterFiles* _tmp14_ = NULL;
	JsRenderJsRender* _tmp15_ = NULL;
	Xcls_ClutterFilesXcls_typetitle* _tmp16_ = NULL;
	ClutterActor* _tmp17_ = NULL;
	ClutterText* _tmp18_ = NULL;
	Xcls_ClutterFilesXcls_typetitle* _tmp19_ = NULL;
	Xcls_ClutterFilesXcls_title* child_3 = NULL;
	Xcls_ClutterFiles* _tmp20_ = NULL;
	JsRenderJsRender* _tmp21_ = NULL;
	Xcls_ClutterFilesXcls_title* _tmp22_ = NULL;
	ClutterActor* _tmp23_ = NULL;
	ClutterText* _tmp24_ = NULL;
	Xcls_ClutterFilesXcls_title* _tmp25_ = NULL;
	JsRenderJsRender* _tmp26_ = NULL;
	JsRenderJsRender* _tmp27_ = NULL;
	ClutterActor* _tmp28_ = NULL;
	ClutterActor* _tmp29_ = NULL;
	ClutterActor* _tmp30_ = NULL;
	ClutterActor* _tmp31_ = NULL;
#line 165 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 165 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (file != NULL, NULL);
#line 165 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = (Xcls_ClutterFilesXcls_fileitem*) g_object_new (object_type, NULL);
#line 167 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = _owner;
#line 167 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 167 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 167 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv->_this = _tmp1_;
#line 168 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = clutter_actor_new ();
#line 168 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp2_);
#line 168 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 168 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->el = _tmp2_;
#line 173 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = self->el;
#line 173 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_reactive (_tmp3_, TRUE);
#line 174 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = self->priv->_this;
#line 174 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp5_ = xcls_clutterfiles_xcls_boxlayout5_new (_tmp4_);
#line 174 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	child_0 = _tmp5_;
#line 175 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref ((GObject*) child_0);
#line 176 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp6_ = self->el;
#line 176 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp7_ = child_0->el;
#line 176 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_layout_manager (_tmp6_, (ClutterLayoutManager*) _tmp7_);
#line 177 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp8_ = self->priv->_this;
#line 177 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp9_ = file;
#line 177 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp10_ = xcls_clutterfiles_xcls_image_new (_tmp8_, _tmp9_);
#line 177 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	child_1 = _tmp10_;
#line 178 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref ((GObject*) child_1);
#line 179 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp11_ = self->el;
#line 179 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp12_ = child_1->el;
#line 179 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_add_child (_tmp11_, (ClutterActor*) _tmp12_);
#line 180 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp13_ = _g_object_ref0 (child_1);
#line 180 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->image);
#line 180 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->image = _tmp13_;
#line 181 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp14_ = self->priv->_this;
#line 181 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp15_ = file;
#line 181 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp16_ = xcls_clutterfiles_xcls_typetitle_new (_tmp14_, _tmp15_);
#line 181 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	child_2 = _tmp16_;
#line 182 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref ((GObject*) child_2);
#line 183 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp17_ = self->el;
#line 183 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp18_ = child_2->el;
#line 183 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_add_child (_tmp17_, (ClutterActor*) _tmp18_);
#line 184 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp19_ = _g_object_ref0 (child_2);
#line 184 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->typetitle);
#line 184 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->typetitle = _tmp19_;
#line 185 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp20_ = self->priv->_this;
#line 185 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp21_ = file;
#line 185 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp22_ = xcls_clutterfiles_xcls_title_new (_tmp20_, _tmp21_);
#line 185 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	child_3 = _tmp22_;
#line 186 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref ((GObject*) child_3);
#line 187 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp23_ = self->el;
#line 187 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp24_ = child_3->el;
#line 187 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_add_child (_tmp23_, (ClutterActor*) _tmp24_);
#line 188 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp25_ = _g_object_ref0 (child_3);
#line 188 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->title);
#line 188 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->title = _tmp25_;
#line 191 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp26_ = file;
#line 191 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp27_ = _g_object_ref0 (_tmp26_);
#line 191 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->file);
#line 191 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->file = _tmp27_;
#line 192 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp28_ = self->el;
#line 192 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_size (_tmp28_, (gfloat) 100, (gfloat) 100);
#line 195 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp29_ = self->el;
#line 195 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_signal_connect_object (_tmp29_, "enter-event", (GCallback) ___lambda49__clutter_actor_enter_event, self, 0);
#line 199 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp30_ = self->el;
#line 199 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_signal_connect_object (_tmp30_, "leave-event", (GCallback) ___lambda50__clutter_actor_leave_event, self, 0);
#line 203 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp31_ = self->el;
#line 203 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_signal_connect_object (_tmp31_, "button-press-event", (GCallback) ___lambda51__clutter_actor_button_press_event, self, 0);
#line 165 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (child_3);
#line 165 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (child_2);
#line 165 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (child_1);
#line 165 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (child_0);
#line 165 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return self;
#line 1234 "ClutterFiles.vala.c"
}


Xcls_ClutterFilesXcls_fileitem* xcls_clutterfiles_xcls_fileitem_new (Xcls_ClutterFiles* _owner, JsRenderJsRender* file) {
#line 165 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return xcls_clutterfiles_xcls_fileitem_construct (XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM, _owner, file);
#line 1241 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_fileitem_class_init (Xcls_ClutterFilesXcls_fileitemClass * klass) {
#line 152 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	xcls_clutterfiles_xcls_fileitem_parent_class = g_type_class_peek_parent (klass);
#line 152 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_type_class_add_private (klass, sizeof (Xcls_ClutterFilesXcls_fileitemPrivate));
#line 152 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_clutterfiles_xcls_fileitem_finalize;
#line 1252 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_fileitem_instance_init (Xcls_ClutterFilesXcls_fileitem * self) {
#line 152 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv = XCLS_CLUTTERFILES_XCLS_FILEITEM_GET_PRIVATE (self);
#line 1259 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_fileitem_finalize (GObject* obj) {
	Xcls_ClutterFilesXcls_fileitem * self;
#line 152 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_CLUTTERFILES_TYPE_XCLS_FILEITEM, Xcls_ClutterFilesXcls_fileitem);
#line 154 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 155 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 159 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->file);
#line 160 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->image);
#line 161 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->typetitle);
#line 162 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->title);
#line 152 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (xcls_clutterfiles_xcls_fileitem_parent_class)->finalize (obj);
#line 1281 "ClutterFiles.vala.c"
}


GType xcls_clutterfiles_xcls_fileitem_get_type (void) {
	static volatile gsize xcls_clutterfiles_xcls_fileitem_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_clutterfiles_xcls_fileitem_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_ClutterFilesXcls_fileitemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_clutterfiles_xcls_fileitem_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_ClutterFilesXcls_fileitem), 0, (GInstanceInitFunc) xcls_clutterfiles_xcls_fileitem_instance_init, NULL };
		GType xcls_clutterfiles_xcls_fileitem_type_id;
		xcls_clutterfiles_xcls_fileitem_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_ClutterFilesXcls_fileitem", &g_define_type_info, 0);
		g_once_init_leave (&xcls_clutterfiles_xcls_fileitem_type_id__volatile, xcls_clutterfiles_xcls_fileitem_type_id);
	}
	return xcls_clutterfiles_xcls_fileitem_type_id__volatile;
}


Xcls_ClutterFilesXcls_BoxLayout5* xcls_clutterfiles_xcls_boxlayout5_construct (GType object_type, Xcls_ClutterFiles* _owner) {
	Xcls_ClutterFilesXcls_BoxLayout5 * self = NULL;
	Xcls_ClutterFiles* _tmp0_ = NULL;
	Xcls_ClutterFiles* _tmp1_ = NULL;
	ClutterBoxLayout* _tmp2_ = NULL;
	ClutterBoxLayout* _tmp3_ = NULL;
	ClutterBoxLayout* _tmp4_ = NULL;
#line 222 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 222 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = (Xcls_ClutterFilesXcls_BoxLayout5*) g_object_new (object_type, NULL);
#line 224 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = _owner;
#line 224 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 224 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 224 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv->_this = _tmp1_;
#line 225 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = (ClutterBoxLayout*) clutter_box_layout_new ();
#line 225 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp2_);
#line 225 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 225 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->el = _tmp2_;
#line 230 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = self->el;
#line 230 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_box_layout_set_orientation (_tmp3_, CLUTTER_ORIENTATION_VERTICAL);
#line 231 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = self->el;
#line 231 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_box_layout_set_spacing (_tmp4_, (guint) 4);
#line 222 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return self;
#line 1334 "ClutterFiles.vala.c"
}


Xcls_ClutterFilesXcls_BoxLayout5* xcls_clutterfiles_xcls_boxlayout5_new (Xcls_ClutterFiles* _owner) {
#line 222 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return xcls_clutterfiles_xcls_boxlayout5_construct (XCLS_CLUTTERFILES_TYPE_XCLS_BOXLAYOUT5, _owner);
#line 1341 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_boxlayout5_class_init (Xcls_ClutterFilesXcls_BoxLayout5Class * klass) {
#line 213 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	xcls_clutterfiles_xcls_boxlayout5_parent_class = g_type_class_peek_parent (klass);
#line 213 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_type_class_add_private (klass, sizeof (Xcls_ClutterFilesXcls_BoxLayout5Private));
#line 213 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_clutterfiles_xcls_boxlayout5_finalize;
#line 1352 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_boxlayout5_instance_init (Xcls_ClutterFilesXcls_BoxLayout5 * self) {
#line 213 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv = XCLS_CLUTTERFILES_XCLS_BOXLAYOUT5_GET_PRIVATE (self);
#line 1359 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_boxlayout5_finalize (GObject* obj) {
	Xcls_ClutterFilesXcls_BoxLayout5 * self;
#line 213 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_CLUTTERFILES_TYPE_XCLS_BOXLAYOUT5, Xcls_ClutterFilesXcls_BoxLayout5);
#line 215 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 216 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 213 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (xcls_clutterfiles_xcls_boxlayout5_parent_class)->finalize (obj);
#line 1373 "ClutterFiles.vala.c"
}


GType xcls_clutterfiles_xcls_boxlayout5_get_type (void) {
	static volatile gsize xcls_clutterfiles_xcls_boxlayout5_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_clutterfiles_xcls_boxlayout5_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_ClutterFilesXcls_BoxLayout5Class), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_clutterfiles_xcls_boxlayout5_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_ClutterFilesXcls_BoxLayout5), 0, (GInstanceInitFunc) xcls_clutterfiles_xcls_boxlayout5_instance_init, NULL };
		GType xcls_clutterfiles_xcls_boxlayout5_type_id;
		xcls_clutterfiles_xcls_boxlayout5_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_ClutterFilesXcls_BoxLayout5", &g_define_type_info, 0);
		g_once_init_leave (&xcls_clutterfiles_xcls_boxlayout5_type_id__volatile, xcls_clutterfiles_xcls_boxlayout5_type_id);
	}
	return xcls_clutterfiles_xcls_boxlayout5_type_id__volatile;
}


Xcls_ClutterFilesXcls_image* xcls_clutterfiles_xcls_image_construct (GType object_type, Xcls_ClutterFiles* _owner, JsRenderJsRender* file) {
	Xcls_ClutterFilesXcls_image * self = NULL;
	Xcls_ClutterFiles* _tmp0_ = NULL;
	Xcls_ClutterFiles* _tmp1_ = NULL;
	ClutterTexture* _tmp2_ = NULL;
	JsRenderJsRender* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	ClutterTexture* _tmp6_ = NULL;
	ClutterTexture* _tmp7_ = NULL;
	ClutterTexture* _tmp8_ = NULL;
	ClutterTexture* _tmp9_ = NULL;
	ClutterTexture* _tmp10_ = NULL;
	ClutterTexture* _tmp11_ = NULL;
	ClutterTexture* _tmp12_ = NULL;
	ClutterTexture* _tmp13_ = NULL;
	ClutterTexture* _tmp14_ = NULL;
	ClutterTexture* _tmp15_ = NULL;
	GError * _inner_error_ = NULL;
#line 247 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 247 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (file != NULL, NULL);
#line 247 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = (Xcls_ClutterFilesXcls_image*) g_object_new (object_type, NULL);
#line 249 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = _owner;
#line 249 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 249 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 249 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv->_this = _tmp1_;
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = file;
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = js_render_js_render_getIconFileName (_tmp3_, TRUE);
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp5_ = _tmp4_;
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp6_ = (ClutterTexture*) clutter_texture_new_from_file (_tmp5_, &_inner_error_);
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp6_);
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp7_ = _tmp6_;
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_free0 (_tmp5_);
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = _tmp7_;
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	if (_inner_error_ != NULL) {
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		g_clear_error (&_inner_error_);
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
		return NULL;
#line 1446 "ClutterFiles.vala.c"
	}
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp8_ = _tmp2_;
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = NULL;
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp8_);
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 250 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->el = _tmp8_;
#line 255 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp9_ = self->el;
#line 255 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_margin_left ((ClutterActor*) _tmp9_, (gfloat) 5);
#line 256 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp10_ = self->el;
#line 256 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_margin_right ((ClutterActor*) _tmp10_, (gfloat) 5);
#line 257 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp11_ = self->el;
#line 257 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_margin_top ((ClutterActor*) _tmp11_, (gfloat) 5);
#line 258 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp12_ = self->el;
#line 258 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_x_align ((ClutterActor*) _tmp12_, CLUTTER_ACTOR_ALIGN_START);
#line 259 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp13_ = self->el;
#line 259 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_x_expand ((ClutterActor*) _tmp13_, TRUE);
#line 260 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp14_ = self->el;
#line 260 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_y_align ((ClutterActor*) _tmp14_, CLUTTER_ACTOR_ALIGN_START);
#line 261 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp15_ = self->el;
#line 261 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_y_expand ((ClutterActor*) _tmp15_, FALSE);
#line 247 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (_tmp2_);
#line 247 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return self;
#line 1490 "ClutterFiles.vala.c"
}


Xcls_ClutterFilesXcls_image* xcls_clutterfiles_xcls_image_new (Xcls_ClutterFiles* _owner, JsRenderJsRender* file) {
#line 247 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return xcls_clutterfiles_xcls_image_construct (XCLS_CLUTTERFILES_TYPE_XCLS_IMAGE, _owner, file);
#line 1497 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_image_class_init (Xcls_ClutterFilesXcls_imageClass * klass) {
#line 238 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	xcls_clutterfiles_xcls_image_parent_class = g_type_class_peek_parent (klass);
#line 238 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_type_class_add_private (klass, sizeof (Xcls_ClutterFilesXcls_imagePrivate));
#line 238 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_clutterfiles_xcls_image_finalize;
#line 1508 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_image_instance_init (Xcls_ClutterFilesXcls_image * self) {
#line 238 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv = XCLS_CLUTTERFILES_XCLS_IMAGE_GET_PRIVATE (self);
#line 1515 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_image_finalize (GObject* obj) {
	Xcls_ClutterFilesXcls_image * self;
#line 238 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_CLUTTERFILES_TYPE_XCLS_IMAGE, Xcls_ClutterFilesXcls_image);
#line 240 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 241 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 238 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (xcls_clutterfiles_xcls_image_parent_class)->finalize (obj);
#line 1529 "ClutterFiles.vala.c"
}


GType xcls_clutterfiles_xcls_image_get_type (void) {
	static volatile gsize xcls_clutterfiles_xcls_image_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_clutterfiles_xcls_image_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_ClutterFilesXcls_imageClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_clutterfiles_xcls_image_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_ClutterFilesXcls_image), 0, (GInstanceInitFunc) xcls_clutterfiles_xcls_image_instance_init, NULL };
		GType xcls_clutterfiles_xcls_image_type_id;
		xcls_clutterfiles_xcls_image_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_ClutterFilesXcls_image", &g_define_type_info, 0);
		g_once_init_leave (&xcls_clutterfiles_xcls_image_type_id__volatile, xcls_clutterfiles_xcls_image_type_id);
	}
	return xcls_clutterfiles_xcls_image_type_id__volatile;
}


Xcls_ClutterFilesXcls_typetitle* xcls_clutterfiles_xcls_typetitle_construct (GType object_type, Xcls_ClutterFiles* _owner, JsRenderJsRender* file) {
	Xcls_ClutterFilesXcls_typetitle * self = NULL;
	Xcls_ClutterFiles* _tmp0_ = NULL;
	Xcls_ClutterFiles* _tmp1_ = NULL;
	JsRenderJsRender* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	ClutterColor _tmp5_ = {0};
	ClutterText* _tmp6_ = NULL;
	ClutterText* _tmp7_ = NULL;
	ClutterText* _tmp8_ = NULL;
	ClutterText* _tmp9_ = NULL;
	ClutterText* _tmp10_ = NULL;
#line 277 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 277 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (file != NULL, NULL);
#line 277 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = (Xcls_ClutterFilesXcls_typetitle*) g_object_new (object_type, NULL);
#line 279 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = _owner;
#line 279 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 279 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 279 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv->_this = _tmp1_;
#line 280 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = file;
#line 280 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = js_render_js_render_nickType (_tmp2_);
#line 280 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = _tmp3_;
#line 280 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_color_from_string (&_tmp5_, "#fff");
#line 280 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp6_ = (ClutterText*) clutter_text_new_full ("Sans 10px", _tmp4_, &_tmp5_);
#line 280 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp6_);
#line 280 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 280 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->el = _tmp6_;
#line 280 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_free0 (_tmp4_);
#line 285 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp7_ = self->el;
#line 285 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_x_align ((ClutterActor*) _tmp7_, CLUTTER_ACTOR_ALIGN_START);
#line 286 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp8_ = self->el;
#line 286 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_x_expand ((ClutterActor*) _tmp8_, TRUE);
#line 287 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp9_ = self->el;
#line 287 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_y_align ((ClutterActor*) _tmp9_, CLUTTER_ACTOR_ALIGN_START);
#line 288 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp10_ = self->el;
#line 288 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_y_expand ((ClutterActor*) _tmp10_, FALSE);
#line 277 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return self;
#line 1608 "ClutterFiles.vala.c"
}


Xcls_ClutterFilesXcls_typetitle* xcls_clutterfiles_xcls_typetitle_new (Xcls_ClutterFiles* _owner, JsRenderJsRender* file) {
#line 277 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return xcls_clutterfiles_xcls_typetitle_construct (XCLS_CLUTTERFILES_TYPE_XCLS_TYPETITLE, _owner, file);
#line 1615 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_typetitle_class_init (Xcls_ClutterFilesXcls_typetitleClass * klass) {
#line 268 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	xcls_clutterfiles_xcls_typetitle_parent_class = g_type_class_peek_parent (klass);
#line 268 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_type_class_add_private (klass, sizeof (Xcls_ClutterFilesXcls_typetitlePrivate));
#line 268 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_clutterfiles_xcls_typetitle_finalize;
#line 1626 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_typetitle_instance_init (Xcls_ClutterFilesXcls_typetitle * self) {
#line 268 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv = XCLS_CLUTTERFILES_XCLS_TYPETITLE_GET_PRIVATE (self);
#line 1633 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_typetitle_finalize (GObject* obj) {
	Xcls_ClutterFilesXcls_typetitle * self;
#line 268 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_CLUTTERFILES_TYPE_XCLS_TYPETITLE, Xcls_ClutterFilesXcls_typetitle);
#line 270 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 271 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 268 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (xcls_clutterfiles_xcls_typetitle_parent_class)->finalize (obj);
#line 1647 "ClutterFiles.vala.c"
}


GType xcls_clutterfiles_xcls_typetitle_get_type (void) {
	static volatile gsize xcls_clutterfiles_xcls_typetitle_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_clutterfiles_xcls_typetitle_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_ClutterFilesXcls_typetitleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_clutterfiles_xcls_typetitle_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_ClutterFilesXcls_typetitle), 0, (GInstanceInitFunc) xcls_clutterfiles_xcls_typetitle_instance_init, NULL };
		GType xcls_clutterfiles_xcls_typetitle_type_id;
		xcls_clutterfiles_xcls_typetitle_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_ClutterFilesXcls_typetitle", &g_define_type_info, 0);
		g_once_init_leave (&xcls_clutterfiles_xcls_typetitle_type_id__volatile, xcls_clutterfiles_xcls_typetitle_type_id);
	}
	return xcls_clutterfiles_xcls_typetitle_type_id__volatile;
}


Xcls_ClutterFilesXcls_title* xcls_clutterfiles_xcls_title_construct (GType object_type, Xcls_ClutterFiles* _owner, JsRenderJsRender* file) {
	Xcls_ClutterFilesXcls_title * self = NULL;
	Xcls_ClutterFiles* _tmp0_ = NULL;
	Xcls_ClutterFiles* _tmp1_ = NULL;
	JsRenderJsRender* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	ClutterColor _tmp5_ = {0};
	ClutterText* _tmp6_ = NULL;
	ClutterText* _tmp7_ = NULL;
	ClutterText* _tmp8_ = NULL;
	ClutterText* _tmp9_ = NULL;
	ClutterText* _tmp10_ = NULL;
#line 304 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 304 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_return_val_if_fail (file != NULL, NULL);
#line 304 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = (Xcls_ClutterFilesXcls_title*) g_object_new (object_type, NULL);
#line 306 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp0_ = _owner;
#line 306 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 306 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 306 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv->_this = _tmp1_;
#line 307 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp2_ = file;
#line 307 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp3_ = js_render_js_render_nickName (_tmp2_);
#line 307 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp4_ = _tmp3_;
#line 307 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_color_from_string (&_tmp5_, "#fff");
#line 307 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp6_ = (ClutterText*) clutter_text_new_full ("Sans 10px", _tmp4_, &_tmp5_);
#line 307 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_object_ref_sink (_tmp6_);
#line 307 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 307 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->el = _tmp6_;
#line 307 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_free0 (_tmp4_);
#line 312 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp7_ = self->el;
#line 312 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_x_align ((ClutterActor*) _tmp7_, CLUTTER_ACTOR_ALIGN_START);
#line 313 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp8_ = self->el;
#line 313 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_x_expand ((ClutterActor*) _tmp8_, TRUE);
#line 314 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp9_ = self->el;
#line 314 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_y_align ((ClutterActor*) _tmp9_, CLUTTER_ACTOR_ALIGN_START);
#line 315 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_tmp10_ = self->el;
#line 315 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	clutter_actor_set_y_expand ((ClutterActor*) _tmp10_, FALSE);
#line 304 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return self;
#line 1726 "ClutterFiles.vala.c"
}


Xcls_ClutterFilesXcls_title* xcls_clutterfiles_xcls_title_new (Xcls_ClutterFiles* _owner, JsRenderJsRender* file) {
#line 304 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	return xcls_clutterfiles_xcls_title_construct (XCLS_CLUTTERFILES_TYPE_XCLS_TITLE, _owner, file);
#line 1733 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_title_class_init (Xcls_ClutterFilesXcls_titleClass * klass) {
#line 295 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	xcls_clutterfiles_xcls_title_parent_class = g_type_class_peek_parent (klass);
#line 295 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_type_class_add_private (klass, sizeof (Xcls_ClutterFilesXcls_titlePrivate));
#line 295 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_clutterfiles_xcls_title_finalize;
#line 1744 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_title_instance_init (Xcls_ClutterFilesXcls_title * self) {
#line 295 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv = XCLS_CLUTTERFILES_XCLS_TITLE_GET_PRIVATE (self);
#line 1751 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_xcls_title_finalize (GObject* obj) {
	Xcls_ClutterFilesXcls_title * self;
#line 295 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_CLUTTERFILES_TYPE_XCLS_TITLE, Xcls_ClutterFilesXcls_title);
#line 297 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 298 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 295 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (xcls_clutterfiles_xcls_title_parent_class)->finalize (obj);
#line 1765 "ClutterFiles.vala.c"
}


GType xcls_clutterfiles_xcls_title_get_type (void) {
	static volatile gsize xcls_clutterfiles_xcls_title_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_clutterfiles_xcls_title_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_ClutterFilesXcls_titleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_clutterfiles_xcls_title_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_ClutterFilesXcls_title), 0, (GInstanceInitFunc) xcls_clutterfiles_xcls_title_instance_init, NULL };
		GType xcls_clutterfiles_xcls_title_type_id;
		xcls_clutterfiles_xcls_title_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_ClutterFilesXcls_title", &g_define_type_info, 0);
		g_once_init_leave (&xcls_clutterfiles_xcls_title_type_id__volatile, xcls_clutterfiles_xcls_title_type_id);
	}
	return xcls_clutterfiles_xcls_title_type_id__volatile;
}


static void xcls_clutterfiles_class_init (Xcls_ClutterFilesClass * klass) {
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	xcls_clutterfiles_parent_class = g_type_class_peek_parent (klass);
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_type_class_add_private (klass, sizeof (Xcls_ClutterFilesPrivate));
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_clutterfiles_finalize;
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	g_signal_new ("open", TYPE_XCLS_CLUTTERFILES, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, JS_RENDER_TYPE_JS_RENDER);
#line 1790 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_instance_init (Xcls_ClutterFiles * self) {
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self->priv = XCLS_CLUTTERFILES_GET_PRIVATE (self);
#line 1797 "ClutterFiles.vala.c"
}


static void xcls_clutterfiles_finalize (GObject* obj) {
	Xcls_ClutterFiles * self;
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_XCLS_CLUTTERFILES, Xcls_ClutterFiles);
#line 22 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->el);
#line 23 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->priv->_this);
#line 25 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->filelayout);
#line 26 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->filelayout_manager);
#line 30 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	_g_object_unref0 (self->fileitems);
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/ClutterFiles.vala"
	G_OBJECT_CLASS (xcls_clutterfiles_parent_class)->finalize (obj);
#line 1817 "ClutterFiles.vala.c"
}


GType xcls_clutterfiles_get_type (void) {
	static volatile gsize xcls_clutterfiles_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_clutterfiles_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_ClutterFilesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_clutterfiles_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_ClutterFiles), 0, (GInstanceInitFunc) xcls_clutterfiles_instance_init, NULL };
		GType xcls_clutterfiles_type_id;
		xcls_clutterfiles_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_ClutterFiles", &g_define_type_info, 0);
		g_once_init_leave (&xcls_clutterfiles_type_id__volatile, xcls_clutterfiles_type_id);
	}
	return xcls_clutterfiles_type_id__volatile;
}



