/* DialogSaveModule.vala.c generated by valac 0.20.1, the Vala compiler
 * generated from DialogSaveModule.vala, do not modify */

/* -- to compile
valac  --pkg gio-2.0  --pkg posix  --pkg gtk+-3.0 --pkg libnotify --pkg gtksourceview-3.0  --pkg  libwnck-3.0 \
    /tmp/DialogSaveModule.vala  -o /tmp/DialogSaveModule
*/
/* -- to test class
static int main (string[] args) {
    Gtk.init (ref args);
    new Xcls_DialogSaveModule();
    DialogSaveModule.show_all();
     Gtk.main ();
    return 0;
}
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define TYPE_XCLS_DIALOGSAVEMODULE (xcls_dialogsavemodule_get_type ())
#define XCLS_DIALOGSAVEMODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_XCLS_DIALOGSAVEMODULE, Xcls_DialogSaveModule))
#define XCLS_DIALOGSAVEMODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_XCLS_DIALOGSAVEMODULE, Xcls_DialogSaveModuleClass))
#define IS_XCLS_DIALOGSAVEMODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_XCLS_DIALOGSAVEMODULE))
#define IS_XCLS_DIALOGSAVEMODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_XCLS_DIALOGSAVEMODULE))
#define XCLS_DIALOGSAVEMODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_XCLS_DIALOGSAVEMODULE, Xcls_DialogSaveModuleClass))

typedef struct _Xcls_DialogSaveModule Xcls_DialogSaveModule;
typedef struct _Xcls_DialogSaveModuleClass Xcls_DialogSaveModuleClass;
typedef struct _Xcls_DialogSaveModulePrivate Xcls_DialogSaveModulePrivate;

#define XCLS_DIALOGSAVEMODULE_TYPE_XCLS_NAME (xcls_dialogsavemodule_xcls_name_get_type ())
#define XCLS_DIALOGSAVEMODULE_XCLS_NAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_NAME, Xcls_DialogSaveModuleXcls_name))
#define XCLS_DIALOGSAVEMODULE_XCLS_NAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_NAME, Xcls_DialogSaveModuleXcls_nameClass))
#define XCLS_DIALOGSAVEMODULE_IS_XCLS_NAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_NAME))
#define XCLS_DIALOGSAVEMODULE_IS_XCLS_NAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_NAME))
#define XCLS_DIALOGSAVEMODULE_XCLS_NAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_NAME, Xcls_DialogSaveModuleXcls_nameClass))

typedef struct _Xcls_DialogSaveModuleXcls_name Xcls_DialogSaveModuleXcls_name;
typedef struct _Xcls_DialogSaveModuleXcls_nameClass Xcls_DialogSaveModuleXcls_nameClass;

#define JS_RENDER_TYPE_NODE (js_render_node_get_type ())
#define JS_RENDER_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JS_RENDER_TYPE_NODE, JsRenderNode))
#define JS_RENDER_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JS_RENDER_TYPE_NODE, JsRenderNodeClass))
#define JS_RENDER_IS_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JS_RENDER_TYPE_NODE))
#define JS_RENDER_IS_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JS_RENDER_TYPE_NODE))
#define JS_RENDER_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JS_RENDER_TYPE_NODE, JsRenderNodeClass))

typedef struct _JsRenderNode JsRenderNode;
typedef struct _JsRenderNodeClass JsRenderNodeClass;

#define PROJECT_TYPE_PROJECT (project_project_get_type ())
#define PROJECT_PROJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROJECT_TYPE_PROJECT, ProjectProject))
#define PROJECT_PROJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROJECT_TYPE_PROJECT, ProjectProjectClass))
#define PROJECT_IS_PROJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROJECT_TYPE_PROJECT))
#define PROJECT_IS_PROJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROJECT_TYPE_PROJECT))
#define PROJECT_PROJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROJECT_TYPE_PROJECT, ProjectProjectClass))

typedef struct _ProjectProject ProjectProject;
typedef struct _ProjectProjectClass ProjectProjectClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define XCLS_DIALOGSAVEMODULE_TYPE_XCLS_HBOX2 (xcls_dialogsavemodule_xcls_hbox2_get_type ())
#define XCLS_DIALOGSAVEMODULE_XCLS_HBOX2(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_HBOX2, Xcls_DialogSaveModuleXcls_HBox2))
#define XCLS_DIALOGSAVEMODULE_XCLS_HBOX2_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_HBOX2, Xcls_DialogSaveModuleXcls_HBox2Class))
#define XCLS_DIALOGSAVEMODULE_IS_XCLS_HBOX2(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_HBOX2))
#define XCLS_DIALOGSAVEMODULE_IS_XCLS_HBOX2_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_HBOX2))
#define XCLS_DIALOGSAVEMODULE_XCLS_HBOX2_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_HBOX2, Xcls_DialogSaveModuleXcls_HBox2Class))

typedef struct _Xcls_DialogSaveModuleXcls_HBox2 Xcls_DialogSaveModuleXcls_HBox2;
typedef struct _Xcls_DialogSaveModuleXcls_HBox2Class Xcls_DialogSaveModuleXcls_HBox2Class;
typedef struct _Xcls_DialogSaveModuleXcls_HBox2Private Xcls_DialogSaveModuleXcls_HBox2Private;

#define XCLS_DIALOGSAVEMODULE_TYPE_XCLS_BUTTON5 (xcls_dialogsavemodule_xcls_button5_get_type ())
#define XCLS_DIALOGSAVEMODULE_XCLS_BUTTON5(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_BUTTON5, Xcls_DialogSaveModuleXcls_Button5))
#define XCLS_DIALOGSAVEMODULE_XCLS_BUTTON5_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_BUTTON5, Xcls_DialogSaveModuleXcls_Button5Class))
#define XCLS_DIALOGSAVEMODULE_IS_XCLS_BUTTON5(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_BUTTON5))
#define XCLS_DIALOGSAVEMODULE_IS_XCLS_BUTTON5_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_BUTTON5))
#define XCLS_DIALOGSAVEMODULE_XCLS_BUTTON5_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_BUTTON5, Xcls_DialogSaveModuleXcls_Button5Class))

typedef struct _Xcls_DialogSaveModuleXcls_Button5 Xcls_DialogSaveModuleXcls_Button5;
typedef struct _Xcls_DialogSaveModuleXcls_Button5Class Xcls_DialogSaveModuleXcls_Button5Class;
typedef struct _Xcls_DialogSaveModuleXcls_Button5Private Xcls_DialogSaveModuleXcls_Button5Private;

#define XCLS_DIALOGSAVEMODULE_TYPE_XCLS_BUTTON6 (xcls_dialogsavemodule_xcls_button6_get_type ())
#define XCLS_DIALOGSAVEMODULE_XCLS_BUTTON6(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_BUTTON6, Xcls_DialogSaveModuleXcls_Button6))
#define XCLS_DIALOGSAVEMODULE_XCLS_BUTTON6_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_BUTTON6, Xcls_DialogSaveModuleXcls_Button6Class))
#define XCLS_DIALOGSAVEMODULE_IS_XCLS_BUTTON6(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_BUTTON6))
#define XCLS_DIALOGSAVEMODULE_IS_XCLS_BUTTON6_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_BUTTON6))
#define XCLS_DIALOGSAVEMODULE_XCLS_BUTTON6_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_BUTTON6, Xcls_DialogSaveModuleXcls_Button6Class))

typedef struct _Xcls_DialogSaveModuleXcls_Button6 Xcls_DialogSaveModuleXcls_Button6;
typedef struct _Xcls_DialogSaveModuleXcls_Button6Class Xcls_DialogSaveModuleXcls_Button6Class;
typedef struct _Xcls_DialogSaveModuleXcls_Button6Private Xcls_DialogSaveModuleXcls_Button6Private;
typedef struct _Xcls_DialogSaveModuleXcls_namePrivate Xcls_DialogSaveModuleXcls_namePrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_XCLS_STANDARDERRORDIALOG (xcls_standarderrordialog_get_type ())
#define XCLS_STANDARDERRORDIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_XCLS_STANDARDERRORDIALOG, Xcls_StandardErrorDialog))
#define XCLS_STANDARDERRORDIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_XCLS_STANDARDERRORDIALOG, Xcls_StandardErrorDialogClass))
#define IS_XCLS_STANDARDERRORDIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_XCLS_STANDARDERRORDIALOG))
#define IS_XCLS_STANDARDERRORDIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_XCLS_STANDARDERRORDIALOG))
#define XCLS_STANDARDERRORDIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_XCLS_STANDARDERRORDIALOG, Xcls_StandardErrorDialogClass))

typedef struct _Xcls_StandardErrorDialog Xcls_StandardErrorDialog;
typedef struct _Xcls_StandardErrorDialogClass Xcls_StandardErrorDialogClass;

#define JS_RENDER_TYPE_JS_RENDER (js_render_js_render_get_type ())
#define JS_RENDER_JS_RENDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JS_RENDER_TYPE_JS_RENDER, JsRenderJsRender))
#define JS_RENDER_JS_RENDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JS_RENDER_TYPE_JS_RENDER, JsRenderJsRenderClass))
#define JS_RENDER_IS_JS_RENDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JS_RENDER_TYPE_JS_RENDER))
#define JS_RENDER_IS_JS_RENDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JS_RENDER_TYPE_JS_RENDER))
#define JS_RENDER_JS_RENDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JS_RENDER_TYPE_JS_RENDER, JsRenderJsRenderClass))

typedef struct _JsRenderJsRender JsRenderJsRender;
typedef struct _JsRenderJsRenderClass JsRenderJsRenderClass;
typedef struct _JsRenderJsRenderPrivate JsRenderJsRenderPrivate;

#define XCLS_DIALOGSAVEMODULE_TYPE_XCLS_LABEL3 (xcls_dialogsavemodule_xcls_label3_get_type ())
#define XCLS_DIALOGSAVEMODULE_XCLS_LABEL3(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_LABEL3, Xcls_DialogSaveModuleXcls_Label3))
#define XCLS_DIALOGSAVEMODULE_XCLS_LABEL3_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_LABEL3, Xcls_DialogSaveModuleXcls_Label3Class))
#define XCLS_DIALOGSAVEMODULE_IS_XCLS_LABEL3(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_LABEL3))
#define XCLS_DIALOGSAVEMODULE_IS_XCLS_LABEL3_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_LABEL3))
#define XCLS_DIALOGSAVEMODULE_XCLS_LABEL3_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_LABEL3, Xcls_DialogSaveModuleXcls_Label3Class))

typedef struct _Xcls_DialogSaveModuleXcls_Label3 Xcls_DialogSaveModuleXcls_Label3;
typedef struct _Xcls_DialogSaveModuleXcls_Label3Class Xcls_DialogSaveModuleXcls_Label3Class;
typedef struct _Xcls_DialogSaveModuleXcls_Label3Private Xcls_DialogSaveModuleXcls_Label3Private;

struct _Xcls_DialogSaveModule {
	GObject parent_instance;
	Xcls_DialogSaveModulePrivate * priv;
	GtkDialog* el;
	Xcls_DialogSaveModuleXcls_name* name;
	JsRenderNode* data;
	ProjectProject* project;
};

struct _Xcls_DialogSaveModuleClass {
	GObjectClass parent_class;
};

struct _Xcls_DialogSaveModulePrivate {
	Xcls_DialogSaveModule* _this;
};

struct _Xcls_DialogSaveModuleXcls_HBox2 {
	GObject parent_instance;
	Xcls_DialogSaveModuleXcls_HBox2Private * priv;
	GtkHBox* el;
};

struct _Xcls_DialogSaveModuleXcls_HBox2Class {
	GObjectClass parent_class;
};

struct _Xcls_DialogSaveModuleXcls_Button5 {
	GObject parent_instance;
	Xcls_DialogSaveModuleXcls_Button5Private * priv;
	GtkButton* el;
};

struct _Xcls_DialogSaveModuleXcls_Button5Class {
	GObjectClass parent_class;
};

struct _Xcls_DialogSaveModuleXcls_Button6 {
	GObject parent_instance;
	Xcls_DialogSaveModuleXcls_Button6Private * priv;
	GtkButton* el;
};

struct _Xcls_DialogSaveModuleXcls_Button6Class {
	GObjectClass parent_class;
};

struct _Xcls_DialogSaveModuleXcls_name {
	GObject parent_instance;
	Xcls_DialogSaveModuleXcls_namePrivate * priv;
	GtkEntry* el;
};

struct _Xcls_DialogSaveModuleXcls_nameClass {
	GObjectClass parent_class;
};

struct _JsRenderJsRender {
	GObject parent_instance;
	JsRenderJsRenderPrivate * priv;
	GeeArrayList* doubleStringProps;
	gchar* id;
	gchar* name;
	gchar* fullname;
	gchar* path;
	gchar* parent;
	gchar* region;
	gchar* title;
	gchar* permname;
	gchar* modOrder;
	gchar* xtype;
	guint64 webkit_page_id;
	ProjectProject* project;
	JsRenderNode* tree;
	GList* cn;
	gboolean hasParent;
};

struct _JsRenderJsRenderClass {
	GObjectClass parent_class;
	void (*loadItems) (JsRenderJsRender* self, GError** error);
	void (*save) (JsRenderJsRender* self);
	void (*saveHTML) (JsRenderJsRender* self, const gchar* html);
	gchar* (*toSource) (JsRenderJsRender* self);
	gchar* (*toSourcePreview) (JsRenderJsRender* self);
	gchar* (*toValaSource) (JsRenderJsRender* self, gboolean testcompile);
};

struct _Xcls_DialogSaveModuleXcls_HBox2Private {
	Xcls_DialogSaveModule* _this;
};

struct _Xcls_DialogSaveModuleXcls_Label3 {
	GObject parent_instance;
	Xcls_DialogSaveModuleXcls_Label3Private * priv;
	GtkLabel* el;
};

struct _Xcls_DialogSaveModuleXcls_Label3Class {
	GObjectClass parent_class;
};

struct _Xcls_DialogSaveModuleXcls_Label3Private {
	Xcls_DialogSaveModule* _this;
};

struct _Xcls_DialogSaveModuleXcls_namePrivate {
	Xcls_DialogSaveModule* _this;
};

struct _Xcls_DialogSaveModuleXcls_Button5Private {
	Xcls_DialogSaveModule* _this;
};

struct _Xcls_DialogSaveModuleXcls_Button6Private {
	Xcls_DialogSaveModule* _this;
};


extern Xcls_DialogSaveModule* DialogSaveModule;
Xcls_DialogSaveModule* DialogSaveModule = NULL;
static gpointer xcls_dialogsavemodule_parent_class = NULL;
extern Xcls_StandardErrorDialog* StandardErrorDialog;
static gpointer xcls_dialogsavemodule_xcls_hbox2_parent_class = NULL;
static gpointer xcls_dialogsavemodule_xcls_label3_parent_class = NULL;
static gpointer xcls_dialogsavemodule_xcls_name_parent_class = NULL;
static gpointer xcls_dialogsavemodule_xcls_button5_parent_class = NULL;
static gpointer xcls_dialogsavemodule_xcls_button6_parent_class = NULL;

GType xcls_dialogsavemodule_get_type (void) G_GNUC_CONST;
GType xcls_dialogsavemodule_xcls_name_get_type (void) G_GNUC_CONST;
GType js_render_node_get_type (void) G_GNUC_CONST;
GType project_project_get_type (void) G_GNUC_CONST;
#define XCLS_DIALOGSAVEMODULE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_XCLS_DIALOGSAVEMODULE, Xcls_DialogSaveModulePrivate))
enum  {
	XCLS_DIALOGSAVEMODULE_DUMMY_PROPERTY
};
Xcls_DialogSaveModule* xcls_dialogsavemodule_singleton (void);
Xcls_DialogSaveModule* xcls_dialogsavemodule_new (void);
Xcls_DialogSaveModule* xcls_dialogsavemodule_construct (GType object_type);
Xcls_DialogSaveModuleXcls_HBox2* xcls_dialogsavemodule_xcls_hbox2_new (Xcls_DialogSaveModule* _owner);
Xcls_DialogSaveModuleXcls_HBox2* xcls_dialogsavemodule_xcls_hbox2_construct (GType object_type, Xcls_DialogSaveModule* _owner);
GType xcls_dialogsavemodule_xcls_hbox2_get_type (void) G_GNUC_CONST;
Xcls_DialogSaveModuleXcls_Button5* xcls_dialogsavemodule_xcls_button5_new (Xcls_DialogSaveModule* _owner);
Xcls_DialogSaveModuleXcls_Button5* xcls_dialogsavemodule_xcls_button5_construct (GType object_type, Xcls_DialogSaveModule* _owner);
GType xcls_dialogsavemodule_xcls_button5_get_type (void) G_GNUC_CONST;
Xcls_DialogSaveModuleXcls_Button6* xcls_dialogsavemodule_xcls_button6_new (Xcls_DialogSaveModule* _owner);
Xcls_DialogSaveModuleXcls_Button6* xcls_dialogsavemodule_xcls_button6_construct (GType object_type, Xcls_DialogSaveModule* _owner);
GType xcls_dialogsavemodule_xcls_button6_get_type (void) G_GNUC_CONST;
static gboolean __lambda20_ (Xcls_DialogSaveModule* self, GtkWidget* _self_, GdkEventAny* event);
static gboolean ___lambda20__gtk_widget_delete_event (GtkWidget* _sender, GdkEventAny* event, gpointer self);
gchar* xcls_dialogsavemodule_show (Xcls_DialogSaveModule* self, GtkWindow* parent, ProjectProject* project, JsRenderNode* data);
GType xcls_standarderrordialog_get_type (void) G_GNUC_CONST;
Xcls_StandardErrorDialog* xcls_standarderrordialog_singleton (void);
void xcls_standarderrordialog_show (Xcls_StandardErrorDialog* self, GtkWindow* win, const gchar* msg);
GType js_render_js_render_get_type (void) G_GNUC_CONST;
JsRenderJsRender* project_project_newFile (ProjectProject* self, const gchar* name);
JsRenderNode* js_render_node_deepClone (JsRenderNode* self);
void js_render_js_render_save (JsRenderJsRender* self);
#define XCLS_DIALOGSAVEMODULE_XCLS_HBOX2_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_HBOX2, Xcls_DialogSaveModuleXcls_HBox2Private))
enum  {
	XCLS_DIALOGSAVEMODULE_XCLS_HBOX2_DUMMY_PROPERTY
};
Xcls_DialogSaveModuleXcls_Label3* xcls_dialogsavemodule_xcls_label3_new (Xcls_DialogSaveModule* _owner);
Xcls_DialogSaveModuleXcls_Label3* xcls_dialogsavemodule_xcls_label3_construct (GType object_type, Xcls_DialogSaveModule* _owner);
GType xcls_dialogsavemodule_xcls_label3_get_type (void) G_GNUC_CONST;
Xcls_DialogSaveModuleXcls_name* xcls_dialogsavemodule_xcls_name_new (Xcls_DialogSaveModule* _owner);
Xcls_DialogSaveModuleXcls_name* xcls_dialogsavemodule_xcls_name_construct (GType object_type, Xcls_DialogSaveModule* _owner);
static void xcls_dialogsavemodule_xcls_hbox2_finalize (GObject* obj);
#define XCLS_DIALOGSAVEMODULE_XCLS_LABEL3_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_LABEL3, Xcls_DialogSaveModuleXcls_Label3Private))
enum  {
	XCLS_DIALOGSAVEMODULE_XCLS_LABEL3_DUMMY_PROPERTY
};
static void xcls_dialogsavemodule_xcls_label3_finalize (GObject* obj);
#define XCLS_DIALOGSAVEMODULE_XCLS_NAME_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_NAME, Xcls_DialogSaveModuleXcls_namePrivate))
enum  {
	XCLS_DIALOGSAVEMODULE_XCLS_NAME_DUMMY_PROPERTY
};
static void xcls_dialogsavemodule_xcls_name_finalize (GObject* obj);
#define XCLS_DIALOGSAVEMODULE_XCLS_BUTTON5_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_BUTTON5, Xcls_DialogSaveModuleXcls_Button5Private))
enum  {
	XCLS_DIALOGSAVEMODULE_XCLS_BUTTON5_DUMMY_PROPERTY
};
static void xcls_dialogsavemodule_xcls_button5_finalize (GObject* obj);
#define XCLS_DIALOGSAVEMODULE_XCLS_BUTTON6_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_DIALOGSAVEMODULE_TYPE_XCLS_BUTTON6, Xcls_DialogSaveModuleXcls_Button6Private))
enum  {
	XCLS_DIALOGSAVEMODULE_XCLS_BUTTON6_DUMMY_PROPERTY
};
static void xcls_dialogsavemodule_xcls_button6_finalize (GObject* obj);
static void xcls_dialogsavemodule_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
#line 30 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	return self ? g_object_ref (self) : NULL;
#line 332 "DialogSaveModule.vala.c"
}


Xcls_DialogSaveModule* xcls_dialogsavemodule_singleton (void) {
	Xcls_DialogSaveModule* result = NULL;
	Xcls_DialogSaveModule* _tmp0_;
	Xcls_DialogSaveModule* _tmp2_;
	Xcls_DialogSaveModule* _tmp3_;
#line 27 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp0_ = DialogSaveModule;
#line 27 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	if (_tmp0_ == NULL) {
#line 345 "DialogSaveModule.vala.c"
		Xcls_DialogSaveModule* _tmp1_;
#line 28 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		_tmp1_ = xcls_dialogsavemodule_new ();
#line 28 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		_g_object_unref0 (DialogSaveModule);
#line 28 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		DialogSaveModule = _tmp1_;
#line 353 "DialogSaveModule.vala.c"
	}
#line 30 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp2_ = DialogSaveModule;
#line 30 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 30 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	result = _tmp3_;
#line 30 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	return result;
#line 363 "DialogSaveModule.vala.c"
}


static gboolean __lambda20_ (Xcls_DialogSaveModule* self, GtkWidget* _self_, GdkEventAny* event) {
	gboolean result = FALSE;
	GtkDialog* _tmp0_;
#line 63 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_return_val_if_fail (_self_ != NULL, FALSE);
#line 63 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 64 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp0_ = self->el;
#line 64 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	gtk_dialog_response (_tmp0_, (gint) GTK_RESPONSE_CANCEL);
#line 65 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	result = TRUE;
#line 65 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	return result;
#line 382 "DialogSaveModule.vala.c"
}


static gboolean ___lambda20__gtk_widget_delete_event (GtkWidget* _sender, GdkEventAny* event, gpointer self) {
	gboolean result;
	result = __lambda20_ (self, _sender, event);
#line 63 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	return result;
#line 391 "DialogSaveModule.vala.c"
}


Xcls_DialogSaveModule* xcls_dialogsavemodule_construct (GType object_type) {
	Xcls_DialogSaveModule * self = NULL;
	Xcls_DialogSaveModule* _tmp0_;
	GtkDialog* _tmp1_;
	GtkDialog* _tmp2_;
	GtkDialog* _tmp3_;
	GtkDialog* _tmp4_;
	Xcls_DialogSaveModule* _tmp5_;
	Xcls_DialogSaveModuleXcls_HBox2* _tmp6_;
	Xcls_DialogSaveModuleXcls_HBox2* child_0;
	GtkDialog* _tmp7_;
	GtkBox* _tmp8_ = NULL;
	GtkHBox* _tmp9_;
	Xcls_DialogSaveModule* _tmp10_;
	Xcls_DialogSaveModuleXcls_Button5* _tmp11_;
	Xcls_DialogSaveModuleXcls_Button5* child_1;
	GtkDialog* _tmp12_;
	GtkButton* _tmp13_;
	Xcls_DialogSaveModule* _tmp14_;
	Xcls_DialogSaveModuleXcls_Button6* _tmp15_;
	Xcls_DialogSaveModuleXcls_Button6* child_2;
	GtkDialog* _tmp16_;
	GtkButton* _tmp17_;
	GtkDialog* _tmp18_;
#line 39 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self = (Xcls_DialogSaveModule*) g_object_new (object_type, NULL);
#line 41 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 41 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->priv->_this);
#line 41 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->priv->_this = _tmp0_;
#line 42 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp1_ = (GtkDialog*) gtk_dialog_new ();
#line 42 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_object_ref_sink (_tmp1_);
#line 42 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->el);
#line 42 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->el = _tmp1_;
#line 47 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp2_ = self->el;
#line 47 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_object_set ((GtkWindow*) _tmp2_, "default-height", 200, NULL);
#line 48 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp3_ = self->el;
#line 48 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_object_set ((GtkWindow*) _tmp3_, "default-width", 400, NULL);
#line 49 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp4_ = self->el;
#line 49 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	gtk_window_set_modal ((GtkWindow*) _tmp4_, TRUE);
#line 50 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp5_ = self->priv->_this;
#line 50 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp6_ = xcls_dialogsavemodule_xcls_hbox2_new (_tmp5_);
#line 50 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	child_0 = _tmp6_;
#line 51 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_object_ref ((GObject*) child_0);
#line 52 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp7_ = self->el;
#line 52 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp8_ = gtk_dialog_get_content_area (_tmp7_);
#line 52 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp9_ = child_0->el;
#line 52 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	gtk_container_add ((GtkContainer*) _tmp8_, (GtkWidget*) _tmp9_);
#line 55 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp10_ = self->priv->_this;
#line 55 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp11_ = xcls_dialogsavemodule_xcls_button5_new (_tmp10_);
#line 55 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	child_1 = _tmp11_;
#line 56 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_object_ref ((GObject*) child_1);
#line 57 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp12_ = self->el;
#line 57 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp13_ = child_1->el;
#line 57 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	gtk_dialog_add_action_widget (_tmp12_, (GtkWidget*) _tmp13_, 0);
#line 58 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp14_ = self->priv->_this;
#line 58 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp15_ = xcls_dialogsavemodule_xcls_button6_new (_tmp14_);
#line 58 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	child_2 = _tmp15_;
#line 59 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_object_ref ((GObject*) child_2);
#line 60 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp16_ = self->el;
#line 60 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp17_ = child_2->el;
#line 60 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	gtk_dialog_add_action_widget (_tmp16_, (GtkWidget*) _tmp17_, 1);
#line 63 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp18_ = self->el;
#line 63 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_signal_connect_object ((GtkWidget*) _tmp18_, "delete-event", (GCallback) ___lambda20__gtk_widget_delete_event, self, 0);
#line 39 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (child_2);
#line 39 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (child_1);
#line 39 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (child_0);
#line 39 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	return self;
#line 503 "DialogSaveModule.vala.c"
}


Xcls_DialogSaveModule* xcls_dialogsavemodule_new (void) {
#line 39 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	return xcls_dialogsavemodule_construct (TYPE_XCLS_DIALOGSAVEMODULE);
#line 510 "DialogSaveModule.vala.c"
}


gchar* xcls_dialogsavemodule_show (Xcls_DialogSaveModule* self, GtkWindow* parent, ProjectProject* project, JsRenderNode* data) {
	gchar* result = NULL;
	GtkDialog* _tmp0_;
	GtkWindow* _tmp1_;
	GtkDialog* _tmp2_;
	JsRenderNode* _tmp3_;
	JsRenderNode* _tmp4_;
	ProjectProject* _tmp5_;
	ProjectProject* _tmp6_;
	Xcls_DialogSaveModuleXcls_name* _tmp7_;
	GtkEntry* _tmp8_;
	GtkDialog* _tmp9_;
	gchar* _tmp10_;
	gchar* name;
	ProjectProject* _tmp38_;
	const gchar* _tmp39_;
	JsRenderJsRender* _tmp40_ = NULL;
	JsRenderJsRender* f;
	JsRenderJsRender* _tmp41_;
	Xcls_DialogSaveModule* _tmp42_;
	JsRenderNode* _tmp43_;
	JsRenderNode* _tmp44_ = NULL;
	JsRenderJsRender* _tmp45_;
	GtkDialog* _tmp46_;
#line 71 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 71 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_return_val_if_fail (parent != NULL, NULL);
#line 71 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_return_val_if_fail (project != NULL, NULL);
#line 71 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_return_val_if_fail (data != NULL, NULL);
#line 74 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp0_ = self->el;
#line 74 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp1_ = parent;
#line 74 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	gtk_window_set_transient_for ((GtkWindow*) _tmp0_, _tmp1_);
#line 75 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp2_ = self->el;
#line 75 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	gtk_window_set_modal ((GtkWindow*) _tmp2_, TRUE);
#line 77 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp3_ = data;
#line 77 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp4_ = _g_object_ref0 (_tmp3_);
#line 77 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->data);
#line 77 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->data = _tmp4_;
#line 78 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp5_ = project;
#line 78 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp6_ = _g_object_ref0 (_tmp5_);
#line 78 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->project);
#line 78 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->project = _tmp6_;
#line 79 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp7_ = self->name;
#line 79 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp8_ = _tmp7_->el;
#line 79 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	gtk_entry_set_text (_tmp8_, "");
#line 80 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp9_ = self->el;
#line 80 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp9_);
#line 81 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp10_ = g_strdup ("");
#line 81 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	name = _tmp10_;
#line 82 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	while (TRUE) {
#line 588 "DialogSaveModule.vala.c"
		GtkDialog* _tmp11_;
		gint _tmp12_ = 0;
		gint response_id;
		gint _tmp13_;
		Xcls_DialogSaveModule* _tmp16_;
		Xcls_DialogSaveModuleXcls_name* _tmp17_;
		GtkEntry* _tmp18_;
		const gchar* _tmp19_ = NULL;
		gchar* _tmp20_;
		const gchar* _tmp21_;
		gint _tmp22_;
		gint _tmp23_;
		gboolean _tmp29_ = FALSE;
		const gchar* _tmp30_;
		gboolean _tmp31_ = FALSE;
		gboolean _tmp34_;
#line 83 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		_tmp11_ = self->el;
#line 83 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		_tmp12_ = gtk_dialog_run (_tmp11_);
#line 83 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		response_id = _tmp12_;
#line 84 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		_tmp13_ = response_id;
#line 84 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		if (_tmp13_ < 1) {
#line 615 "DialogSaveModule.vala.c"
			GtkDialog* _tmp14_;
			gchar* _tmp15_;
#line 85 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			_tmp14_ = self->el;
#line 85 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			gtk_widget_hide ((GtkWidget*) _tmp14_);
#line 86 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			_tmp15_ = g_strdup ("");
#line 86 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			result = _tmp15_;
#line 86 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			_g_free0 (name);
#line 86 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			return result;
#line 630 "DialogSaveModule.vala.c"
		}
#line 89 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		_tmp16_ = self->priv->_this;
#line 89 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		_tmp17_ = _tmp16_->name;
#line 89 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		_tmp18_ = _tmp17_->el;
#line 89 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		_tmp19_ = gtk_entry_get_text (_tmp18_);
#line 89 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		_tmp20_ = g_strdup (_tmp19_);
#line 89 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		_g_free0 (name);
#line 89 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		name = _tmp20_;
#line 90 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		_tmp21_ = name;
#line 90 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		_tmp22_ = strlen (_tmp21_);
#line 90 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		_tmp23_ = _tmp22_;
#line 90 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		if (_tmp23_ < 1) {
#line 654 "DialogSaveModule.vala.c"
			Xcls_StandardErrorDialog* _tmp24_;
			Xcls_StandardErrorDialog* _tmp25_ = NULL;
			Xcls_StandardErrorDialog* _tmp26_;
			Xcls_DialogSaveModule* _tmp27_;
			GtkDialog* _tmp28_;
#line 91 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			_tmp24_ = StandardErrorDialog;
#line 91 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			_tmp25_ = xcls_standarderrordialog_singleton ();
#line 91 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			_tmp26_ = _tmp25_;
#line 91 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			_tmp27_ = self->priv->_this;
#line 91 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			_tmp28_ = _tmp27_->el;
#line 91 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			xcls_standarderrordialog_show (_tmp26_, G_TYPE_CHECK_INSTANCE_CAST (_tmp28_, GTK_TYPE_WINDOW, GtkWindow), "You must give the template a name. ");
#line 91 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			_g_object_unref0 (_tmp26_);
#line 95 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			continue;
#line 676 "DialogSaveModule.vala.c"
		}
#line 97 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		_tmp30_ = name;
#line 97 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		_tmp31_ = g_regex_match_simple ("^[A-Za-z.]+$", _tmp30_, 0, 0);
#line 97 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		if (!_tmp31_) {
#line 97 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			_tmp29_ = TRUE;
#line 686 "DialogSaveModule.vala.c"
		} else {
			const gchar* _tmp32_;
			gboolean _tmp33_ = FALSE;
#line 98 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			_tmp32_ = name;
#line 98 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			_tmp33_ = g_regex_match_simple ("^[A-Za-z.]+$", _tmp32_, 0, 0);
#line 98 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			_tmp29_ = !_tmp33_;
#line 696 "DialogSaveModule.vala.c"
		}
#line 97 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		_tmp34_ = _tmp29_;
#line 97 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		if (_tmp34_) {
#line 702 "DialogSaveModule.vala.c"
			Xcls_StandardErrorDialog* _tmp35_;
			Xcls_DialogSaveModule* _tmp36_;
			GtkDialog* _tmp37_;
#line 100 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			_tmp35_ = StandardErrorDialog;
#line 100 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			_tmp36_ = self->priv->_this;
#line 100 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			_tmp37_ = _tmp36_->el;
#line 100 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			xcls_standarderrordialog_show (_tmp35_, G_TYPE_CHECK_INSTANCE_CAST (_tmp37_, GTK_TYPE_WINDOW, GtkWindow), "Template Nane must contain only letters dots");
#line 105 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
			continue;
#line 716 "DialogSaveModule.vala.c"
		}
#line 107 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
		break;
#line 720 "DialogSaveModule.vala.c"
	}
#line 109 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp38_ = project;
#line 109 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp39_ = name;
#line 109 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp40_ = project_project_newFile (_tmp38_, _tmp39_);
#line 109 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	f = _tmp40_;
#line 110 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp41_ = f;
#line 110 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp42_ = self->priv->_this;
#line 110 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp43_ = _tmp42_->data;
#line 110 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp44_ = js_render_node_deepClone (_tmp43_);
#line 110 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (_tmp41_->tree);
#line 110 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp41_->tree = _tmp44_;
#line 111 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp45_ = f;
#line 111 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	js_render_js_render_save (_tmp45_);
#line 114 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp46_ = self->el;
#line 114 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	gtk_widget_hide ((GtkWidget*) _tmp46_);
#line 116 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	result = name;
#line 116 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (f);
#line 116 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	return result;
#line 756 "DialogSaveModule.vala.c"
}


Xcls_DialogSaveModuleXcls_HBox2* xcls_dialogsavemodule_xcls_hbox2_construct (GType object_type, Xcls_DialogSaveModule* _owner) {
	Xcls_DialogSaveModuleXcls_HBox2 * self = NULL;
	Xcls_DialogSaveModule* _tmp0_;
	Xcls_DialogSaveModule* _tmp1_;
	GtkHBox* _tmp2_;
	Xcls_DialogSaveModule* _tmp3_;
	Xcls_DialogSaveModuleXcls_Label3* _tmp4_;
	Xcls_DialogSaveModuleXcls_Label3* child_0;
	GtkHBox* _tmp5_;
	GtkLabel* _tmp6_;
	Xcls_DialogSaveModule* _tmp7_;
	Xcls_DialogSaveModuleXcls_name* _tmp8_;
	Xcls_DialogSaveModuleXcls_name* child_1;
	GtkHBox* _tmp9_;
	GtkEntry* _tmp10_;
#line 132 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 132 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self = (Xcls_DialogSaveModuleXcls_HBox2*) g_object_new (object_type, NULL);
#line 134 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp0_ = _owner;
#line 134 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 134 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->priv->_this);
#line 134 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->priv->_this = _tmp1_;
#line 135 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp2_ = (GtkHBox*) gtk_hbox_new (TRUE, 0);
#line 135 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_object_ref_sink (_tmp2_);
#line 135 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->el);
#line 135 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->el = _tmp2_;
#line 140 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp3_ = self->priv->_this;
#line 140 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp4_ = xcls_dialogsavemodule_xcls_label3_new (_tmp3_);
#line 140 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	child_0 = _tmp4_;
#line 141 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_object_ref ((GObject*) child_0);
#line 142 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp5_ = self->el;
#line 142 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp6_ = child_0->el;
#line 142 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	gtk_container_add ((GtkContainer*) _tmp5_, (GtkWidget*) _tmp6_);
#line 143 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp7_ = self->priv->_this;
#line 143 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp8_ = xcls_dialogsavemodule_xcls_name_new (_tmp7_);
#line 143 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	child_1 = _tmp8_;
#line 144 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_object_ref ((GObject*) child_1);
#line 145 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp9_ = self->el;
#line 145 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp10_ = child_1->el;
#line 145 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	gtk_container_add ((GtkContainer*) _tmp9_, (GtkWidget*) _tmp10_);
#line 132 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (child_1);
#line 132 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (child_0);
#line 132 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	return self;
#line 829 "DialogSaveModule.vala.c"
}


Xcls_DialogSaveModuleXcls_HBox2* xcls_dialogsavemodule_xcls_hbox2_new (Xcls_DialogSaveModule* _owner) {
#line 132 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	return xcls_dialogsavemodule_xcls_hbox2_construct (XCLS_DIALOGSAVEMODULE_TYPE_XCLS_HBOX2, _owner);
#line 836 "DialogSaveModule.vala.c"
}


static void xcls_dialogsavemodule_xcls_hbox2_class_init (Xcls_DialogSaveModuleXcls_HBox2Class * klass) {
#line 123 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	xcls_dialogsavemodule_xcls_hbox2_parent_class = g_type_class_peek_parent (klass);
#line 123 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_type_class_add_private (klass, sizeof (Xcls_DialogSaveModuleXcls_HBox2Private));
#line 123 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_dialogsavemodule_xcls_hbox2_finalize;
#line 847 "DialogSaveModule.vala.c"
}


static void xcls_dialogsavemodule_xcls_hbox2_instance_init (Xcls_DialogSaveModuleXcls_HBox2 * self) {
#line 123 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->priv = XCLS_DIALOGSAVEMODULE_XCLS_HBOX2_GET_PRIVATE (self);
#line 854 "DialogSaveModule.vala.c"
}


static void xcls_dialogsavemodule_xcls_hbox2_finalize (GObject* obj) {
	Xcls_DialogSaveModuleXcls_HBox2 * self;
#line 123 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_DIALOGSAVEMODULE_TYPE_XCLS_HBOX2, Xcls_DialogSaveModuleXcls_HBox2);
#line 125 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->el);
#line 126 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->priv->_this);
#line 123 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	G_OBJECT_CLASS (xcls_dialogsavemodule_xcls_hbox2_parent_class)->finalize (obj);
#line 868 "DialogSaveModule.vala.c"
}


GType xcls_dialogsavemodule_xcls_hbox2_get_type (void) {
	static volatile gsize xcls_dialogsavemodule_xcls_hbox2_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_dialogsavemodule_xcls_hbox2_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_DialogSaveModuleXcls_HBox2Class), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_dialogsavemodule_xcls_hbox2_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_DialogSaveModuleXcls_HBox2), 0, (GInstanceInitFunc) xcls_dialogsavemodule_xcls_hbox2_instance_init, NULL };
		GType xcls_dialogsavemodule_xcls_hbox2_type_id;
		xcls_dialogsavemodule_xcls_hbox2_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_DialogSaveModuleXcls_HBox2", &g_define_type_info, 0);
		g_once_init_leave (&xcls_dialogsavemodule_xcls_hbox2_type_id__volatile, xcls_dialogsavemodule_xcls_hbox2_type_id);
	}
	return xcls_dialogsavemodule_xcls_hbox2_type_id__volatile;
}


Xcls_DialogSaveModuleXcls_Label3* xcls_dialogsavemodule_xcls_label3_construct (GType object_type, Xcls_DialogSaveModule* _owner) {
	Xcls_DialogSaveModuleXcls_Label3 * self = NULL;
	Xcls_DialogSaveModule* _tmp0_;
	Xcls_DialogSaveModule* _tmp1_;
	GtkLabel* _tmp2_;
#line 161 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 161 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self = (Xcls_DialogSaveModuleXcls_Label3*) g_object_new (object_type, NULL);
#line 163 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp0_ = _owner;
#line 163 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 163 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->priv->_this);
#line 163 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->priv->_this = _tmp1_;
#line 164 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp2_ = (GtkLabel*) gtk_label_new ("Name");
#line 164 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_object_ref_sink (_tmp2_);
#line 164 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->el);
#line 164 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->el = _tmp2_;
#line 161 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	return self;
#line 911 "DialogSaveModule.vala.c"
}


Xcls_DialogSaveModuleXcls_Label3* xcls_dialogsavemodule_xcls_label3_new (Xcls_DialogSaveModule* _owner) {
#line 161 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	return xcls_dialogsavemodule_xcls_label3_construct (XCLS_DIALOGSAVEMODULE_TYPE_XCLS_LABEL3, _owner);
#line 918 "DialogSaveModule.vala.c"
}


static void xcls_dialogsavemodule_xcls_label3_class_init (Xcls_DialogSaveModuleXcls_Label3Class * klass) {
#line 152 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	xcls_dialogsavemodule_xcls_label3_parent_class = g_type_class_peek_parent (klass);
#line 152 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_type_class_add_private (klass, sizeof (Xcls_DialogSaveModuleXcls_Label3Private));
#line 152 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_dialogsavemodule_xcls_label3_finalize;
#line 929 "DialogSaveModule.vala.c"
}


static void xcls_dialogsavemodule_xcls_label3_instance_init (Xcls_DialogSaveModuleXcls_Label3 * self) {
#line 152 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->priv = XCLS_DIALOGSAVEMODULE_XCLS_LABEL3_GET_PRIVATE (self);
#line 936 "DialogSaveModule.vala.c"
}


static void xcls_dialogsavemodule_xcls_label3_finalize (GObject* obj) {
	Xcls_DialogSaveModuleXcls_Label3 * self;
#line 152 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_DIALOGSAVEMODULE_TYPE_XCLS_LABEL3, Xcls_DialogSaveModuleXcls_Label3);
#line 154 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->el);
#line 155 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->priv->_this);
#line 152 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	G_OBJECT_CLASS (xcls_dialogsavemodule_xcls_label3_parent_class)->finalize (obj);
#line 950 "DialogSaveModule.vala.c"
}


GType xcls_dialogsavemodule_xcls_label3_get_type (void) {
	static volatile gsize xcls_dialogsavemodule_xcls_label3_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_dialogsavemodule_xcls_label3_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_DialogSaveModuleXcls_Label3Class), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_dialogsavemodule_xcls_label3_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_DialogSaveModuleXcls_Label3), 0, (GInstanceInitFunc) xcls_dialogsavemodule_xcls_label3_instance_init, NULL };
		GType xcls_dialogsavemodule_xcls_label3_type_id;
		xcls_dialogsavemodule_xcls_label3_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_DialogSaveModuleXcls_Label3", &g_define_type_info, 0);
		g_once_init_leave (&xcls_dialogsavemodule_xcls_label3_type_id__volatile, xcls_dialogsavemodule_xcls_label3_type_id);
	}
	return xcls_dialogsavemodule_xcls_label3_type_id__volatile;
}


Xcls_DialogSaveModuleXcls_name* xcls_dialogsavemodule_xcls_name_construct (GType object_type, Xcls_DialogSaveModule* _owner) {
	Xcls_DialogSaveModuleXcls_name * self = NULL;
	Xcls_DialogSaveModule* _tmp0_;
	Xcls_DialogSaveModule* _tmp1_;
	Xcls_DialogSaveModule* _tmp2_;
	Xcls_DialogSaveModuleXcls_name* _tmp3_;
	GtkEntry* _tmp4_;
#line 186 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 186 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self = (Xcls_DialogSaveModuleXcls_name*) g_object_new (object_type, NULL);
#line 188 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp0_ = _owner;
#line 188 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 188 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->priv->_this);
#line 188 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->priv->_this = _tmp1_;
#line 189 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp2_ = self->priv->_this;
#line 189 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp3_ = _g_object_ref0 (self);
#line 189 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (_tmp2_->name);
#line 189 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp2_->name = _tmp3_;
#line 190 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp4_ = (GtkEntry*) gtk_entry_new ();
#line 190 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_object_ref_sink (_tmp4_);
#line 190 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->el);
#line 190 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->el = _tmp4_;
#line 186 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	return self;
#line 1003 "DialogSaveModule.vala.c"
}


Xcls_DialogSaveModuleXcls_name* xcls_dialogsavemodule_xcls_name_new (Xcls_DialogSaveModule* _owner) {
#line 186 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	return xcls_dialogsavemodule_xcls_name_construct (XCLS_DIALOGSAVEMODULE_TYPE_XCLS_NAME, _owner);
#line 1010 "DialogSaveModule.vala.c"
}


static void xcls_dialogsavemodule_xcls_name_class_init (Xcls_DialogSaveModuleXcls_nameClass * klass) {
#line 177 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	xcls_dialogsavemodule_xcls_name_parent_class = g_type_class_peek_parent (klass);
#line 177 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_type_class_add_private (klass, sizeof (Xcls_DialogSaveModuleXcls_namePrivate));
#line 177 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_dialogsavemodule_xcls_name_finalize;
#line 1021 "DialogSaveModule.vala.c"
}


static void xcls_dialogsavemodule_xcls_name_instance_init (Xcls_DialogSaveModuleXcls_name * self) {
#line 177 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->priv = XCLS_DIALOGSAVEMODULE_XCLS_NAME_GET_PRIVATE (self);
#line 1028 "DialogSaveModule.vala.c"
}


static void xcls_dialogsavemodule_xcls_name_finalize (GObject* obj) {
	Xcls_DialogSaveModuleXcls_name * self;
#line 177 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_DIALOGSAVEMODULE_TYPE_XCLS_NAME, Xcls_DialogSaveModuleXcls_name);
#line 179 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->el);
#line 180 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->priv->_this);
#line 177 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	G_OBJECT_CLASS (xcls_dialogsavemodule_xcls_name_parent_class)->finalize (obj);
#line 1042 "DialogSaveModule.vala.c"
}


GType xcls_dialogsavemodule_xcls_name_get_type (void) {
	static volatile gsize xcls_dialogsavemodule_xcls_name_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_dialogsavemodule_xcls_name_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_DialogSaveModuleXcls_nameClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_dialogsavemodule_xcls_name_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_DialogSaveModuleXcls_name), 0, (GInstanceInitFunc) xcls_dialogsavemodule_xcls_name_instance_init, NULL };
		GType xcls_dialogsavemodule_xcls_name_type_id;
		xcls_dialogsavemodule_xcls_name_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_DialogSaveModuleXcls_name", &g_define_type_info, 0);
		g_once_init_leave (&xcls_dialogsavemodule_xcls_name_type_id__volatile, xcls_dialogsavemodule_xcls_name_type_id);
	}
	return xcls_dialogsavemodule_xcls_name_type_id__volatile;
}


Xcls_DialogSaveModuleXcls_Button5* xcls_dialogsavemodule_xcls_button5_construct (GType object_type, Xcls_DialogSaveModule* _owner) {
	Xcls_DialogSaveModuleXcls_Button5 * self = NULL;
	Xcls_DialogSaveModule* _tmp0_;
	Xcls_DialogSaveModule* _tmp1_;
	GtkButton* _tmp2_;
	GtkButton* _tmp3_;
#line 210 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 210 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self = (Xcls_DialogSaveModuleXcls_Button5*) g_object_new (object_type, NULL);
#line 212 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp0_ = _owner;
#line 212 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 212 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->priv->_this);
#line 212 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->priv->_this = _tmp1_;
#line 213 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp2_ = (GtkButton*) gtk_button_new ();
#line 213 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_object_ref_sink (_tmp2_);
#line 213 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->el);
#line 213 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->el = _tmp2_;
#line 218 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp3_ = self->el;
#line 218 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	gtk_button_set_label (_tmp3_, "Cancel");
#line 210 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	return self;
#line 1090 "DialogSaveModule.vala.c"
}


Xcls_DialogSaveModuleXcls_Button5* xcls_dialogsavemodule_xcls_button5_new (Xcls_DialogSaveModule* _owner) {
#line 210 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	return xcls_dialogsavemodule_xcls_button5_construct (XCLS_DIALOGSAVEMODULE_TYPE_XCLS_BUTTON5, _owner);
#line 1097 "DialogSaveModule.vala.c"
}


static void xcls_dialogsavemodule_xcls_button5_class_init (Xcls_DialogSaveModuleXcls_Button5Class * klass) {
#line 201 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	xcls_dialogsavemodule_xcls_button5_parent_class = g_type_class_peek_parent (klass);
#line 201 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_type_class_add_private (klass, sizeof (Xcls_DialogSaveModuleXcls_Button5Private));
#line 201 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_dialogsavemodule_xcls_button5_finalize;
#line 1108 "DialogSaveModule.vala.c"
}


static void xcls_dialogsavemodule_xcls_button5_instance_init (Xcls_DialogSaveModuleXcls_Button5 * self) {
#line 201 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->priv = XCLS_DIALOGSAVEMODULE_XCLS_BUTTON5_GET_PRIVATE (self);
#line 1115 "DialogSaveModule.vala.c"
}


static void xcls_dialogsavemodule_xcls_button5_finalize (GObject* obj) {
	Xcls_DialogSaveModuleXcls_Button5 * self;
#line 201 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_DIALOGSAVEMODULE_TYPE_XCLS_BUTTON5, Xcls_DialogSaveModuleXcls_Button5);
#line 203 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->el);
#line 204 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->priv->_this);
#line 201 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	G_OBJECT_CLASS (xcls_dialogsavemodule_xcls_button5_parent_class)->finalize (obj);
#line 1129 "DialogSaveModule.vala.c"
}


GType xcls_dialogsavemodule_xcls_button5_get_type (void) {
	static volatile gsize xcls_dialogsavemodule_xcls_button5_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_dialogsavemodule_xcls_button5_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_DialogSaveModuleXcls_Button5Class), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_dialogsavemodule_xcls_button5_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_DialogSaveModuleXcls_Button5), 0, (GInstanceInitFunc) xcls_dialogsavemodule_xcls_button5_instance_init, NULL };
		GType xcls_dialogsavemodule_xcls_button5_type_id;
		xcls_dialogsavemodule_xcls_button5_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_DialogSaveModuleXcls_Button5", &g_define_type_info, 0);
		g_once_init_leave (&xcls_dialogsavemodule_xcls_button5_type_id__volatile, xcls_dialogsavemodule_xcls_button5_type_id);
	}
	return xcls_dialogsavemodule_xcls_button5_type_id__volatile;
}


Xcls_DialogSaveModuleXcls_Button6* xcls_dialogsavemodule_xcls_button6_construct (GType object_type, Xcls_DialogSaveModule* _owner) {
	Xcls_DialogSaveModuleXcls_Button6 * self = NULL;
	Xcls_DialogSaveModule* _tmp0_;
	Xcls_DialogSaveModule* _tmp1_;
	GtkButton* _tmp2_;
	GtkButton* _tmp3_;
#line 234 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 234 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self = (Xcls_DialogSaveModuleXcls_Button6*) g_object_new (object_type, NULL);
#line 236 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp0_ = _owner;
#line 236 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 236 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->priv->_this);
#line 236 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->priv->_this = _tmp1_;
#line 237 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp2_ = (GtkButton*) gtk_button_new ();
#line 237 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_object_ref_sink (_tmp2_);
#line 237 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->el);
#line 237 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->el = _tmp2_;
#line 242 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_tmp3_ = self->el;
#line 242 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	gtk_button_set_label (_tmp3_, "OK");
#line 234 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	return self;
#line 1177 "DialogSaveModule.vala.c"
}


Xcls_DialogSaveModuleXcls_Button6* xcls_dialogsavemodule_xcls_button6_new (Xcls_DialogSaveModule* _owner) {
#line 234 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	return xcls_dialogsavemodule_xcls_button6_construct (XCLS_DIALOGSAVEMODULE_TYPE_XCLS_BUTTON6, _owner);
#line 1184 "DialogSaveModule.vala.c"
}


static void xcls_dialogsavemodule_xcls_button6_class_init (Xcls_DialogSaveModuleXcls_Button6Class * klass) {
#line 225 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	xcls_dialogsavemodule_xcls_button6_parent_class = g_type_class_peek_parent (klass);
#line 225 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_type_class_add_private (klass, sizeof (Xcls_DialogSaveModuleXcls_Button6Private));
#line 225 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_dialogsavemodule_xcls_button6_finalize;
#line 1195 "DialogSaveModule.vala.c"
}


static void xcls_dialogsavemodule_xcls_button6_instance_init (Xcls_DialogSaveModuleXcls_Button6 * self) {
#line 225 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->priv = XCLS_DIALOGSAVEMODULE_XCLS_BUTTON6_GET_PRIVATE (self);
#line 1202 "DialogSaveModule.vala.c"
}


static void xcls_dialogsavemodule_xcls_button6_finalize (GObject* obj) {
	Xcls_DialogSaveModuleXcls_Button6 * self;
#line 225 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_DIALOGSAVEMODULE_TYPE_XCLS_BUTTON6, Xcls_DialogSaveModuleXcls_Button6);
#line 227 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->el);
#line 228 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->priv->_this);
#line 225 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	G_OBJECT_CLASS (xcls_dialogsavemodule_xcls_button6_parent_class)->finalize (obj);
#line 1216 "DialogSaveModule.vala.c"
}


GType xcls_dialogsavemodule_xcls_button6_get_type (void) {
	static volatile gsize xcls_dialogsavemodule_xcls_button6_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_dialogsavemodule_xcls_button6_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_DialogSaveModuleXcls_Button6Class), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_dialogsavemodule_xcls_button6_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_DialogSaveModuleXcls_Button6), 0, (GInstanceInitFunc) xcls_dialogsavemodule_xcls_button6_instance_init, NULL };
		GType xcls_dialogsavemodule_xcls_button6_type_id;
		xcls_dialogsavemodule_xcls_button6_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_DialogSaveModuleXcls_Button6", &g_define_type_info, 0);
		g_once_init_leave (&xcls_dialogsavemodule_xcls_button6_type_id__volatile, xcls_dialogsavemodule_xcls_button6_type_id);
	}
	return xcls_dialogsavemodule_xcls_button6_type_id__volatile;
}


static void xcls_dialogsavemodule_class_init (Xcls_DialogSaveModuleClass * klass) {
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	xcls_dialogsavemodule_parent_class = g_type_class_peek_parent (klass);
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	g_type_class_add_private (klass, sizeof (Xcls_DialogSaveModulePrivate));
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_dialogsavemodule_finalize;
#line 1239 "DialogSaveModule.vala.c"
}


static void xcls_dialogsavemodule_instance_init (Xcls_DialogSaveModule * self) {
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self->priv = XCLS_DIALOGSAVEMODULE_GET_PRIVATE (self);
#line 1246 "DialogSaveModule.vala.c"
}


static void xcls_dialogsavemodule_finalize (GObject* obj) {
	Xcls_DialogSaveModule * self;
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_XCLS_DIALOGSAVEMODULE, Xcls_DialogSaveModule);
#line 22 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->el);
#line 23 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->priv->_this);
#line 32 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->name);
#line 35 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->data);
#line 36 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	_g_object_unref0 (self->project);
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/DialogSaveModule.vala"
	G_OBJECT_CLASS (xcls_dialogsavemodule_parent_class)->finalize (obj);
#line 1266 "DialogSaveModule.vala.c"
}


GType xcls_dialogsavemodule_get_type (void) {
	static volatile gsize xcls_dialogsavemodule_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_dialogsavemodule_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_DialogSaveModuleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_dialogsavemodule_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_DialogSaveModule), 0, (GInstanceInitFunc) xcls_dialogsavemodule_instance_init, NULL };
		GType xcls_dialogsavemodule_type_id;
		xcls_dialogsavemodule_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_DialogSaveModule", &g_define_type_info, 0);
		g_once_init_leave (&xcls_dialogsavemodule_type_id__volatile, xcls_dialogsavemodule_type_id);
	}
	return xcls_dialogsavemodule_type_id__volatile;
}



