/* DialogTemplateSelect.vala.c generated by valac 0.20.1, the Vala compiler
 * generated from DialogTemplateSelect.vala, do not modify */

/* -- to compile
valac  --pkg gio-2.0  --pkg posix  --pkg gtk+-3.0 --pkg libnotify --pkg gtksourceview-3.0  --pkg  libwnck-3.0 \
    /tmp/DialogTemplateSelect.vala  -o /tmp/DialogTemplateSelect
*/
/* -- to test class
static int main (string[] args) {
    Gtk.init (ref args);
    new Xcls_DialogTemplateSelect();
    DialogTemplateSelect.show_all();
     Gtk.main ();
    return 0;
}
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_XCLS_DIALOGTEMPLATESELECT (xcls_dialogtemplateselect_get_type ())
#define XCLS_DIALOGTEMPLATESELECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_XCLS_DIALOGTEMPLATESELECT, Xcls_DialogTemplateSelect))
#define XCLS_DIALOGTEMPLATESELECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_XCLS_DIALOGTEMPLATESELECT, Xcls_DialogTemplateSelectClass))
#define IS_XCLS_DIALOGTEMPLATESELECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_XCLS_DIALOGTEMPLATESELECT))
#define IS_XCLS_DIALOGTEMPLATESELECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_XCLS_DIALOGTEMPLATESELECT))
#define XCLS_DIALOGTEMPLATESELECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_XCLS_DIALOGTEMPLATESELECT, Xcls_DialogTemplateSelectClass))

typedef struct _Xcls_DialogTemplateSelect Xcls_DialogTemplateSelect;
typedef struct _Xcls_DialogTemplateSelectClass Xcls_DialogTemplateSelectClass;
typedef struct _Xcls_DialogTemplateSelectPrivate Xcls_DialogTemplateSelectPrivate;

#define XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_COMBO (xcls_dialogtemplateselect_xcls_combo_get_type ())
#define XCLS_DIALOGTEMPLATESELECT_XCLS_COMBO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_COMBO, Xcls_DialogTemplateSelectXcls_combo))
#define XCLS_DIALOGTEMPLATESELECT_XCLS_COMBO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_COMBO, Xcls_DialogTemplateSelectXcls_comboClass))
#define XCLS_DIALOGTEMPLATESELECT_IS_XCLS_COMBO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_COMBO))
#define XCLS_DIALOGTEMPLATESELECT_IS_XCLS_COMBO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_COMBO))
#define XCLS_DIALOGTEMPLATESELECT_XCLS_COMBO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_COMBO, Xcls_DialogTemplateSelectXcls_comboClass))

typedef struct _Xcls_DialogTemplateSelectXcls_combo Xcls_DialogTemplateSelectXcls_combo;
typedef struct _Xcls_DialogTemplateSelectXcls_comboClass Xcls_DialogTemplateSelectXcls_comboClass;

#define XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_CELLRENDERER (xcls_dialogtemplateselect_xcls_cellrenderer_get_type ())
#define XCLS_DIALOGTEMPLATESELECT_XCLS_CELLRENDERER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_CELLRENDERER, Xcls_DialogTemplateSelectXcls_cellrenderer))
#define XCLS_DIALOGTEMPLATESELECT_XCLS_CELLRENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_CELLRENDERER, Xcls_DialogTemplateSelectXcls_cellrendererClass))
#define XCLS_DIALOGTEMPLATESELECT_IS_XCLS_CELLRENDERER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_CELLRENDERER))
#define XCLS_DIALOGTEMPLATESELECT_IS_XCLS_CELLRENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_CELLRENDERER))
#define XCLS_DIALOGTEMPLATESELECT_XCLS_CELLRENDERER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_CELLRENDERER, Xcls_DialogTemplateSelectXcls_cellrendererClass))

typedef struct _Xcls_DialogTemplateSelectXcls_cellrenderer Xcls_DialogTemplateSelectXcls_cellrenderer;
typedef struct _Xcls_DialogTemplateSelectXcls_cellrendererClass Xcls_DialogTemplateSelectXcls_cellrendererClass;

#define XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_MODEL (xcls_dialogtemplateselect_xcls_model_get_type ())
#define XCLS_DIALOGTEMPLATESELECT_XCLS_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_MODEL, Xcls_DialogTemplateSelectXcls_model))
#define XCLS_DIALOGTEMPLATESELECT_XCLS_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_MODEL, Xcls_DialogTemplateSelectXcls_modelClass))
#define XCLS_DIALOGTEMPLATESELECT_IS_XCLS_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_MODEL))
#define XCLS_DIALOGTEMPLATESELECT_IS_XCLS_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_MODEL))
#define XCLS_DIALOGTEMPLATESELECT_XCLS_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_MODEL, Xcls_DialogTemplateSelectXcls_modelClass))

typedef struct _Xcls_DialogTemplateSelectXcls_model Xcls_DialogTemplateSelectXcls_model;
typedef struct _Xcls_DialogTemplateSelectXcls_modelClass Xcls_DialogTemplateSelectXcls_modelClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_VBOX2 (xcls_dialogtemplateselect_xcls_vbox2_get_type ())
#define XCLS_DIALOGTEMPLATESELECT_XCLS_VBOX2(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_VBOX2, Xcls_DialogTemplateSelectXcls_VBox2))
#define XCLS_DIALOGTEMPLATESELECT_XCLS_VBOX2_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_VBOX2, Xcls_DialogTemplateSelectXcls_VBox2Class))
#define XCLS_DIALOGTEMPLATESELECT_IS_XCLS_VBOX2(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_VBOX2))
#define XCLS_DIALOGTEMPLATESELECT_IS_XCLS_VBOX2_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_VBOX2))
#define XCLS_DIALOGTEMPLATESELECT_XCLS_VBOX2_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_VBOX2, Xcls_DialogTemplateSelectXcls_VBox2Class))

typedef struct _Xcls_DialogTemplateSelectXcls_VBox2 Xcls_DialogTemplateSelectXcls_VBox2;
typedef struct _Xcls_DialogTemplateSelectXcls_VBox2Class Xcls_DialogTemplateSelectXcls_VBox2Class;
typedef struct _Xcls_DialogTemplateSelectXcls_VBox2Private Xcls_DialogTemplateSelectXcls_VBox2Private;

#define XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_BUTTON8 (xcls_dialogtemplateselect_xcls_button8_get_type ())
#define XCLS_DIALOGTEMPLATESELECT_XCLS_BUTTON8(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_BUTTON8, Xcls_DialogTemplateSelectXcls_Button8))
#define XCLS_DIALOGTEMPLATESELECT_XCLS_BUTTON8_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_BUTTON8, Xcls_DialogTemplateSelectXcls_Button8Class))
#define XCLS_DIALOGTEMPLATESELECT_IS_XCLS_BUTTON8(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_BUTTON8))
#define XCLS_DIALOGTEMPLATESELECT_IS_XCLS_BUTTON8_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_BUTTON8))
#define XCLS_DIALOGTEMPLATESELECT_XCLS_BUTTON8_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_BUTTON8, Xcls_DialogTemplateSelectXcls_Button8Class))

typedef struct _Xcls_DialogTemplateSelectXcls_Button8 Xcls_DialogTemplateSelectXcls_Button8;
typedef struct _Xcls_DialogTemplateSelectXcls_Button8Class Xcls_DialogTemplateSelectXcls_Button8Class;
typedef struct _Xcls_DialogTemplateSelectXcls_Button8Private Xcls_DialogTemplateSelectXcls_Button8Private;

#define PALETE_TYPE_PALETE (palete_palete_get_type ())
#define PALETE_PALETE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PALETE_TYPE_PALETE, PaletePalete))
#define PALETE_PALETE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PALETE_TYPE_PALETE, PaletePaleteClass))
#define PALETE_IS_PALETE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PALETE_TYPE_PALETE))
#define PALETE_IS_PALETE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PALETE_TYPE_PALETE))
#define PALETE_PALETE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PALETE_TYPE_PALETE, PaletePaleteClass))

typedef struct _PaletePalete PaletePalete;
typedef struct _PaletePaleteClass PaletePaleteClass;

#define JS_RENDER_TYPE_NODE (js_render_node_get_type ())
#define JS_RENDER_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JS_RENDER_TYPE_NODE, JsRenderNode))
#define JS_RENDER_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JS_RENDER_TYPE_NODE, JsRenderNodeClass))
#define JS_RENDER_IS_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JS_RENDER_TYPE_NODE))
#define JS_RENDER_IS_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JS_RENDER_TYPE_NODE))
#define JS_RENDER_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JS_RENDER_TYPE_NODE, JsRenderNodeClass))

typedef struct _JsRenderNode JsRenderNode;
typedef struct _JsRenderNodeClass JsRenderNodeClass;
#define __g_list_free__g_free0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_free0_ (var), NULL)))
typedef struct _Xcls_DialogTemplateSelectXcls_comboPrivate Xcls_DialogTemplateSelectXcls_comboPrivate;

#define XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_HBOX3 (xcls_dialogtemplateselect_xcls_hbox3_get_type ())
#define XCLS_DIALOGTEMPLATESELECT_XCLS_HBOX3(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_HBOX3, Xcls_DialogTemplateSelectXcls_HBox3))
#define XCLS_DIALOGTEMPLATESELECT_XCLS_HBOX3_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_HBOX3, Xcls_DialogTemplateSelectXcls_HBox3Class))
#define XCLS_DIALOGTEMPLATESELECT_IS_XCLS_HBOX3(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_HBOX3))
#define XCLS_DIALOGTEMPLATESELECT_IS_XCLS_HBOX3_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_HBOX3))
#define XCLS_DIALOGTEMPLATESELECT_XCLS_HBOX3_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_HBOX3, Xcls_DialogTemplateSelectXcls_HBox3Class))

typedef struct _Xcls_DialogTemplateSelectXcls_HBox3 Xcls_DialogTemplateSelectXcls_HBox3;
typedef struct _Xcls_DialogTemplateSelectXcls_HBox3Class Xcls_DialogTemplateSelectXcls_HBox3Class;
typedef struct _Xcls_DialogTemplateSelectXcls_HBox3Private Xcls_DialogTemplateSelectXcls_HBox3Private;

#define XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_LABEL4 (xcls_dialogtemplateselect_xcls_label4_get_type ())
#define XCLS_DIALOGTEMPLATESELECT_XCLS_LABEL4(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_LABEL4, Xcls_DialogTemplateSelectXcls_Label4))
#define XCLS_DIALOGTEMPLATESELECT_XCLS_LABEL4_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_LABEL4, Xcls_DialogTemplateSelectXcls_Label4Class))
#define XCLS_DIALOGTEMPLATESELECT_IS_XCLS_LABEL4(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_LABEL4))
#define XCLS_DIALOGTEMPLATESELECT_IS_XCLS_LABEL4_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_LABEL4))
#define XCLS_DIALOGTEMPLATESELECT_XCLS_LABEL4_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_LABEL4, Xcls_DialogTemplateSelectXcls_Label4Class))

typedef struct _Xcls_DialogTemplateSelectXcls_Label4 Xcls_DialogTemplateSelectXcls_Label4;
typedef struct _Xcls_DialogTemplateSelectXcls_Label4Class Xcls_DialogTemplateSelectXcls_Label4Class;
typedef struct _Xcls_DialogTemplateSelectXcls_Label4Private Xcls_DialogTemplateSelectXcls_Label4Private;
typedef struct _Xcls_DialogTemplateSelectXcls_cellrendererPrivate Xcls_DialogTemplateSelectXcls_cellrendererPrivate;
typedef struct _Xcls_DialogTemplateSelectXcls_modelPrivate Xcls_DialogTemplateSelectXcls_modelPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _Xcls_DialogTemplateSelect {
	GObject parent_instance;
	Xcls_DialogTemplateSelectPrivate * priv;
	GtkDialog* el;
	Xcls_DialogTemplateSelectXcls_combo* combo;
	Xcls_DialogTemplateSelectXcls_cellrenderer* cellrenderer;
	Xcls_DialogTemplateSelectXcls_model* model;
};

struct _Xcls_DialogTemplateSelectClass {
	GObjectClass parent_class;
};

struct _Xcls_DialogTemplateSelectPrivate {
	Xcls_DialogTemplateSelect* _this;
};

struct _Xcls_DialogTemplateSelectXcls_VBox2 {
	GObject parent_instance;
	Xcls_DialogTemplateSelectXcls_VBox2Private * priv;
	GtkVBox* el;
};

struct _Xcls_DialogTemplateSelectXcls_VBox2Class {
	GObjectClass parent_class;
};

struct _Xcls_DialogTemplateSelectXcls_Button8 {
	GObject parent_instance;
	Xcls_DialogTemplateSelectXcls_Button8Private * priv;
	GtkButton* el;
};

struct _Xcls_DialogTemplateSelectXcls_Button8Class {
	GObjectClass parent_class;
};

struct _Xcls_DialogTemplateSelectXcls_combo {
	GObject parent_instance;
	Xcls_DialogTemplateSelectXcls_comboPrivate * priv;
	GtkComboBox* el;
};

struct _Xcls_DialogTemplateSelectXcls_comboClass {
	GObjectClass parent_class;
};

struct _Xcls_DialogTemplateSelectXcls_VBox2Private {
	Xcls_DialogTemplateSelect* _this;
};

struct _Xcls_DialogTemplateSelectXcls_HBox3 {
	GObject parent_instance;
	Xcls_DialogTemplateSelectXcls_HBox3Private * priv;
	GtkHBox* el;
};

struct _Xcls_DialogTemplateSelectXcls_HBox3Class {
	GObjectClass parent_class;
};

struct _Xcls_DialogTemplateSelectXcls_HBox3Private {
	Xcls_DialogTemplateSelect* _this;
};

struct _Xcls_DialogTemplateSelectXcls_Label4 {
	GObject parent_instance;
	Xcls_DialogTemplateSelectXcls_Label4Private * priv;
	GtkLabel* el;
};

struct _Xcls_DialogTemplateSelectXcls_Label4Class {
	GObjectClass parent_class;
};

struct _Xcls_DialogTemplateSelectXcls_Label4Private {
	Xcls_DialogTemplateSelect* _this;
};

struct _Xcls_DialogTemplateSelectXcls_comboPrivate {
	Xcls_DialogTemplateSelect* _this;
};

struct _Xcls_DialogTemplateSelectXcls_cellrenderer {
	GObject parent_instance;
	Xcls_DialogTemplateSelectXcls_cellrendererPrivate * priv;
	GtkCellRendererText* el;
};

struct _Xcls_DialogTemplateSelectXcls_cellrendererClass {
	GObjectClass parent_class;
};

struct _Xcls_DialogTemplateSelectXcls_model {
	GObject parent_instance;
	Xcls_DialogTemplateSelectXcls_modelPrivate * priv;
	GtkListStore* el;
};

struct _Xcls_DialogTemplateSelectXcls_modelClass {
	GObjectClass parent_class;
};

struct _Xcls_DialogTemplateSelectXcls_cellrendererPrivate {
	Xcls_DialogTemplateSelect* _this;
};

struct _Xcls_DialogTemplateSelectXcls_modelPrivate {
	Xcls_DialogTemplateSelect* _this;
};

struct _Xcls_DialogTemplateSelectXcls_Button8Private {
	Xcls_DialogTemplateSelect* _this;
};


extern Xcls_DialogTemplateSelect* DialogTemplateSelect;
Xcls_DialogTemplateSelect* DialogTemplateSelect = NULL;
static gpointer xcls_dialogtemplateselect_parent_class = NULL;
static gpointer xcls_dialogtemplateselect_xcls_vbox2_parent_class = NULL;
static gpointer xcls_dialogtemplateselect_xcls_hbox3_parent_class = NULL;
static gpointer xcls_dialogtemplateselect_xcls_label4_parent_class = NULL;
static gpointer xcls_dialogtemplateselect_xcls_combo_parent_class = NULL;
static gpointer xcls_dialogtemplateselect_xcls_cellrenderer_parent_class = NULL;
static gpointer xcls_dialogtemplateselect_xcls_model_parent_class = NULL;
static gpointer xcls_dialogtemplateselect_xcls_button8_parent_class = NULL;

GType xcls_dialogtemplateselect_get_type (void) G_GNUC_CONST;
GType xcls_dialogtemplateselect_xcls_combo_get_type (void) G_GNUC_CONST;
GType xcls_dialogtemplateselect_xcls_cellrenderer_get_type (void) G_GNUC_CONST;
GType xcls_dialogtemplateselect_xcls_model_get_type (void) G_GNUC_CONST;
#define XCLS_DIALOGTEMPLATESELECT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_XCLS_DIALOGTEMPLATESELECT, Xcls_DialogTemplateSelectPrivate))
enum  {
	XCLS_DIALOGTEMPLATESELECT_DUMMY_PROPERTY
};
Xcls_DialogTemplateSelect* xcls_dialogtemplateselect_new (void);
Xcls_DialogTemplateSelect* xcls_dialogtemplateselect_construct (GType object_type);
Xcls_DialogTemplateSelectXcls_VBox2* xcls_dialogtemplateselect_xcls_vbox2_new (Xcls_DialogTemplateSelect* _owner);
Xcls_DialogTemplateSelectXcls_VBox2* xcls_dialogtemplateselect_xcls_vbox2_construct (GType object_type, Xcls_DialogTemplateSelect* _owner);
GType xcls_dialogtemplateselect_xcls_vbox2_get_type (void) G_GNUC_CONST;
Xcls_DialogTemplateSelectXcls_Button8* xcls_dialogtemplateselect_xcls_button8_new (Xcls_DialogTemplateSelect* _owner);
Xcls_DialogTemplateSelectXcls_Button8* xcls_dialogtemplateselect_xcls_button8_construct (GType object_type, Xcls_DialogTemplateSelect* _owner);
GType xcls_dialogtemplateselect_xcls_button8_get_type (void) G_GNUC_CONST;
static gboolean __lambda39_ (Xcls_DialogTemplateSelect* self, GtkWidget* _self_, GdkEventAny* event);
static gboolean ___lambda39__gtk_widget_delete_event (GtkWidget* _sender, GdkEventAny* event, gpointer self);
GType palete_palete_get_type (void) G_GNUC_CONST;
GType js_render_node_get_type (void) G_GNUC_CONST;
JsRenderNode* xcls_dialogtemplateselect_show (Xcls_DialogTemplateSelect* self, PaletePalete* pal, JsRenderNode* node);
GList* palete_palete_listTemplates (PaletePalete* self, JsRenderNode* node);
static void _g_free0_ (gpointer var);
static void _g_list_free__g_free0_ (GList* self);
void xcls_dialogtemplateselect_xcls_model_loadData (Xcls_DialogTemplateSelectXcls_model* self, GList* data);
JsRenderNode* palete_palete_loadTemplate (PaletePalete* self, const gchar* path);
#define XCLS_DIALOGTEMPLATESELECT_XCLS_VBOX2_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_VBOX2, Xcls_DialogTemplateSelectXcls_VBox2Private))
enum  {
	XCLS_DIALOGTEMPLATESELECT_XCLS_VBOX2_DUMMY_PROPERTY
};
Xcls_DialogTemplateSelectXcls_HBox3* xcls_dialogtemplateselect_xcls_hbox3_new (Xcls_DialogTemplateSelect* _owner);
Xcls_DialogTemplateSelectXcls_HBox3* xcls_dialogtemplateselect_xcls_hbox3_construct (GType object_type, Xcls_DialogTemplateSelect* _owner);
GType xcls_dialogtemplateselect_xcls_hbox3_get_type (void) G_GNUC_CONST;
static void xcls_dialogtemplateselect_xcls_vbox2_finalize (GObject* obj);
#define XCLS_DIALOGTEMPLATESELECT_XCLS_HBOX3_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_HBOX3, Xcls_DialogTemplateSelectXcls_HBox3Private))
enum  {
	XCLS_DIALOGTEMPLATESELECT_XCLS_HBOX3_DUMMY_PROPERTY
};
Xcls_DialogTemplateSelectXcls_Label4* xcls_dialogtemplateselect_xcls_label4_new (Xcls_DialogTemplateSelect* _owner);
Xcls_DialogTemplateSelectXcls_Label4* xcls_dialogtemplateselect_xcls_label4_construct (GType object_type, Xcls_DialogTemplateSelect* _owner);
GType xcls_dialogtemplateselect_xcls_label4_get_type (void) G_GNUC_CONST;
Xcls_DialogTemplateSelectXcls_combo* xcls_dialogtemplateselect_xcls_combo_new (Xcls_DialogTemplateSelect* _owner);
Xcls_DialogTemplateSelectXcls_combo* xcls_dialogtemplateselect_xcls_combo_construct (GType object_type, Xcls_DialogTemplateSelect* _owner);
static void xcls_dialogtemplateselect_xcls_hbox3_finalize (GObject* obj);
#define XCLS_DIALOGTEMPLATESELECT_XCLS_LABEL4_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_LABEL4, Xcls_DialogTemplateSelectXcls_Label4Private))
enum  {
	XCLS_DIALOGTEMPLATESELECT_XCLS_LABEL4_DUMMY_PROPERTY
};
static void xcls_dialogtemplateselect_xcls_label4_finalize (GObject* obj);
#define XCLS_DIALOGTEMPLATESELECT_XCLS_COMBO_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_COMBO, Xcls_DialogTemplateSelectXcls_comboPrivate))
enum  {
	XCLS_DIALOGTEMPLATESELECT_XCLS_COMBO_DUMMY_PROPERTY
};
Xcls_DialogTemplateSelectXcls_cellrenderer* xcls_dialogtemplateselect_xcls_cellrenderer_new (Xcls_DialogTemplateSelect* _owner);
Xcls_DialogTemplateSelectXcls_cellrenderer* xcls_dialogtemplateselect_xcls_cellrenderer_construct (GType object_type, Xcls_DialogTemplateSelect* _owner);
Xcls_DialogTemplateSelectXcls_model* xcls_dialogtemplateselect_xcls_model_new (Xcls_DialogTemplateSelect* _owner);
Xcls_DialogTemplateSelectXcls_model* xcls_dialogtemplateselect_xcls_model_construct (GType object_type, Xcls_DialogTemplateSelect* _owner);
static void xcls_dialogtemplateselect_xcls_combo_finalize (GObject* obj);
#define XCLS_DIALOGTEMPLATESELECT_XCLS_CELLRENDERER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_CELLRENDERER, Xcls_DialogTemplateSelectXcls_cellrendererPrivate))
enum  {
	XCLS_DIALOGTEMPLATESELECT_XCLS_CELLRENDERER_DUMMY_PROPERTY
};
static void xcls_dialogtemplateselect_xcls_cellrenderer_finalize (GObject* obj);
#define XCLS_DIALOGTEMPLATESELECT_XCLS_MODEL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_MODEL, Xcls_DialogTemplateSelectXcls_modelPrivate))
enum  {
	XCLS_DIALOGTEMPLATESELECT_XCLS_MODEL_DUMMY_PROPERTY
};
static void xcls_dialogtemplateselect_xcls_model_finalize (GObject* obj);
#define XCLS_DIALOGTEMPLATESELECT_XCLS_BUTTON8_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_BUTTON8, Xcls_DialogTemplateSelectXcls_Button8Private))
enum  {
	XCLS_DIALOGTEMPLATESELECT_XCLS_BUTTON8_DUMMY_PROPERTY
};
static void xcls_dialogtemplateselect_xcls_button8_finalize (GObject* obj);
static void xcls_dialogtemplateselect_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
#line 35 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return self ? g_object_ref (self) : NULL;
#line 346 "DialogTemplateSelect.vala.c"
}


static gboolean __lambda39_ (Xcls_DialogTemplateSelect* self, GtkWidget* _self_, GdkEventAny* event) {
	gboolean result = FALSE;
	GtkDialog* _tmp0_;
#line 52 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_return_val_if_fail (_self_ != NULL, FALSE);
#line 52 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 53 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp0_ = self->el;
#line 53 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_widget_hide ((GtkWidget*) _tmp0_);
#line 54 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	result = TRUE;
#line 54 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return result;
#line 365 "DialogTemplateSelect.vala.c"
}


static gboolean ___lambda39__gtk_widget_delete_event (GtkWidget* _sender, GdkEventAny* event, gpointer self) {
	gboolean result;
	result = __lambda39_ (self, _sender, event);
#line 52 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return result;
#line 374 "DialogTemplateSelect.vala.c"
}


Xcls_DialogTemplateSelect* xcls_dialogtemplateselect_construct (GType object_type) {
	Xcls_DialogTemplateSelect * self = NULL;
	GtkDialog* _tmp0_;
	Xcls_DialogTemplateSelect* _tmp1_;
	Xcls_DialogTemplateSelect* _tmp2_;
	GtkDialog* _tmp3_;
	GtkDialog* _tmp4_;
	GtkDialog* _tmp5_;
	Xcls_DialogTemplateSelect* _tmp6_;
	Xcls_DialogTemplateSelectXcls_VBox2* _tmp7_;
	Xcls_DialogTemplateSelectXcls_VBox2* child_0;
	GtkDialog* _tmp8_;
	GtkBox* _tmp9_ = NULL;
	GtkVBox* _tmp10_;
	Xcls_DialogTemplateSelect* _tmp11_;
	Xcls_DialogTemplateSelectXcls_Button8* _tmp12_;
	Xcls_DialogTemplateSelectXcls_Button8* child_1;
	GtkDialog* _tmp13_;
	GtkButton* _tmp14_;
	GtkDialog* _tmp15_;
#line 32 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self = (Xcls_DialogTemplateSelect*) g_object_new (object_type, NULL);
#line 34 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp0_ = (GtkDialog*) gtk_dialog_new ();
#line 34 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_object_ref_sink (_tmp0_);
#line 34 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->el);
#line 34 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->el = _tmp0_;
#line 35 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp1_ = _g_object_ref0 (self);
#line 35 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->priv->_this);
#line 35 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->priv->_this = _tmp1_;
#line 36 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp2_ = _g_object_ref0 (self);
#line 36 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (DialogTemplateSelect);
#line 36 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	DialogTemplateSelect = _tmp2_;
#line 41 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp3_ = self->el;
#line 41 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_object_set ((GtkWindow*) _tmp3_, "default-height", 200, NULL);
#line 42 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp4_ = self->el;
#line 42 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_object_set ((GtkWindow*) _tmp4_, "default-width", 400, NULL);
#line 43 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp5_ = self->el;
#line 43 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_window_set_modal ((GtkWindow*) _tmp5_, TRUE);
#line 44 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp6_ = self->priv->_this;
#line 44 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp7_ = xcls_dialogtemplateselect_xcls_vbox2_new (_tmp6_);
#line 44 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	child_0 = _tmp7_;
#line 45 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_object_ref ((GObject*) child_0);
#line 46 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp8_ = self->el;
#line 46 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp9_ = gtk_dialog_get_content_area (_tmp8_);
#line 46 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp10_ = child_0->el;
#line 46 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_container_add ((GtkContainer*) _tmp9_, (GtkWidget*) _tmp10_);
#line 47 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp11_ = self->priv->_this;
#line 47 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp12_ = xcls_dialogtemplateselect_xcls_button8_new (_tmp11_);
#line 47 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	child_1 = _tmp12_;
#line 48 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_object_ref ((GObject*) child_1);
#line 49 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp13_ = self->el;
#line 49 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp14_ = child_1->el;
#line 49 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_dialog_add_action_widget (_tmp13_, (GtkWidget*) _tmp14_, 0);
#line 52 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp15_ = self->el;
#line 52 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_signal_connect_object ((GtkWidget*) _tmp15_, "delete-event", (GCallback) ___lambda39__gtk_widget_delete_event, self, 0);
#line 32 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (child_1);
#line 32 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (child_0);
#line 32 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return self;
#line 472 "DialogTemplateSelect.vala.c"
}


Xcls_DialogTemplateSelect* xcls_dialogtemplateselect_new (void) {
#line 32 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return xcls_dialogtemplateselect_construct (TYPE_XCLS_DIALOGTEMPLATESELECT);
#line 479 "DialogTemplateSelect.vala.c"
}


static void _g_free0_ (gpointer var) {
#line 72 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	var = (g_free (var), NULL);
#line 486 "DialogTemplateSelect.vala.c"
}


static void _g_list_free__g_free0_ (GList* self) {
#line 72 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_list_foreach (self, (GFunc) _g_free0_, NULL);
#line 72 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_list_free (self);
#line 495 "DialogTemplateSelect.vala.c"
}


JsRenderNode* xcls_dialogtemplateselect_show (Xcls_DialogTemplateSelect* self, PaletePalete* pal, JsRenderNode* node) {
	JsRenderNode* result = NULL;
	PaletePalete* _tmp0_;
	JsRenderNode* _tmp1_;
	GList* _tmp2_ = NULL;
	GList* opts;
	GList* _tmp3_;
	guint _tmp4_ = 0U;
	Xcls_DialogTemplateSelect* _tmp7_;
	Xcls_DialogTemplateSelectXcls_model* _tmp8_;
	GList* _tmp9_;
	Xcls_DialogTemplateSelect* _tmp10_;
	Xcls_DialogTemplateSelectXcls_combo* _tmp11_;
	GtkComboBox* _tmp12_;
	GtkDialog* _tmp13_;
	GtkDialog* _tmp14_;
	GtkDialog* _tmp15_;
	Xcls_DialogTemplateSelect* _tmp16_;
	Xcls_DialogTemplateSelectXcls_combo* _tmp17_;
	GtkComboBox* _tmp18_;
	gint _tmp19_ = 0;
	gint ix;
	gint _tmp20_;
	PaletePalete* _tmp21_;
	GList* _tmp22_;
	gint _tmp23_;
	gconstpointer _tmp24_ = NULL;
	JsRenderNode* _tmp25_ = NULL;
#line 67 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 67 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_return_val_if_fail (pal != NULL, NULL);
#line 67 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_return_val_if_fail (node != NULL, NULL);
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp0_ = pal;
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp1_ = node;
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp2_ = palete_palete_listTemplates (_tmp0_, _tmp1_);
#line 70 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	opts = _tmp2_;
#line 71 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp3_ = opts;
#line 71 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp4_ = g_list_length (_tmp3_);
#line 71 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	if (_tmp4_ < ((guint) 1)) {
#line 547 "DialogTemplateSelect.vala.c"
		JsRenderNode* _tmp5_;
		JsRenderNode* _tmp6_;
#line 72 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
		_tmp5_ = node;
#line 72 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
		_tmp6_ = _g_object_ref0 (_tmp5_);
#line 72 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
		result = _tmp6_;
#line 72 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
		__g_list_free__g_free0_0 (opts);
#line 72 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
		return result;
#line 560 "DialogTemplateSelect.vala.c"
	}
#line 76 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp7_ = self->priv->_this;
#line 76 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp8_ = _tmp7_->model;
#line 76 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp9_ = opts;
#line 76 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	xcls_dialogtemplateselect_xcls_model_loadData (_tmp8_, _tmp9_);
#line 77 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp10_ = self->priv->_this;
#line 77 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp11_ = _tmp10_->combo;
#line 77 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp12_ = _tmp11_->el;
#line 77 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_combo_box_set_active (_tmp12_, 0);
#line 79 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp13_ = self->el;
#line 79 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp13_);
#line 80 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp14_ = self->el;
#line 80 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_dialog_run (_tmp14_);
#line 81 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp15_ = self->el;
#line 81 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_widget_hide ((GtkWidget*) _tmp15_);
#line 82 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp16_ = self->priv->_this;
#line 82 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp17_ = _tmp16_->combo;
#line 82 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp18_ = _tmp17_->el;
#line 82 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp19_ = gtk_combo_box_get_active (_tmp18_);
#line 82 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	ix = _tmp19_;
#line 83 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp20_ = ix;
#line 83 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	if (_tmp20_ < 1) {
#line 84 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
		result = NULL;
#line 84 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
		__g_list_free__g_free0_0 (opts);
#line 84 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
		return result;
#line 610 "DialogTemplateSelect.vala.c"
	}
#line 88 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp21_ = pal;
#line 88 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp22_ = opts;
#line 88 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp23_ = ix;
#line 88 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp24_ = g_list_nth_data (_tmp22_, (guint) _tmp23_);
#line 88 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp25_ = palete_palete_loadTemplate (_tmp21_, (const gchar*) _tmp24_);
#line 88 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	result = _tmp25_;
#line 88 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	__g_list_free__g_free0_0 (opts);
#line 88 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return result;
#line 628 "DialogTemplateSelect.vala.c"
}


Xcls_DialogTemplateSelectXcls_VBox2* xcls_dialogtemplateselect_xcls_vbox2_construct (GType object_type, Xcls_DialogTemplateSelect* _owner) {
	Xcls_DialogTemplateSelectXcls_VBox2 * self = NULL;
	GtkVBox* _tmp0_;
	Xcls_DialogTemplateSelect* _tmp1_;
	Xcls_DialogTemplateSelect* _tmp2_;
	Xcls_DialogTemplateSelect* _tmp3_;
	Xcls_DialogTemplateSelectXcls_HBox3* _tmp4_;
	Xcls_DialogTemplateSelectXcls_HBox3* child_0;
	GtkVBox* _tmp5_;
	GtkHBox* _tmp6_;
#line 114 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 114 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self = (Xcls_DialogTemplateSelectXcls_VBox2*) g_object_new (object_type, NULL);
#line 116 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp0_ = (GtkVBox*) gtk_vbox_new (TRUE, 0);
#line 116 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_object_ref_sink (_tmp0_);
#line 116 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->el);
#line 116 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->el = _tmp0_;
#line 117 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp1_ = _owner;
#line 117 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 117 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->priv->_this);
#line 117 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->priv->_this = _tmp2_;
#line 122 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp3_ = self->priv->_this;
#line 122 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp4_ = xcls_dialogtemplateselect_xcls_hbox3_new (_tmp3_);
#line 122 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	child_0 = _tmp4_;
#line 123 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_object_ref ((GObject*) child_0);
#line 124 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp5_ = self->el;
#line 124 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp6_ = child_0->el;
#line 124 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_box_pack_start ((GtkBox*) _tmp5_, (GtkWidget*) _tmp6_, FALSE, FALSE, (guint) 0);
#line 114 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (child_0);
#line 114 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return self;
#line 680 "DialogTemplateSelect.vala.c"
}


Xcls_DialogTemplateSelectXcls_VBox2* xcls_dialogtemplateselect_xcls_vbox2_new (Xcls_DialogTemplateSelect* _owner) {
#line 114 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return xcls_dialogtemplateselect_xcls_vbox2_construct (XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_VBOX2, _owner);
#line 687 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_vbox2_class_init (Xcls_DialogTemplateSelectXcls_VBox2Class * klass) {
#line 105 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	xcls_dialogtemplateselect_xcls_vbox2_parent_class = g_type_class_peek_parent (klass);
#line 105 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_type_class_add_private (klass, sizeof (Xcls_DialogTemplateSelectXcls_VBox2Private));
#line 105 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_dialogtemplateselect_xcls_vbox2_finalize;
#line 698 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_vbox2_instance_init (Xcls_DialogTemplateSelectXcls_VBox2 * self) {
#line 105 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->priv = XCLS_DIALOGTEMPLATESELECT_XCLS_VBOX2_GET_PRIVATE (self);
#line 705 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_vbox2_finalize (GObject* obj) {
	Xcls_DialogTemplateSelectXcls_VBox2 * self;
#line 105 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_VBOX2, Xcls_DialogTemplateSelectXcls_VBox2);
#line 107 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->el);
#line 108 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->priv->_this);
#line 105 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	G_OBJECT_CLASS (xcls_dialogtemplateselect_xcls_vbox2_parent_class)->finalize (obj);
#line 719 "DialogTemplateSelect.vala.c"
}


GType xcls_dialogtemplateselect_xcls_vbox2_get_type (void) {
	static volatile gsize xcls_dialogtemplateselect_xcls_vbox2_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_dialogtemplateselect_xcls_vbox2_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_DialogTemplateSelectXcls_VBox2Class), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_dialogtemplateselect_xcls_vbox2_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_DialogTemplateSelectXcls_VBox2), 0, (GInstanceInitFunc) xcls_dialogtemplateselect_xcls_vbox2_instance_init, NULL };
		GType xcls_dialogtemplateselect_xcls_vbox2_type_id;
		xcls_dialogtemplateselect_xcls_vbox2_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_DialogTemplateSelectXcls_VBox2", &g_define_type_info, 0);
		g_once_init_leave (&xcls_dialogtemplateselect_xcls_vbox2_type_id__volatile, xcls_dialogtemplateselect_xcls_vbox2_type_id);
	}
	return xcls_dialogtemplateselect_xcls_vbox2_type_id__volatile;
}


Xcls_DialogTemplateSelectXcls_HBox3* xcls_dialogtemplateselect_xcls_hbox3_construct (GType object_type, Xcls_DialogTemplateSelect* _owner) {
	Xcls_DialogTemplateSelectXcls_HBox3 * self = NULL;
	GtkHBox* _tmp0_;
	Xcls_DialogTemplateSelect* _tmp1_;
	Xcls_DialogTemplateSelect* _tmp2_;
	Xcls_DialogTemplateSelect* _tmp3_;
	Xcls_DialogTemplateSelectXcls_Label4* _tmp4_;
	Xcls_DialogTemplateSelectXcls_Label4* child_0;
	GtkHBox* _tmp5_;
	GtkLabel* _tmp6_;
	Xcls_DialogTemplateSelect* _tmp7_;
	Xcls_DialogTemplateSelectXcls_combo* _tmp8_;
	Xcls_DialogTemplateSelectXcls_combo* child_1;
	GtkHBox* _tmp9_;
	GtkComboBox* _tmp10_;
#line 152 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 152 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self = (Xcls_DialogTemplateSelectXcls_HBox3*) g_object_new (object_type, NULL);
#line 154 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp0_ = (GtkHBox*) gtk_hbox_new (TRUE, 0);
#line 154 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_object_ref_sink (_tmp0_);
#line 154 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->el);
#line 154 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->el = _tmp0_;
#line 155 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp1_ = _owner;
#line 155 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 155 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->priv->_this);
#line 155 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->priv->_this = _tmp2_;
#line 160 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp3_ = self->priv->_this;
#line 160 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp4_ = xcls_dialogtemplateselect_xcls_label4_new (_tmp3_);
#line 160 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	child_0 = _tmp4_;
#line 161 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_object_ref ((GObject*) child_0);
#line 162 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp5_ = self->el;
#line 162 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp6_ = child_0->el;
#line 162 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_box_pack_start ((GtkBox*) _tmp5_, (GtkWidget*) _tmp6_, FALSE, FALSE, (guint) 0);
#line 163 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp7_ = self->priv->_this;
#line 163 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp8_ = xcls_dialogtemplateselect_xcls_combo_new (_tmp7_);
#line 163 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	child_1 = _tmp8_;
#line 164 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_object_ref ((GObject*) child_1);
#line 165 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp9_ = self->el;
#line 165 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp10_ = child_1->el;
#line 165 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_container_add ((GtkContainer*) _tmp9_, (GtkWidget*) _tmp10_);
#line 152 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (child_1);
#line 152 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (child_0);
#line 152 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return self;
#line 804 "DialogTemplateSelect.vala.c"
}


Xcls_DialogTemplateSelectXcls_HBox3* xcls_dialogtemplateselect_xcls_hbox3_new (Xcls_DialogTemplateSelect* _owner) {
#line 152 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return xcls_dialogtemplateselect_xcls_hbox3_construct (XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_HBOX3, _owner);
#line 811 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_hbox3_class_init (Xcls_DialogTemplateSelectXcls_HBox3Class * klass) {
#line 143 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	xcls_dialogtemplateselect_xcls_hbox3_parent_class = g_type_class_peek_parent (klass);
#line 143 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_type_class_add_private (klass, sizeof (Xcls_DialogTemplateSelectXcls_HBox3Private));
#line 143 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_dialogtemplateselect_xcls_hbox3_finalize;
#line 822 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_hbox3_instance_init (Xcls_DialogTemplateSelectXcls_HBox3 * self) {
#line 143 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->priv = XCLS_DIALOGTEMPLATESELECT_XCLS_HBOX3_GET_PRIVATE (self);
#line 829 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_hbox3_finalize (GObject* obj) {
	Xcls_DialogTemplateSelectXcls_HBox3 * self;
#line 143 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_HBOX3, Xcls_DialogTemplateSelectXcls_HBox3);
#line 145 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->el);
#line 146 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->priv->_this);
#line 143 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	G_OBJECT_CLASS (xcls_dialogtemplateselect_xcls_hbox3_parent_class)->finalize (obj);
#line 843 "DialogTemplateSelect.vala.c"
}


GType xcls_dialogtemplateselect_xcls_hbox3_get_type (void) {
	static volatile gsize xcls_dialogtemplateselect_xcls_hbox3_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_dialogtemplateselect_xcls_hbox3_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_DialogTemplateSelectXcls_HBox3Class), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_dialogtemplateselect_xcls_hbox3_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_DialogTemplateSelectXcls_HBox3), 0, (GInstanceInitFunc) xcls_dialogtemplateselect_xcls_hbox3_instance_init, NULL };
		GType xcls_dialogtemplateselect_xcls_hbox3_type_id;
		xcls_dialogtemplateselect_xcls_hbox3_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_DialogTemplateSelectXcls_HBox3", &g_define_type_info, 0);
		g_once_init_leave (&xcls_dialogtemplateselect_xcls_hbox3_type_id__volatile, xcls_dialogtemplateselect_xcls_hbox3_type_id);
	}
	return xcls_dialogtemplateselect_xcls_hbox3_type_id__volatile;
}


Xcls_DialogTemplateSelectXcls_Label4* xcls_dialogtemplateselect_xcls_label4_construct (GType object_type, Xcls_DialogTemplateSelect* _owner) {
	Xcls_DialogTemplateSelectXcls_Label4 * self = NULL;
	GtkLabel* _tmp0_;
	Xcls_DialogTemplateSelect* _tmp1_;
	Xcls_DialogTemplateSelect* _tmp2_;
#line 197 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 197 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self = (Xcls_DialogTemplateSelectXcls_Label4*) g_object_new (object_type, NULL);
#line 199 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp0_ = (GtkLabel*) gtk_label_new ("Select Template : ");
#line 199 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_object_ref_sink (_tmp0_);
#line 199 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->el);
#line 199 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->el = _tmp0_;
#line 200 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp1_ = _owner;
#line 200 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 200 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->priv->_this);
#line 200 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->priv->_this = _tmp2_;
#line 197 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return self;
#line 886 "DialogTemplateSelect.vala.c"
}


Xcls_DialogTemplateSelectXcls_Label4* xcls_dialogtemplateselect_xcls_label4_new (Xcls_DialogTemplateSelect* _owner) {
#line 197 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return xcls_dialogtemplateselect_xcls_label4_construct (XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_LABEL4, _owner);
#line 893 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_label4_class_init (Xcls_DialogTemplateSelectXcls_Label4Class * klass) {
#line 188 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	xcls_dialogtemplateselect_xcls_label4_parent_class = g_type_class_peek_parent (klass);
#line 188 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_type_class_add_private (klass, sizeof (Xcls_DialogTemplateSelectXcls_Label4Private));
#line 188 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_dialogtemplateselect_xcls_label4_finalize;
#line 904 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_label4_instance_init (Xcls_DialogTemplateSelectXcls_Label4 * self) {
#line 188 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->priv = XCLS_DIALOGTEMPLATESELECT_XCLS_LABEL4_GET_PRIVATE (self);
#line 911 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_label4_finalize (GObject* obj) {
	Xcls_DialogTemplateSelectXcls_Label4 * self;
#line 188 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_LABEL4, Xcls_DialogTemplateSelectXcls_Label4);
#line 190 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->el);
#line 191 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->priv->_this);
#line 188 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	G_OBJECT_CLASS (xcls_dialogtemplateselect_xcls_label4_parent_class)->finalize (obj);
#line 925 "DialogTemplateSelect.vala.c"
}


GType xcls_dialogtemplateselect_xcls_label4_get_type (void) {
	static volatile gsize xcls_dialogtemplateselect_xcls_label4_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_dialogtemplateselect_xcls_label4_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_DialogTemplateSelectXcls_Label4Class), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_dialogtemplateselect_xcls_label4_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_DialogTemplateSelectXcls_Label4), 0, (GInstanceInitFunc) xcls_dialogtemplateselect_xcls_label4_instance_init, NULL };
		GType xcls_dialogtemplateselect_xcls_label4_type_id;
		xcls_dialogtemplateselect_xcls_label4_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_DialogTemplateSelectXcls_Label4", &g_define_type_info, 0);
		g_once_init_leave (&xcls_dialogtemplateselect_xcls_label4_type_id__volatile, xcls_dialogtemplateselect_xcls_label4_type_id);
	}
	return xcls_dialogtemplateselect_xcls_label4_type_id__volatile;
}


Xcls_DialogTemplateSelectXcls_combo* xcls_dialogtemplateselect_xcls_combo_construct (GType object_type, Xcls_DialogTemplateSelect* _owner) {
	Xcls_DialogTemplateSelectXcls_combo * self = NULL;
	GtkComboBox* _tmp0_;
	Xcls_DialogTemplateSelect* _tmp1_;
	Xcls_DialogTemplateSelect* _tmp2_;
	Xcls_DialogTemplateSelect* _tmp3_;
	Xcls_DialogTemplateSelectXcls_combo* _tmp4_;
	Xcls_DialogTemplateSelect* _tmp5_;
	Xcls_DialogTemplateSelectXcls_cellrenderer* _tmp6_;
	Xcls_DialogTemplateSelectXcls_cellrenderer* child_0;
	GtkComboBox* _tmp7_;
	GtkCellRendererText* _tmp8_;
	Xcls_DialogTemplateSelect* _tmp9_;
	Xcls_DialogTemplateSelectXcls_model* _tmp10_;
	Xcls_DialogTemplateSelectXcls_model* child_1;
	GtkComboBox* _tmp11_;
	GtkListStore* _tmp12_;
	GtkComboBox* _tmp13_;
	Xcls_DialogTemplateSelect* _tmp14_;
	Xcls_DialogTemplateSelectXcls_cellrenderer* _tmp15_;
	GtkCellRendererText* _tmp16_;
#line 232 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 232 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self = (Xcls_DialogTemplateSelectXcls_combo*) g_object_new (object_type, NULL);
#line 234 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp0_ = (GtkComboBox*) gtk_combo_box_new ();
#line 234 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_object_ref_sink (_tmp0_);
#line 234 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->el);
#line 234 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->el = _tmp0_;
#line 235 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp1_ = _owner;
#line 235 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 235 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->priv->_this);
#line 235 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->priv->_this = _tmp2_;
#line 236 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp3_ = self->priv->_this;
#line 236 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp4_ = _g_object_ref0 (self);
#line 236 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (_tmp3_->combo);
#line 236 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp3_->combo = _tmp4_;
#line 241 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp5_ = self->priv->_this;
#line 241 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp6_ = xcls_dialogtemplateselect_xcls_cellrenderer_new (_tmp5_);
#line 241 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	child_0 = _tmp6_;
#line 242 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_object_ref ((GObject*) child_0);
#line 243 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp7_ = self->el;
#line 243 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp8_ = child_0->el;
#line 243 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_cell_layout_pack_start ((GtkCellLayout*) _tmp7_, (GtkCellRenderer*) _tmp8_, TRUE);
#line 244 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp9_ = self->priv->_this;
#line 244 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp10_ = xcls_dialogtemplateselect_xcls_model_new (_tmp9_);
#line 244 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	child_1 = _tmp10_;
#line 245 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_object_ref ((GObject*) child_1);
#line 246 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp11_ = self->el;
#line 246 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp12_ = child_1->el;
#line 246 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_combo_box_set_model (_tmp11_, (GtkTreeModel*) _tmp12_);
#line 249 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp13_ = self->el;
#line 249 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp14_ = self->priv->_this;
#line 249 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp15_ = _tmp14_->cellrenderer;
#line 249 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp16_ = _tmp15_->el;
#line 249 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_cell_layout_add_attribute ((GtkCellLayout*) _tmp13_, (GtkCellRenderer*) _tmp16_, "markup", 1);
#line 232 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (child_1);
#line 232 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (child_0);
#line 232 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return self;
#line 1034 "DialogTemplateSelect.vala.c"
}


Xcls_DialogTemplateSelectXcls_combo* xcls_dialogtemplateselect_xcls_combo_new (Xcls_DialogTemplateSelect* _owner) {
#line 232 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return xcls_dialogtemplateselect_xcls_combo_construct (XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_COMBO, _owner);
#line 1041 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_combo_class_init (Xcls_DialogTemplateSelectXcls_comboClass * klass) {
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	xcls_dialogtemplateselect_xcls_combo_parent_class = g_type_class_peek_parent (klass);
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_type_class_add_private (klass, sizeof (Xcls_DialogTemplateSelectXcls_comboPrivate));
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_dialogtemplateselect_xcls_combo_finalize;
#line 1052 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_combo_instance_init (Xcls_DialogTemplateSelectXcls_combo * self) {
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->priv = XCLS_DIALOGTEMPLATESELECT_XCLS_COMBO_GET_PRIVATE (self);
#line 1059 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_combo_finalize (GObject* obj) {
	Xcls_DialogTemplateSelectXcls_combo * self;
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_COMBO, Xcls_DialogTemplateSelectXcls_combo);
#line 225 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->el);
#line 226 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->priv->_this);
#line 223 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	G_OBJECT_CLASS (xcls_dialogtemplateselect_xcls_combo_parent_class)->finalize (obj);
#line 1073 "DialogTemplateSelect.vala.c"
}


GType xcls_dialogtemplateselect_xcls_combo_get_type (void) {
	static volatile gsize xcls_dialogtemplateselect_xcls_combo_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_dialogtemplateselect_xcls_combo_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_DialogTemplateSelectXcls_comboClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_dialogtemplateselect_xcls_combo_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_DialogTemplateSelectXcls_combo), 0, (GInstanceInitFunc) xcls_dialogtemplateselect_xcls_combo_instance_init, NULL };
		GType xcls_dialogtemplateselect_xcls_combo_type_id;
		xcls_dialogtemplateselect_xcls_combo_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_DialogTemplateSelectXcls_combo", &g_define_type_info, 0);
		g_once_init_leave (&xcls_dialogtemplateselect_xcls_combo_type_id__volatile, xcls_dialogtemplateselect_xcls_combo_type_id);
	}
	return xcls_dialogtemplateselect_xcls_combo_type_id__volatile;
}


Xcls_DialogTemplateSelectXcls_cellrenderer* xcls_dialogtemplateselect_xcls_cellrenderer_construct (GType object_type, Xcls_DialogTemplateSelect* _owner) {
	Xcls_DialogTemplateSelectXcls_cellrenderer * self = NULL;
	GtkCellRendererText* _tmp0_;
	Xcls_DialogTemplateSelect* _tmp1_;
	Xcls_DialogTemplateSelect* _tmp2_;
	Xcls_DialogTemplateSelect* _tmp3_;
	Xcls_DialogTemplateSelectXcls_cellrenderer* _tmp4_;
#line 281 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 281 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self = (Xcls_DialogTemplateSelectXcls_cellrenderer*) g_object_new (object_type, NULL);
#line 283 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp0_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
#line 283 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_object_ref_sink (_tmp0_);
#line 283 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->el);
#line 283 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->el = _tmp0_;
#line 284 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp1_ = _owner;
#line 284 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 284 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->priv->_this);
#line 284 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->priv->_this = _tmp2_;
#line 285 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp3_ = self->priv->_this;
#line 285 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp4_ = _g_object_ref0 (self);
#line 285 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (_tmp3_->cellrenderer);
#line 285 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp3_->cellrenderer = _tmp4_;
#line 281 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return self;
#line 1126 "DialogTemplateSelect.vala.c"
}


Xcls_DialogTemplateSelectXcls_cellrenderer* xcls_dialogtemplateselect_xcls_cellrenderer_new (Xcls_DialogTemplateSelect* _owner) {
#line 281 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return xcls_dialogtemplateselect_xcls_cellrenderer_construct (XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_CELLRENDERER, _owner);
#line 1133 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_cellrenderer_class_init (Xcls_DialogTemplateSelectXcls_cellrendererClass * klass) {
#line 272 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	xcls_dialogtemplateselect_xcls_cellrenderer_parent_class = g_type_class_peek_parent (klass);
#line 272 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_type_class_add_private (klass, sizeof (Xcls_DialogTemplateSelectXcls_cellrendererPrivate));
#line 272 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_dialogtemplateselect_xcls_cellrenderer_finalize;
#line 1144 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_cellrenderer_instance_init (Xcls_DialogTemplateSelectXcls_cellrenderer * self) {
#line 272 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->priv = XCLS_DIALOGTEMPLATESELECT_XCLS_CELLRENDERER_GET_PRIVATE (self);
#line 1151 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_cellrenderer_finalize (GObject* obj) {
	Xcls_DialogTemplateSelectXcls_cellrenderer * self;
#line 272 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_CELLRENDERER, Xcls_DialogTemplateSelectXcls_cellrenderer);
#line 274 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->el);
#line 275 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->priv->_this);
#line 272 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	G_OBJECT_CLASS (xcls_dialogtemplateselect_xcls_cellrenderer_parent_class)->finalize (obj);
#line 1165 "DialogTemplateSelect.vala.c"
}


GType xcls_dialogtemplateselect_xcls_cellrenderer_get_type (void) {
	static volatile gsize xcls_dialogtemplateselect_xcls_cellrenderer_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_dialogtemplateselect_xcls_cellrenderer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_DialogTemplateSelectXcls_cellrendererClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_dialogtemplateselect_xcls_cellrenderer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_DialogTemplateSelectXcls_cellrenderer), 0, (GInstanceInitFunc) xcls_dialogtemplateselect_xcls_cellrenderer_instance_init, NULL };
		GType xcls_dialogtemplateselect_xcls_cellrenderer_type_id;
		xcls_dialogtemplateselect_xcls_cellrenderer_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_DialogTemplateSelectXcls_cellrenderer", &g_define_type_info, 0);
		g_once_init_leave (&xcls_dialogtemplateselect_xcls_cellrenderer_type_id__volatile, xcls_dialogtemplateselect_xcls_cellrenderer_type_id);
	}
	return xcls_dialogtemplateselect_xcls_cellrenderer_type_id__volatile;
}


Xcls_DialogTemplateSelectXcls_model* xcls_dialogtemplateselect_xcls_model_construct (GType object_type, Xcls_DialogTemplateSelect* _owner) {
	Xcls_DialogTemplateSelectXcls_model * self = NULL;
	GtkListStore* _tmp0_;
	Xcls_DialogTemplateSelect* _tmp1_;
	Xcls_DialogTemplateSelect* _tmp2_;
	Xcls_DialogTemplateSelect* _tmp3_;
	Xcls_DialogTemplateSelectXcls_model* _tmp4_;
#line 317 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 317 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self = (Xcls_DialogTemplateSelectXcls_model*) g_object_new (object_type, NULL);
#line 319 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp0_ = gtk_list_store_new (2, G_TYPE_STRING, G_TYPE_STRING);
#line 319 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->el);
#line 319 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->el = _tmp0_;
#line 320 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp1_ = _owner;
#line 320 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 320 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->priv->_this);
#line 320 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->priv->_this = _tmp2_;
#line 321 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp3_ = self->priv->_this;
#line 321 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp4_ = _g_object_ref0 (self);
#line 321 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (_tmp3_->model);
#line 321 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp3_->model = _tmp4_;
#line 317 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return self;
#line 1216 "DialogTemplateSelect.vala.c"
}


Xcls_DialogTemplateSelectXcls_model* xcls_dialogtemplateselect_xcls_model_new (Xcls_DialogTemplateSelect* _owner) {
#line 317 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return xcls_dialogtemplateselect_xcls_model_construct (XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_MODEL, _owner);
#line 1223 "DialogTemplateSelect.vala.c"
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
#line 1242 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1242 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	g_return_val_if_fail (old != NULL, NULL);
#line 1242 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	g_return_val_if_fail (replacement != NULL, NULL);
#line 1236 "DialogTemplateSelect.vala.c"
	{
		const gchar* _tmp0_;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_;
		GRegex* _tmp3_;
		GRegex* _tmp4_;
		GRegex* regex;
		GRegex* _tmp5_;
		const gchar* _tmp6_;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_;
#line 1244 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp0_ = old;
#line 1244 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
#line 1244 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp2_ = _tmp1_;
#line 1244 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
#line 1244 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp4_ = _tmp3_;
#line 1244 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_g_free0 (_tmp2_);
#line 1244 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		regex = _tmp4_;
#line 1244 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		if (_inner_error_ != NULL) {
#line 1244 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
			if (_inner_error_->domain == G_REGEX_ERROR) {
#line 1266 "DialogTemplateSelect.vala.c"
				goto __catch8_g_regex_error;
			}
#line 1244 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 1244 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
			g_clear_error (&_inner_error_);
#line 1244 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
			return NULL;
#line 1275 "DialogTemplateSelect.vala.c"
		}
#line 1245 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp5_ = regex;
#line 1245 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp6_ = replacement;
#line 1245 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp7_ = g_regex_replace_literal (_tmp5_, self, (gssize) (-1), 0, _tmp6_, 0, &_inner_error_);
#line 1245 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_tmp8_ = _tmp7_;
#line 1245 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		if (_inner_error_ != NULL) {
#line 1245 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
			_g_regex_unref0 (regex);
#line 1245 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
			if (_inner_error_->domain == G_REGEX_ERROR) {
#line 1291 "DialogTemplateSelect.vala.c"
				goto __catch8_g_regex_error;
			}
#line 1245 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
			_g_regex_unref0 (regex);
#line 1245 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 1245 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
			g_clear_error (&_inner_error_);
#line 1245 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
			return NULL;
#line 1302 "DialogTemplateSelect.vala.c"
		}
#line 1245 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		result = _tmp8_;
#line 1245 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_g_regex_unref0 (regex);
#line 1245 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		return result;
#line 1310 "DialogTemplateSelect.vala.c"
	}
	goto __finally8;
	__catch8_g_regex_error:
	{
		GError* e = NULL;
#line 1243 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		e = _inner_error_;
#line 1243 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_inner_error_ = NULL;
#line 1247 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		g_assert_not_reached ();
#line 1243 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		_g_error_free0 (e);
#line 1324 "DialogTemplateSelect.vala.c"
	}
	__finally8:
#line 1243 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
	if (_inner_error_ != NULL) {
#line 1243 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 1243 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		g_clear_error (&_inner_error_);
#line 1243 "/usr/share/vala-0.20/vapi/glib-2.0.vapi"
		return NULL;
#line 1335 "DialogTemplateSelect.vala.c"
	}
}


void xcls_dialogtemplateselect_xcls_model_loadData (Xcls_DialogTemplateSelectXcls_model* self, GList* data) {
	GtkListStore* _tmp0_;
	GtkTreeIter iter = {0};
	GtkListStore* _tmp1_;
	GtkListStore* _tmp2_;
	GtkListStore* el;
	GtkListStore* _tmp3_;
	GtkTreeIter _tmp4_ = {0};
	GtkListStore* _tmp5_;
	GtkTreeIter _tmp6_;
	GValue _tmp7_ = {0};
	GtkListStore* _tmp8_;
	GtkTreeIter _tmp9_;
	GValue _tmp10_ = {0};
#line 339 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_return_if_fail (self != NULL);
#line 340 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp0_ = self->el;
#line 340 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_list_store_clear (_tmp0_);
#line 342 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp1_ = self->el;
#line 342 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 342 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	el = _tmp2_;
#line 344 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp3_ = el;
#line 344 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_list_store_append (_tmp3_, &_tmp4_);
#line 344 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	iter = _tmp4_;
#line 347 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp5_ = el;
#line 347 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp6_ = iter;
#line 347 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_value_init (&_tmp7_, G_TYPE_STRING);
#line 347 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_value_set_string (&_tmp7_, "");
#line 347 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_list_store_set_value (_tmp5_, &_tmp6_, 0, &_tmp7_);
#line 347 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	G_IS_VALUE (&_tmp7_) ? (g_value_unset (&_tmp7_), NULL) : NULL;
#line 348 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp8_ = el;
#line 348 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp9_ = iter;
#line 348 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_value_init (&_tmp10_, G_TYPE_STRING);
#line 348 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_value_set_string (&_tmp10_, "Just add Element");
#line 348 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_list_store_set_value (_tmp8_, &_tmp9_, 1, &_tmp10_);
#line 348 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	G_IS_VALUE (&_tmp10_) ? (g_value_unset (&_tmp10_), NULL) : NULL;
#line 1396 "DialogTemplateSelect.vala.c"
	{
		gint i;
#line 350 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
		i = 0;
#line 1401 "DialogTemplateSelect.vala.c"
		{
			gboolean _tmp11_;
#line 350 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
			_tmp11_ = TRUE;
#line 350 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
			while (TRUE) {
#line 1408 "DialogTemplateSelect.vala.c"
				gboolean _tmp12_;
				gint _tmp14_;
				GList* _tmp15_;
				guint _tmp16_ = 0U;
				GtkListStore* _tmp17_;
				GtkTreeIter _tmp18_ = {0};
				GList* _tmp19_;
				gint _tmp20_;
				gconstpointer _tmp21_ = NULL;
				gchar* _tmp22_;
				gchar* str;
				const gchar* _tmp23_;
				gchar* _tmp24_ = NULL;
				gchar* fn;
				const gchar* _tmp25_;
				gchar* _tmp26_ = NULL;
				gchar* _tmp27_;
				GtkListStore* _tmp28_;
				GtkTreeIter _tmp29_;
				const gchar* _tmp30_;
				GValue _tmp31_ = {0};
				GtkListStore* _tmp32_;
				GtkTreeIter _tmp33_;
				const gchar* _tmp34_;
				GValue _tmp35_ = {0};
#line 350 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp12_ = _tmp11_;
#line 350 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				if (!_tmp12_) {
#line 1438 "DialogTemplateSelect.vala.c"
					gint _tmp13_;
#line 350 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
					_tmp13_ = i;
#line 350 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
					i = _tmp13_ + 1;
#line 1444 "DialogTemplateSelect.vala.c"
				}
#line 350 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp11_ = FALSE;
#line 350 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp14_ = i;
#line 350 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp15_ = data;
#line 350 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp16_ = g_list_length (_tmp15_);
#line 350 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				if (!(((guint) _tmp14_) < _tmp16_)) {
#line 350 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
					break;
#line 1458 "DialogTemplateSelect.vala.c"
				}
#line 353 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp17_ = el;
#line 353 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				gtk_list_store_append (_tmp17_, &_tmp18_);
#line 353 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				iter = _tmp18_;
#line 354 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp19_ = data;
#line 354 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp20_ = i;
#line 354 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp21_ = g_list_nth_data (_tmp19_, (guint) _tmp20_);
#line 354 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp22_ = g_strdup ((const gchar*) _tmp21_);
#line 354 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				str = _tmp22_;
#line 355 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp23_ = str;
#line 355 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp24_ = g_path_get_basename (_tmp23_);
#line 355 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				fn = _tmp24_;
#line 356 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp25_ = fn;
#line 356 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp26_ = string_replace (_tmp25_, ".json", "");
#line 356 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp27_ = _tmp26_;
#line 356 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_g_free0 (_tmp27_);
#line 358 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp28_ = el;
#line 358 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp29_ = iter;
#line 358 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp30_ = fn;
#line 358 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				g_value_init (&_tmp31_, G_TYPE_STRING);
#line 358 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				g_value_set_string (&_tmp31_, _tmp30_);
#line 358 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				gtk_list_store_set_value (_tmp28_, &_tmp29_, 0, &_tmp31_);
#line 358 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				G_IS_VALUE (&_tmp31_) ? (g_value_unset (&_tmp31_), NULL) : NULL;
#line 359 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp32_ = el;
#line 359 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp33_ = iter;
#line 359 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_tmp34_ = str;
#line 359 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				g_value_init (&_tmp35_, G_TYPE_STRING);
#line 359 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				g_value_set_string (&_tmp35_, _tmp34_);
#line 359 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				gtk_list_store_set_value (_tmp32_, &_tmp33_, 1, &_tmp35_);
#line 359 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				G_IS_VALUE (&_tmp35_) ? (g_value_unset (&_tmp35_), NULL) : NULL;
#line 350 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_g_free0 (fn);
#line 350 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
				_g_free0 (str);
#line 1522 "DialogTemplateSelect.vala.c"
			}
		}
	}
#line 339 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (el);
#line 1528 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_model_class_init (Xcls_DialogTemplateSelectXcls_modelClass * klass) {
#line 308 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	xcls_dialogtemplateselect_xcls_model_parent_class = g_type_class_peek_parent (klass);
#line 308 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_type_class_add_private (klass, sizeof (Xcls_DialogTemplateSelectXcls_modelPrivate));
#line 308 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_dialogtemplateselect_xcls_model_finalize;
#line 1539 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_model_instance_init (Xcls_DialogTemplateSelectXcls_model * self) {
#line 308 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->priv = XCLS_DIALOGTEMPLATESELECT_XCLS_MODEL_GET_PRIVATE (self);
#line 1546 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_model_finalize (GObject* obj) {
	Xcls_DialogTemplateSelectXcls_model * self;
#line 308 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_MODEL, Xcls_DialogTemplateSelectXcls_model);
#line 310 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->el);
#line 311 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->priv->_this);
#line 308 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	G_OBJECT_CLASS (xcls_dialogtemplateselect_xcls_model_parent_class)->finalize (obj);
#line 1560 "DialogTemplateSelect.vala.c"
}


GType xcls_dialogtemplateselect_xcls_model_get_type (void) {
	static volatile gsize xcls_dialogtemplateselect_xcls_model_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_dialogtemplateselect_xcls_model_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_DialogTemplateSelectXcls_modelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_dialogtemplateselect_xcls_model_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_DialogTemplateSelectXcls_model), 0, (GInstanceInitFunc) xcls_dialogtemplateselect_xcls_model_instance_init, NULL };
		GType xcls_dialogtemplateselect_xcls_model_type_id;
		xcls_dialogtemplateselect_xcls_model_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_DialogTemplateSelectXcls_model", &g_define_type_info, 0);
		g_once_init_leave (&xcls_dialogtemplateselect_xcls_model_type_id__volatile, xcls_dialogtemplateselect_xcls_model_type_id);
	}
	return xcls_dialogtemplateselect_xcls_model_type_id__volatile;
}


Xcls_DialogTemplateSelectXcls_Button8* xcls_dialogtemplateselect_xcls_button8_construct (GType object_type, Xcls_DialogTemplateSelect* _owner) {
	Xcls_DialogTemplateSelectXcls_Button8 * self = NULL;
	GtkButton* _tmp0_;
	Xcls_DialogTemplateSelect* _tmp1_;
	Xcls_DialogTemplateSelect* _tmp2_;
	GtkButton* _tmp3_;
#line 383 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_return_val_if_fail (_owner != NULL, NULL);
#line 383 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self = (Xcls_DialogTemplateSelectXcls_Button8*) g_object_new (object_type, NULL);
#line 385 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp0_ = (GtkButton*) gtk_button_new ();
#line 385 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_object_ref_sink (_tmp0_);
#line 385 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->el);
#line 385 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->el = _tmp0_;
#line 386 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp1_ = _owner;
#line 386 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 386 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->priv->_this);
#line 386 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->priv->_this = _tmp2_;
#line 391 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_tmp3_ = self->el;
#line 391 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	gtk_button_set_label (_tmp3_, "OK");
#line 383 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return self;
#line 1608 "DialogTemplateSelect.vala.c"
}


Xcls_DialogTemplateSelectXcls_Button8* xcls_dialogtemplateselect_xcls_button8_new (Xcls_DialogTemplateSelect* _owner) {
#line 383 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	return xcls_dialogtemplateselect_xcls_button8_construct (XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_BUTTON8, _owner);
#line 1615 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_button8_class_init (Xcls_DialogTemplateSelectXcls_Button8Class * klass) {
#line 374 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	xcls_dialogtemplateselect_xcls_button8_parent_class = g_type_class_peek_parent (klass);
#line 374 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_type_class_add_private (klass, sizeof (Xcls_DialogTemplateSelectXcls_Button8Private));
#line 374 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_dialogtemplateselect_xcls_button8_finalize;
#line 1626 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_button8_instance_init (Xcls_DialogTemplateSelectXcls_Button8 * self) {
#line 374 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->priv = XCLS_DIALOGTEMPLATESELECT_XCLS_BUTTON8_GET_PRIVATE (self);
#line 1633 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_xcls_button8_finalize (GObject* obj) {
	Xcls_DialogTemplateSelectXcls_Button8 * self;
#line 374 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XCLS_DIALOGTEMPLATESELECT_TYPE_XCLS_BUTTON8, Xcls_DialogTemplateSelectXcls_Button8);
#line 376 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->el);
#line 377 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->priv->_this);
#line 374 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	G_OBJECT_CLASS (xcls_dialogtemplateselect_xcls_button8_parent_class)->finalize (obj);
#line 1647 "DialogTemplateSelect.vala.c"
}


GType xcls_dialogtemplateselect_xcls_button8_get_type (void) {
	static volatile gsize xcls_dialogtemplateselect_xcls_button8_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_dialogtemplateselect_xcls_button8_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_DialogTemplateSelectXcls_Button8Class), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_dialogtemplateselect_xcls_button8_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_DialogTemplateSelectXcls_Button8), 0, (GInstanceInitFunc) xcls_dialogtemplateselect_xcls_button8_instance_init, NULL };
		GType xcls_dialogtemplateselect_xcls_button8_type_id;
		xcls_dialogtemplateselect_xcls_button8_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_DialogTemplateSelectXcls_Button8", &g_define_type_info, 0);
		g_once_init_leave (&xcls_dialogtemplateselect_xcls_button8_type_id__volatile, xcls_dialogtemplateselect_xcls_button8_type_id);
	}
	return xcls_dialogtemplateselect_xcls_button8_type_id__volatile;
}


static void xcls_dialogtemplateselect_class_init (Xcls_DialogTemplateSelectClass * klass) {
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	xcls_dialogtemplateselect_parent_class = g_type_class_peek_parent (klass);
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	g_type_class_add_private (klass, sizeof (Xcls_DialogTemplateSelectPrivate));
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	G_OBJECT_CLASS (klass)->finalize = xcls_dialogtemplateselect_finalize;
#line 1670 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_instance_init (Xcls_DialogTemplateSelect * self) {
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self->priv = XCLS_DIALOGTEMPLATESELECT_GET_PRIVATE (self);
#line 1677 "DialogTemplateSelect.vala.c"
}


static void xcls_dialogtemplateselect_finalize (GObject* obj) {
	Xcls_DialogTemplateSelect * self;
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_XCLS_DIALOGTEMPLATESELECT, Xcls_DialogTemplateSelect);
#line 22 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->el);
#line 23 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->priv->_this);
#line 25 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->combo);
#line 26 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->cellrenderer);
#line 27 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	_g_object_unref0 (self->model);
#line 20 "/home/alan/gitlive/app.Builder.js/Builder4/DialogTemplateSelect.vala"
	G_OBJECT_CLASS (xcls_dialogtemplateselect_parent_class)->finalize (obj);
#line 1697 "DialogTemplateSelect.vala.c"
}


GType xcls_dialogtemplateselect_get_type (void) {
	static volatile gsize xcls_dialogtemplateselect_type_id__volatile = 0;
	if (g_once_init_enter (&xcls_dialogtemplateselect_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (Xcls_DialogTemplateSelectClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xcls_dialogtemplateselect_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Xcls_DialogTemplateSelect), 0, (GInstanceInitFunc) xcls_dialogtemplateselect_instance_init, NULL };
		GType xcls_dialogtemplateselect_type_id;
		xcls_dialogtemplateselect_type_id = g_type_register_static (G_TYPE_OBJECT, "Xcls_DialogTemplateSelect", &g_define_type_info, 0);
		g_once_init_leave (&xcls_dialogtemplateselect_type_id__volatile, xcls_dialogtemplateselect_type_id);
	}
	return xcls_dialogtemplateselect_type_id__volatile;
}



